# Manual Inspection of LLM Relevance Labels

This notebook is a lightweight manual audit tool for the LLM-generated relevance labels. It lets us look directly at randomly sampled queries and their judged candidate recipes instead of relying only on agreement metrics or retrieval metrics.

The notebook does not modify the ground truth files. It only loads:

- `groundtruth_outputs/annotation/llm_groundtruth_labels.jsonl`
- `groundtruth_outputs/annotation/blinded_annotation_items.jsonl`

and joins them into human-readable inspection tables.

## 1. Setup

Set the random seed and display size here. `NUM_RANDOM_QUERIES` controls how many queries are sampled for visual inspection. Each sampled query can show all 50 judged candidates, or fewer if you lower `MAX_DOCS_PER_QUERY_TO_DISPLAY`.

In [1]:
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Optional

import pandas as pd
from IPython.display import display


def find_finalproject_root(start_path: Optional[Path] = None) -> Path:
    """Find the Finalproject directory by walking upward from the current path."""
    current_path = (start_path or Path.cwd()).resolve()
    for candidate_path in [current_path, *current_path.parents]:
        if candidate_path.name == "Finalproject":
            return candidate_path
        nested_finalproject = candidate_path / "Finalproject"
        if nested_finalproject.exists() and nested_finalproject.is_dir():
            return nested_finalproject.resolve()
    raise FileNotFoundError("Could not find the Finalproject directory.")


FINALPROJECT_ROOT = find_finalproject_root()
NOTEBOOK_OUTPUT_DIR = FINALPROJECT_ROOT / "notebooks" / "rec_and_eval" / "groundtruth_outputs"
ANNOTATION_OUTPUT_DIR = NOTEBOOK_OUTPUT_DIR / "annotation"

LLM_LABELS_PATH = ANNOTATION_OUTPUT_DIR / "llm_groundtruth_labels.jsonl"
BLINDED_ITEMS_PATH = ANNOTATION_OUTPUT_DIR / "blinded_annotation_items.jsonl"

RANDOM_SEED = 20260714
NUM_RANDOM_QUERIES = 8
MAX_DOCS_PER_QUERY_TO_DISPLAY = 50

# Options: "blinded_position" or "relevance_desc"
SORT_WITHIN_QUERY = "blinded_position"

RELEVANCE_LABEL_NAMES = {
    0: "0 - not relevant",
    1: "1 - partially related",
    2: "2 - relevant",
    3: "3 - highly relevant",
}

pd.set_option("display.max_colwidth", 220)
pd.set_option("display.max_rows", 80)

print("Finalproject root:", FINALPROJECT_ROOT)
print("LLM labels path:", LLM_LABELS_PATH)
print("Blinded items path:", BLINDED_ITEMS_PATH)

Finalproject root: C:\Users\tientm1\DS300-UIT-RecommenderSystem\Finalproject
LLM labels path: C:\Users\tientm1\DS300-UIT-RecommenderSystem\Finalproject\notebooks\rec_and_eval\groundtruth_outputs\annotation\llm_groundtruth_labels.jsonl
Blinded items path: C:\Users\tientm1\DS300-UIT-RecommenderSystem\Finalproject\notebooks\rec_and_eval\groundtruth_outputs\annotation\blinded_annotation_items.jsonl

## 2. Load Labels and Candidate Metadata

The label file stores only the LLM relevance score and stable identifiers. The blinded annotation item file stores the query text and recipe fields that were shown to the LLM. We join the two files by `(query_id, doc_id, blinded_position)`.

In [2]:
def load_jsonl_records(jsonl_path: Path) -> list[dict]:
    """Load a JSONL file into dictionaries."""
    records = []
    with jsonl_path.open("r", encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            if not line.strip():
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as error:
                raise ValueError(f"Invalid JSON at {jsonl_path}:{line_number}") from error
    return records


label_records = load_jsonl_records(LLM_LABELS_PATH)
blinded_item_records = load_jsonl_records(BLINDED_ITEMS_PATH)

labels_dataframe = pd.DataFrame(label_records)
items_dataframe = pd.DataFrame(blinded_item_records)

print("LLM label rows:", len(labels_dataframe))
print("Blinded item rows:", len(items_dataframe))
print("LLM label queries:", labels_dataframe["query_id"].nunique())
print("Blinded item queries:", items_dataframe["query_id"].nunique())

display(labels_dataframe.head(3))
display(items_dataframe.head(3))

LLM label rows: 25000
Blinded item rows: 25000
LLM label queries: 500
Blinded item queries: 500

,query_id,candidate_id,doc_id,blinded_position,relevance,label_match_strategy,label_reconciled,judge_type,llm_provider,llm_model_name,prompt_version
0,0,D001,3056,1,1,candidate_id,False,llm,openai_compatible_litellm,local-std-03,recipe_relevance_query_batch_title_type_description_v3
1,0,D002,2621,2,2,candidate_id,False,llm,openai_compatible_litellm,local-std-03,recipe_relevance_query_batch_title_type_description_v3
2,0,D003,2683,3,0,candidate_id,False,llm,openai_compatible_litellm,local-std-03,recipe_relevance_query_batch_title_type_description_v3

,query_id,doc_id,blinded_position,query_text,recipe_title,recipe_type,recipe_description,ingredients,normalized_ingredients,cooking_steps
0,0,3056,1,Bánh trung thu nướng nhân đậu xanh bằng nồi chiên không dầu,Bánh trung thu dẻo chay không dùng lò nướng,Món bánh,"Những chiếc bánh trung thu dẻo mềm, ngọt bùi thật không thể thiếu trong mùa trung thu. Vậy bạn an chay thì sao? Cùng Điện máy XANH vào bếp làm bánh dẻo trung thu chay đơn giản, nhanh chóng mà không cần dùng lò nướng .",250 g Đậu xanh đã ngâm qua đêm | 620 g Đường | 1/2 quả Nước chanh | 1/2 muỗng cà phê Muối | 40 ml Dầu ăn | 1 muỗng cà phê Nước hoa bưởi | 200 g Bột bánh dẻo,muỗng cà phê muối | đường | dầu ăn | bột bánh dẻo | đậu xanh đã ngâm qua đêm | nước hoa bưởi | quả nước chanh,"Bước 1: Làm nước đường: Cho 350 ml nước cùng 0.5 kg đường thêm ½ nước quả chanh để không bị lại đường rồi bắt lên bếp đun sôi, không khuấy khi nấu mà để cho đường tan hết. Sau khi nước đường sôi, để lửa nhỏ và nấu..."
1,0,2621,2,Bánh trung thu nướng nhân đậu xanh bằng nồi chiên không dầu,Bánh trung thu đậu xanh trứng muối sầu riêng với nồi cơm điện,Món bánh,"Bánh trung thu đậu xanh sầu riêng có vỏ bánh vàng óng, mềm tan, nhân bên trong thì ngọt bùi, thơm phức mùi sầu riêng. Đặc biệt, công thức mà Điện máy XANH chia sẻ ngay sau đây được làm hoàn toàn bằng nồi cơm điện. Và...",250 g Bột mì đa dụng (Phần vỏ bánh) | 2 cái Lòng đỏ trứng gà (Phần vỏ bánh) | 40 ml Dầu ăn (Phần vỏ bánh) | 20 g Bơ đậu phộng (Phần vỏ bánh) | 150 g Đậu xanh (Phần nhân bánh) | 50 g Sầu riêng (Phần nhân bánh) | 1 muỗ...,nước đường bánh nướng mua sẵn hoặc tự nấu | lòng đỏ trứng gà phần nước quết bánh | dầu ăn phần nhân bánh | đậu xanh phần nhân bánh | trứng vịt muối phần nhân bánh | lòng đỏ trứng gà phần vỏ bánh | đường phần nhân bán...,"Bước 1: Hầm đậu: Rửa sạch đậu xanh, cho vào nồi cùng 300ml nước và nấu khoảng 20 phút cho đậu chín nhừ. | Bước 2: Xay nhuyễn đậu và sầu riêng: Khi đậu vừa chín nhừ, bạn cho vào khoảng ¼ muỗng cà phê muối, 4 muỗng cà ..."
2,0,2683,3,Bánh trung thu nướng nhân đậu xanh bằng nồi chiên không dầu,Cách chiên bánh bao bằng nồi chiên không dầu vàng ruộm nhanh chóng tại nhà,Món bánh,"Thay vì phải chiên ngập dầu, bạn hoàn toàn có thể sử dụng nồi chiên không dầu để làm bánh bao chiên một cách nhanh chóng, ít dầu mỡ mà vẫn giữ được độ giòn ngon. Điện máy XANH sẽ cùng bạn vào bếp khám phá cách chiên ...",10 cái Bánh bao không nhân | 1 ít Dầu ăn (hoặc bơ) | 1 ít Sữa đặc,bánh bao không nhân | dầu ăn hoặc bơ | sữa đặc,"Bước 1: Chiên bánh bao: Bạn xếp bánh bao vào khay chiên, có thể lót thêm 1 lớp giấy nến để tăng khả năng chống dính. Tiếp đến, bạn dùng cọ quét một lớp dầu ăn mỏng lên trên các mặt bánh bao. Bạn đặt khay chiên vào nồ..."

## 3. Validate Coverage and Build the Inspection Table

Before manual inspection, this section checks that both files cover exactly the same 500 queries and 25,000 `(query, document)` pairs. Any mismatch should be fixed before trusting the visual inspection table.

In [3]:
EXPECTED_NUM_QUERIES = 500
EXPECTED_LABELS_PER_QUERY = 50
EXPECTED_TOTAL_LABELS = EXPECTED_NUM_QUERIES * EXPECTED_LABELS_PER_QUERY

required_label_columns = {"query_id", "doc_id", "blinded_position", "candidate_id", "relevance"}
required_item_columns = {
    "query_id",
    "doc_id",
    "blinded_position",
    "query_text",
    "recipe_title",
    "recipe_type",
    "recipe_description",
}

missing_label_columns = sorted(required_label_columns - set(labels_dataframe.columns))
missing_item_columns = sorted(required_item_columns - set(items_dataframe.columns))
if missing_label_columns:
    raise ValueError(f"Missing label columns: {missing_label_columns}")
if missing_item_columns:
    raise ValueError(f"Missing blinded item columns: {missing_item_columns}")

if len(labels_dataframe) != EXPECTED_TOTAL_LABELS:
    raise ValueError(f"Expected {EXPECTED_TOTAL_LABELS} label rows, found {len(labels_dataframe)}.")
if len(items_dataframe) != EXPECTED_TOTAL_LABELS:
    raise ValueError(f"Expected {EXPECTED_TOTAL_LABELS} blinded item rows, found {len(items_dataframe)}.")

labels_per_query = Counter(labels_dataframe.groupby("query_id").size())
items_per_query = Counter(items_dataframe.groupby("query_id").size())
if dict(labels_per_query) != {EXPECTED_LABELS_PER_QUERY: EXPECTED_NUM_QUERIES}:
    raise ValueError(f"Unexpected labels per query distribution: {dict(labels_per_query)}")
if dict(items_per_query) != {EXPECTED_LABELS_PER_QUERY: EXPECTED_NUM_QUERIES}:
    raise ValueError(f"Unexpected blinded items per query distribution: {dict(items_per_query)}")

if not labels_dataframe["relevance"].isin([0, 1, 2, 3]).all():
    raise ValueError("Found relevance labels outside the allowed 0-3 range.")

inspection_dataframe = labels_dataframe.merge(
    items_dataframe,
    on=["query_id", "doc_id", "blinded_position"],
    how="inner",
    validate="one_to_one",
)

if len(inspection_dataframe) != EXPECTED_TOTAL_LABELS:
    raise ValueError(
        f"Expected merged inspection table to have {EXPECTED_TOTAL_LABELS} rows, "
        f"found {len(inspection_dataframe)}."
    )

inspection_dataframe["relevance_name"] = inspection_dataframe["relevance"].map(RELEVANCE_LABEL_NAMES)
inspection_dataframe = inspection_dataframe.sort_values(["query_id", "blinded_position"]).reset_index(drop=True)

print("Coverage validation: OK")
print("Merged inspection rows:", len(inspection_dataframe))
print("Relevance distribution:")
display(
    inspection_dataframe["relevance"]
    .value_counts()
    .sort_index()
    .rename_axis("relevance")
    .reset_index(name="num_pairs")
)

Coverage validation: OK
Merged inspection rows: 25000
Relevance distribution:

   relevance  num_pairs
0          0      13505
1          1       7713
2          2       3013
3          3        769

## 4. Random Query-Level Inspection

This is the main manual check. For each sampled query, the notebook prints the query text, shows the relevance distribution within its 50 candidates, and displays the candidate recipes with the LLM relevance score.

Use `SORT_WITHIN_QUERY = "blinded_position"` to see the same order that was sent to the LLM. Use `SORT_WITHIN_QUERY = "relevance_desc"` to group highly relevant candidates at the top.

In [4]:
INSPECTION_COLUMNS = [
    "candidate_id",
    "blinded_position",
    "doc_id",
    "relevance",
    "relevance_name",
    "recipe_title",
    "recipe_type",
    "recipe_description",
    "normalized_ingredients",
]


def get_query_inspection_table(query_id: int, sort_within_query: str = SORT_WITHIN_QUERY) -> pd.DataFrame:
    """Return a readable inspection table for one query."""
    query_rows = inspection_dataframe[inspection_dataframe["query_id"] == query_id].copy()
    if query_rows.empty:
        raise ValueError(f"Unknown query_id={query_id}")

    if sort_within_query == "blinded_position":
        query_rows = query_rows.sort_values("blinded_position")
    elif sort_within_query == "relevance_desc":
        query_rows = query_rows.sort_values(["relevance", "blinded_position"], ascending=[False, True])
    else:
        raise ValueError("sort_within_query must be either 'blinded_position' or 'relevance_desc'.")

    available_columns = [column for column in INSPECTION_COLUMNS if column in query_rows.columns]
    return query_rows[available_columns].head(MAX_DOCS_PER_QUERY_TO_DISPLAY).reset_index(drop=True)


def display_query_inspection(query_id: int, sort_within_query: str = SORT_WITHIN_QUERY) -> None:
    """Print one query and display its candidate labels."""
    query_rows = inspection_dataframe[inspection_dataframe["query_id"] == query_id]
    query_text = query_rows["query_text"].iloc[0]
    relevance_distribution = query_rows["relevance"].value_counts().sort_index()

    print("=" * 120)
    print(f"query_id: {query_id}")
    print(f"query_text: {query_text}")
    print("relevance distribution:", dict(relevance_distribution))
    display(get_query_inspection_table(query_id, sort_within_query=sort_within_query))


sampled_query_ids = (
    inspection_dataframe[["query_id"]]
    .drop_duplicates()
    .sample(n=NUM_RANDOM_QUERIES, random_state=RANDOM_SEED)["query_id"]
    .tolist()
)

print("Sampled query IDs:", sampled_query_ids)
for sampled_query_id in sampled_query_ids:
    display_query_inspection(sampled_query_id, sort_within_query=SORT_WITHIN_QUERY)

Sampled query IDs: [242, 270, 485, 135, 151, 317, 360, 214]
========================================================================================================================
query_id: 242
query_text: Bánh đa cá rô ăn kèm với rau cải cực ngon đơn giản ngay tại nhà
relevance distribution: {0: np.int64(15), 1: np.int64(27), 2: np.int64(7), 3: np.int64(1)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,4462,3,3 - highly relevant,Bánh đa cá rô ăn kèm với rau cải cực ngon đơn giản ngay tại nhà,Món nước,"Bánh đa cá rô có lẽ không quá xa lạ đối với chúng ta, tuy nguyên liệu dân dã dễ tìm nhưng mùi vị thanh ngọt của món nước này lại là thứ khiến ta khó quên. Hôm nay, hãy cùng vào bếp với Điện máy XANH để xem cách nấu b...",bó cải xanh | gừng | dầu ăn | bột nghệ | hành tím | gia vị thông dụng muối/ hạt nêm/ đường/tiêu | rau thì là | cá rô | hành lá | ngò | bánh đa
1,D002,2,6636,1,1 - partially related,Cơm cá rô giòn thơm hấp dẫn chuẩn vị miền Bắc,Món chiên,"Cá rô là một loại cá dân dã gắn với bữa cơm hằng ngày của người Việt Nam. Ngoài các cách nấu thường ngày, hôm nay Điện máy XANH xin giới thiệu với các bạn món chiên mới lạ của người miền Bắc - Cơm cá rô. Hãy cùng vào...",gừng | dầu ăn | hành tím | gạo | cá rô khoảng | rau thì là | hành phi | muối hạt | nước mắm | gia vị thông dụng hạt nêm/ muối/ tiêu
2,D003,3,7017,1,1 - partially related,"Cá rô chiên nước mắm cay nồng, thấm vị chuẩn cơm gia đình",Món chiên,"Cá rô chiên nước mắm là món chiên thơm ngon, hấp dẫn với cách làm siêu nhanh, đơn giản, thích hợp để bạn trổ tài nấu cho cả nhà thưởng thức vào những ngày bận rộn với công việc. Cùng vào bếp và xem ngay cách thực hiệ...",cá rô phi | dầu ăn | rượu trắng | gia vị thông dụng đường/ bột ngọt/ muối | nước mắm | ớt | tỏi
3,D004,4,6673,1,1 - partially related,Cá rô bí chiên giòn chấm nước mắm chua ngọt bằng chảo inox,Món chiên,"Cá rô bí hay cá rô non có thể chế biến thành nhiều món, trong đó có cá rô bí chiên giòn. Món chiên này không chỉ đơn giản, mà còn dễ ăn vì có thể ăn luôn cả xương cá. Vào bếp tìm hiểu ngay cách làm món ăn hấp dẫn này...",đường | dầu ăn | ớt băm | ói bột tẩm khô chiên giòn | sả băm | cá rô bí | nước mắm | nước cốt me | tỏi băm
4,D005,5,1597,1,1 - partially related,"Canh cá khoai rau cải ngọt ngon, dinh dưỡng cho cả nhà",Món canh,"Nếu như vô tình có 1 ngày bạn quá bận rộn không thể chu toàn được cho bữa cơm thì từ giờ đừng lo lắng nữa nhé, bởi đã có sự góp mặt của món canh nóng hổi, hấp dẫn, bổ dưỡng khiến ai cũng mê mẩn. Nào cùng bắt tay vào ...",rau cải ngọt | gia vị thông dụng hạt nêm/ muối/ đường/ tiêu xay | dầu ăn | gừng nhỏ | muỗng canh nước mắm | cá khoai | hành lá | tỏi
5,D006,6,6372,1,1 - partially related,"Cá rô kho củ cải trắng đậm đà, lạ vị đưa cơm tại nhà",Món kho,"Cá rô là nguyên liệu khá phổ biến trong bữa cơm hàng ngày ở mỗi gia đình với nhiều công thức khác nhau. Hôm nay, hãy cùng vào bếp với Điện máy XANH và thử làm ngay cá rô kho củ cải trắng, một món kho đơn giản nhưng l...",nước màu | dầu ăn | cá rô khoảng | củ cải trắng khoảng | nước mắm | hành lá | gia vị thông dụng đường/ tiêu/ bột ngọt/ hạt nêm | ớt | ngò rí
6,D007,7,7375,0,0 - not relevant,"Cá viên sốt cam lạ miệng, thơm ngon và bổ dưỡng",Món chiên,"Cá viên là một trong số những món ăn vặt hấp dẫn, đặc biệt đối với các bạn trẻ. Hôm nay, Điện máy XANH sẽ hướng dẫn cho các bạn làm cá viên sốt cam thơm ngon hấp dẫn ngay tại nhà. Cùng vào bếp thực hiện món chiên này...",nấm mèo | dầu ăn | cá rô phi | gia vị thông dụng đường/muối/tiêu/hạt nêm | bột ớt | cam | bột năng | hành phi
7,D008,8,6653,1,1 - partially related,"Cá rô chiên giòn sốt tỏi ớt đơn giản, thơm ngon, ăn là mê",Món chiên,"Công thức chi tiết cách làm cá rô chiên giòn sốt tỏi ớt đơn giản, thơm ngon, ăn là mê. Click xem và vào bếp làm ngay món ăn để cùng gia đình thưởng thức nhé!",gia vị muối/ giấm/ đường/ nước mắm/ tương ớt | cá rô khoảng | ớt sừng | tỏi
8,D009,9,1440,1,1 - partially related,Canh cá khoai cải cúc (tần ô) ngọt mát đưa cơm cho cả nhà,Món canh,"Như chúng ta thường thấy, một bữa cơm gia đình thì ít nhất phải có một món mặn và một món canh . Món canh thì rất đa dạng. Nhân đây, Điện máy XANH sẽ hướng dẫn bạn cách nấu canh cá khoai cải cúc vừa ngọt mát, vừa đơn...",cải cúc | dầu ăn | hành tím | cá khoai | nước lọc | gia vị thông dụng muối/ bột ngọt/ hạt nêm | nước mắm | muỗng cà phê tiêu xay
9,D010,10,1769,2,2 - relevant,"Canh cải cúc nấu cá rô dân dã, thơm ngon cho bữa cơm thêm hấp dẫn",Món canh,"Canh cải cúc nấu cá rô nghe lạ mà rất quen thuộc, bạn đã được thưởng thức qua chưa? Nếu chưa thì cùng theo chân vào bếp với Điện máy XANH thực hiện món canh dân dã, thơm ngon, đơn giản này cho bữa cơm thêm hấp dẫn nha!",gừng | muối/ tiêu xay | hành tây | cá rô phi khoảng | rau cải xanh | rau cải cúc | nước mắm
10,D011,11,4657,0,0 - not relevant,Cách ướp cá nướng ngon quên lối về tại nhà cực đơn giản,Món nướng,"Bạn đang tìm cách ướp cá nướng ngon để chiêu đãi gia đình? Đừng lo, với mẹo vào bếp này, món cá nướng của bạn sẽ mọng nước, thơm lừng không khói, chuẩn vị món nướng nhà làm. Cùng khám phá công thức độc đáo này nhé!",tỏi to | khế chua hoặc dứa | bó sả | dưa chuột | hành tím | gia vị thông dụng nước mắm/ hạt nêm/ đường/ tương ớt/ giấm/ gừng/ muối/ nước lọc/ tỏi/ ớt | cá rô phi khoảng | rau ăn kèm | chuối xanh
11,D012,12,4444,1,1 - partially related,Bún chả cá Đà Nẵng chuẩn vị thơm ngon đơn giản cho cả nhà,Món nước,Không cần phải đi đâu xa xôi hay đến các nhà hàng đắt tiền bạn vẫn sẽ được thưởng thức ngay món bún chả cá Đà Nẵng thơm ngon đậm vị đặc trưng. Cùng Điện máy XANH vào bếp trổ tài ngay món nước này với công thức cực kỳ...,chả chiên | dầu ăn | muỗng cà phê bột tỏi | rau ăn kèm rau quế/ tía tô/ rau thơm/ ngò rí | gia vị thông dụng muối/ hạt nêm/ đường/ tiêu | cà chua | cá basa | thơm | nước mắm | bắp cải | chả hấp | bí đỏ
12,D013,13,10092,0,0 - not relevant,Mắm cá rô phi đơn giản thơm ngon đậm đà tại nhà,Món khô - mắm,Mắm cá rô phi là một món ăn dân dã và cực kỳ quen thuộc với người dân Việt Nam. Mắm cá rô với hương vị đậm đà đặc trưng sẽ cực kì thích hợp khi ăn kèm với các loại rau hoặc chuối chát trong các bữa ăn gia đình. Cùng ...,gạo rang | gia vị thông dụng muối/ đường/ bột ngọt | cá rô phi | thơm
13,D014,14,3288,0,0 - not relevant,Bánh tráng cá cơm để chiên hoặc nướng đều ngon bằng nồi chiên,Món bánh,"Bánh tráng cá cơm được người Việt sáng tạo để có thể bảo quản loài cá theo mùa này được lâu hơn. Khi đã làm được chiếc bánh tráng cá cơm, bạn có thể chiên hoặc nướng đều vô cùng đơn giản với nồi chiên. Cùng Vào bếp l...",hành lá | bánh tráng mỏng loại nhỏ | cá cơm | gia vị muối/bột ngọt/bột ớt
14,D015,15,1184,1,1 - partially related,Bánh canh cá lóc miền Trung,Món chính,"Bánh này cá lóc này cũng rất đơn giản, quan trọng là cá lóc phải tươi thì món bánh canh này mới mon được",gừng | hành boa rô | bánh canh | cá lóc to | chả cá | hành lá
15,D016,16,8352,1,1 - partially related,Gỏi cá rô phi sống ngon miệng dễ làm không bị tanh,Món gỏi - salad,"Nếu bạn đang tìm một món ăn thơm ngon, thanh mát để chóng ngấy sau những ngày ăn quá nhiều dầu mỡ thì món gỏi trộn chính là giải pháp ""cứu cánh"" tuyệt vời đấy! Cùng vào bếp với Điện máy XANH ngay hôm nay và học ngay ...",mẻ | riềng lớn | gia vị thông dụng đường/muối/hạt nêm/bột ngọt | dầu ăn | thính gạo | lòng đỏ trứng gà | hành tím | á lá chanh | rau thơm ăn kèm tía tô/húng quế/húng lủi/diếp cá | chanh | sả | tương ớt | lá lốt | ớt ...
16,D017,17,10080,0,0 - not relevant,Khô cá rô phi cực kì đơn giản tại nhà mà ai cũng làm được,Món khô - mắm,"Cá rô phi loài cá sống ở nước ngọt, thịt cá ngọt, thơm và dai. Khô cá rô phi được làm từ những con cá rô phi tươi, vậy nên thành phẩm rất ngon và phù hợp để ăn vặt nhâm nhi cùng bia hoặc trộn gỏi cũng khá lạ miệng. V...",gia vị thông dụng muối/ bột nêm/ bột ngọt | cá rô phi | ớt bột | nước mắm | ớt | tỏi
17,D018,18,10189,0,0 - not relevant,Bánh tráng cuốn tôm thơm ngon đơn giản,Món cuốn - trộn,"Bánh tráng cuốn tôm là một món ăn có hương vị thơm ngon, chế biến đơn đơn giản, được nhiều người yêu thích. Hãy cùng vào bếp với Điện máy XANH để trổ tài làm ngay món cuốn hấp dẫn này để chiêu đãi gia đình mình nhé!",bún gạo lứt hoặc bún tươi | bánh tráng loại tùy thích | rau ăn kèm rau xà lách/ lá quế/ diếp cá/ rau thơm | cà rốt | tôm tươi
18,D019,19,7385,0,0 - not relevant,"Chả cá trôi dai ngon lạ vị, ai cũng mê đơn giản tại nhà",Món chiên,"Cá trôi nổi tiếng với lớp thịt săn dày mang vị ngọt tự nhiên, thường xuất hiện trong các món chiên , món kho bữa cơm thường ngày. Hôm nay, cùng vào bếp với Điện máy XANH để khám phá cách làm chả cá trôi thơm ngon tại...",dầu ăn | cá trôi | hành tím | hành lá | gia vị thông dụng tiêu/ bột ngọt/ hạt nêm
19,D020,20,502,1,1 - partially related,Cá rô đồng kho nước dừa,Món ngon cho cuối tuần,"Nếu đã thưởng thức món cá rô kho tộ chế biến theo kiểu Miền Nam thì bạn cũng đừng bỏ qua món cá rô đồng kho nước dừa theo kiểu miền Bắc. Đây là món ăn ngon, mang đậm hương vị quê nhà.",muỗng cà phê muối | nước màu | rau răm | cá rô khoảng | muỗng cà phê tiêu | hạt nêm | nước dừa tươi
20,D021,21,165,2,2 - relevant,Canh cá Quỳnh Côi chuẩn vị đặc sản Thái Bình,Món ngon hàng ngày,"Một bát canh cá dân dã, trọn hương - sắc - vị với thịt cá dai giòn, nước dùng thanh, trứng cá vàng ươm, rau xanh, bánh đa trắng... tựa bức họa đồng quê hấp dẫn. Đây là món ăn nổi tiếng Thái Bình.",hạt tiêu | dầu ăn | cải cúc... tùy mùa nào thức nấy | bó rau cần hoặc rau ngót | hành tím | muối | bó hành hoa | cá rô đồng | bánh đa quỳnh côi sợi mỏng mịn | khi nấu vẫn dữ được độ dai do làm từ gạo chiêm mùa trước ...
21,D022,22,7267,0,0 - not relevant,Chả cá rô phi dai ngon đơn giản dễ làm tại nhà,Món chiên,"Để những bữa ăn gia đình bạn thêm phong phú và hấp dẫn, hãy thử làm chả cá rô phi không chỉ có hương thơm nồng nàn mà còn rất dai ngon, dễ thực hiện. Hãy cùng vào bếp thực hiện món chiên ngon này bạn nhé!",cá rô phi | dầu ăn | mỡ heo | hành tím | thìa là | dấm | nước mắm | gia vị thông dụng bột ngọt/ đường/ hạt nêm/ tiêu xay | ớt | tôm tươi
22,D023,23,4790,1,1 - partially related,Cá rô nướng thơm ngon hấp dẫn đơn giản dễ làm cho bữa cơm,Món nướng,"Đã từng một lần đến miền Tây không ai có thể quên được hương vị các món nướng ở nơi đây. Trong bài viết này, hãy cùng chuyên trang Vào bếp của Điện máy XANH thử ngay món cá rô nướng cực đơn giản mang đậm hương vị đặc...",muối hột | muối/ bột ngọt | cá rô | ớt | dầu dừa
23,D024,24,6872,0,0 - not relevant,"Chả cá rô phi lá lốt giòn, dai thơm ngon và vô cùng đơn giản",Món chiên,"Cá rô phi là là loài cá giàu dinh dưỡng được nhiều người yêu thích và chế biến thành nhiều món ăn ngon. Vì vậy, hôm nay Điện máy XANH sẽ đem đến cho bạn một công thức làm chả cá rô phi lá lốt siêu hấp dẫn đảm bảo cả ...",thịt heo thịt nạc vai xay | dầu ăn | cá rô phi | gia vị thông dụng hạt nêm/ tiêu/ đường/ bột ngọt | nước mắm | lá lốt
24,D025,25,6605,1,1 - partially related,Cá rô kho nghệ thơm lừng mềm ngon đậm đà hương vị,Món kho,"Cá rô kho nghệ là món kho dân dã, đơn giản nhưng đậm đà hương vị Việt. Hôm nay, hãy cùng Điện máy XANH vào bếp và thực hiện ngay món ăn này cho cả gia đình cùng thưởng thức nhé!",gia vị thông dụng muối/đường/bột ngọt/tiêu | cá rô | nước mắm | nghệ khoảng | hành lá cắt nhỏ
25,D026,26,6546,1,1 - partially related,Cá rô phi kho tương riềng đậm đà thơm nức mũi,Món kho,"Cá rô phi kho tương riềng là món kho đậm vị, dân dã, rất hợp khẩu vị người Việt. Thịt cá ngọt mềm, mùi tương bần và riềng thơm phức. Hãy cũng bắt tay vào bếp trổ tài với món ăn hấp dẫn, đậm đà tình quê này nhé!",tương bần | cá rô phi | thịt ba chỉ | sả | ớt | riềng
26,D027,27,7121,1,1 - partially related,Cá rô rang muối dân dã lạ vị đổi món cho bữa cơm gia đình,Món chiên,"Cá rô là loại cá vô cùng quen thuộc, được nhiều người yêu thích nhờ thịt cá dai chắc, béo và rất thơm. Để giữ trọn vị tươi ngon này, bạn hãy vào bếp với Điện máy XANH làm món cá rô rang muối, món chiên ngon đơn giản ...",nước cốt chanh | cá rô | muối hạt
27,D028,28,7552,1,1 - partially related,Xôi cá rô đồng đặc sản Nam Định lạ miệng thơm ngon hấp dẫn,Món hấp,"Nam Định vốn được biết đến là quê hương của món phở nổi tiếng trứ danh khắp nơi. Nhưng liệu bạn có biết rằng, ở đây còn có 1 món hấp không kém cạnh gì không? Cùng vào bếp với Điện máy XANH thực hiện ngay món xôi cá r...",cá rô đồng | gia vị thông dụng hạt nêm/ muối/ bột ngọt | dầu ăn | nếp
28,D029,29,5221,1,1 - partially related,Bánh đa xào chay đơn giản thơm ngon hấp dẫn tại nhà,Món xào,Món chay là sự lựa chọn của nhiều người cho những ngày ngán dầu mỡ muốn thanh lọc lại cơ thể. Cùng vào bếp với Điện máy XANH thực hiện ngay món bánh đa xào chay thanh đạm thơm ngon cho bữa ăn của bạn thêm ngon miệng ...,hành boa rô | dầu ăn | muối/ bột ngọt | cải ngọt | đậu que | đậu phụ trắng | nấm rơm | muỗng canh nước tương | bánh đa khô | ngò rí
29,D030,30,7946,1,1 - partially related,"Lẩu khổ qua cá rô phi siêu ngon, chuẩn vị dễ làm tại nha",Món lẩu,"Nếu ai là một fan thích ăn cá rô phi thì đừng bỏ qua món lẩu khổ qua cá rô phi này nhé, chắc chắn sẽ làm cho cả nhà mình đều tấm tắc khen ngon đó. Cùng Vào bếp bắt tay thực hiện nấu lẩu khổ qua cá rô phi nào!",muỗng cà phê bột ngọt | ói gia vị nấu phở | khổ qua | xương heo | hạt nêm | chả cá rô phi | hành lá
30,D031,31,2681,0,0 - not relevant,Bánh khoai cá kình - bánh xèo cá kình đặc sản Huế thơm ngon dễ làm,Món bánh,"Bánh khoái cá kình - một món ăn dân dã đậm chất đặc sản Huế với độ giòn béo từ vỏ bánh, thịt cá tươi thì mềm mại, ngọt thơm. Đặc biệt, món bánh này còn có công dụng khá hiệu quả trong việc cải thiện giấc ngủ của bạn....",đường | dầu ăn | rau sống ăn kèm | nước chanh | cá kình | bột bánh xèo pha sẵn | nước mắm | ớt | tỏi
31,D032,32,725,2,2 - relevant,Bữa sáng đơn giản với bún cá rô,Bữa sáng đơn giản,"Bún cá rô thực ra cũng không mất quá nhiều thời gian như bạn tưởng. Bạn có thể thực hiện các bước sơ chế từ tối hôm trước để chuẩn bị bữa sáng ngon lành, bổ dưỡng này cho gia đình.",đường | bột nêm | xà lách | dầu ăn | rau thơm | nước dùng | bún | hành lá thái nhuyễn | cá rô | nước mắm | ớt
32,D033,33,1771,2,2 - relevant,"Canh cá rô phi lá giang siêu hấp dẫn, đơn giản cho bữa ăn",Món canh,"Canh cá rô phi lá giang thơm ngon, hấp dẫn lại dễ làm sẽ là một sự lựa chọn lý tưởng cho bữa cơm của gia đình bạn. Nếu bạn đang tìm kiếm một món canh đơn giản, dễ làm mà lại đưa cơm thì hãy cùng vào bếp với Điện máy ...",dầu ăn | hành tím | muối | cá rô phi khoảng | tiêu xay | lá giang | nước mắm
33,D034,34,6600,1,1 - partially related,Cá rô bí kho tiêu thơm ngon đậm đà dễ làm cho bữa cơm,Món kho,"Các món kho luôn được nhiều người ưa thích bởi sự đa dạng cũng như hương vị đậm đà mà chúng đem lại. Hôm nay, chuyên trang Vào bếp của Điện máy XANH sẽ hướng dẫn bạn cách làm món cá rô bí kho tiêu cực ngon, cực hấp d...",dầu ăn | hành tím | gia vị thông dụng muối/ đường/ bột ngọt/ tiêu xay | cá rô bí | nước mắm | hành lá | ớt | tỏi
34,D035,35,1575,2,2 - relevant,"Canh cải cá rô siêu hấp dẫn, thanh mát cho cả nhà",Món canh,"Để bữa cơm truyền thống của gia đình thêm phần trọn vẹn và đủ đầy thì món canh chính là món không thể thiếu. Hôm nay, bạn hãy cùng vào bếp với Điện máy XANH để khám phá ngay công thức nấu canh cải cá rô vừa thơm ngon...",muối/ tiêu xay | gừng | cá rô đồng | rau cải xanh | chanh | nước mắm
35,D036,36,4734,0,0 - not relevant,Cá chìa vôi nướng muối ớt bằng nồi chiên không dầu giòn ngon,Món nướng,"Nếu bạn đang tìm một món nướng đậm đà hương vị biển, cá chìa vôi nướng muối ớt là lựa chọn tuyệt vời. Chỉ với vài bước đơn giản, bạn có thể vào bếp thực hiện món cá cay mặn hấp dẫn, da giòn thơm, thịt ngọt tự nhiên m...",nghệ tươi | sả | món ăn kèm bánh tráng cuốn/ chanh/ rau sống/ mắm nêm | gia vị thông dụng muối/ hạt nêm/ đường/ dầu ăn | cá chìa vôi khoảng | ớt
36,D037,37,4579,0,0 - not relevant,Cách ướp cá rô phi nướng nồi chiên không dầu thơm ngon đậm đà,Món nướng,"Bạn đang tìm cách ướp cá rô phi nướng nồi chiên không dầu ngon chuẩn vị? Vào bếp cùng mình khám phá công thức ướp cá nướng nồi chiên không dầu siêu dễ, đảm bảo món nướng thơm lừng, da giòn thịt ngọt, ai ăn cũng mê!",mỡ hành | cá rô phi khoảng 1 | gia vị thông dụng nước mắm/ dầu hào/ hạt nêm/ tiêu đen/ ớt bột khô không cay/ đường/ dầu ăn | sả băm | đậu phộng rang | hành tím băm | rau ăn kèm dưa leo/ xà lách | tỏi băm | hành phi
37,D038,38,317,0,0 - not relevant,Nem công chả phượng,Món ngon hàng ngày,"Một chút sáng tạo sẽ biến món chả Sài Gòn thành món ăn mới, lạ và rất ngon miệng. Lớp bánh tráng mỏng quấn bên ngoài được thay bằng bánh đa. Đây sẽ là món khai vị hấp dẫn cho bữa Tất niên.",cua | giò sống | khoai môn | cá thác lác | bánh đa bánh tráng nướng | tôm
38,D039,39,4312,2,2 - relevant,Canh cá Quỳnh Côi - canh cá rô Thái Bình thơm ngon đơn giản,Món nước,"Canh cá Quỳnh Côi là một món nước ngon đặc trưng của Thái Bình. Với các nguyên liệu dân dã như cá rô đồng, bánh đa,... bằng sự khéo léo của mình thì bạn có thể hoàn toàn làm được món ăn này. Điện máy XANH sẽ hướng dẫ...",muỗng cà phê bột ngọt | hành lá cắt nhỏ | gừng cắt lát | muỗng canh bột canh | dầu ăn | ớt cắt nhỏ | bánh đa | cá rô | nước mắm | rau răm cắt nhỏ | cà chua
39,D040,40,7003,1,1 - partially related,Cá rô chiên xù chấm mắm gừng giòn rụm cực ngon dễ làm,Món chiên,"Cá rô chiên xù giòn rụm thơm béo, ăn kèm với nước chấm cay cay vị gừng tạo nên một sự kết hợp hài hoà đến cuốn hút. Cùng với Điện máy XANH vào bếp xem ngay cách chế biến món chiên đơn giản này ngay thôi nào!",đường | thìa cà phê ớt băm | gừng băm | cá rô đồng | chanh | nước mắm | rau sống các loại | tỏi băm
40,D041,41,7402,1,1 - partially related,Cá rô phi chiên giòn siêu hấp dẫn không phải ai cũng biết,Món chiên,"Cá rô phi là loại cá chứa khá nhiều chất dinh dưỡng tốt cho người sử dụng và có thể chế biến thành rất nhiều món ăn thơm ngon, hấp dẫn. Vì vậy, hôm nay Điện máy XANH sẽ đem đến cho bạn một công thức làm món cá rô phi...",đường/ muối | rau ăn kèm tía tô/ húng tây/ kinh giới | xà lách | cá rô phi | dầu ăn | dưa leo | hành lá | mắm nêm | thơm | bún tươi | bánh tráng | cà rốt | chuối xanh | ớt | trái chanh | tỏi | đậu phộng
41,D042,42,6074,1,1 - partially related,Cá rô phi om dưa chua thơm ngon đậm đà dễ làm,Món kho,"Cá rô phi om dưa chua là món kho vô cùng hấp dẫn, quen thuộc và được nhiều người ưa thích bởi hương vị ngọt mềm đặc trưng của cá rô. Hãy cùng Điện máy XANH vào bếp thực hiện ngay món cá rô phi om dưa chua thơm ngon nhé.",rau húng quế | mỡ heo hoặc dầu ăn | ớt đỏ | rau răm | dưa cải chua | thịt ba chỉ | sả | rau mùi tàu ngò gai | củ gừng | hành củ | gia vị thông dụng muối/hạt nêm/bột ngọt/bột canh | rau thì là | cá rô phi nhỏ | hành l...
42,D043,43,242,1,1 - partially related,Cá rô phi sốt cà chua,Món ngon hàng ngày,Màu đỏ của cà chua và màu vàng của cá sẽ hấp dẫn ngay các nhóc nhà bạn khi nhìn thấy món cá rô phi sốt cà chua. Đây là món ăn thường ngày rất dễ làm và được nhiều người ưa thích.,hạt tiêu | cá rô phi | rau thì là | nước mắm | hành lá | ớt | gia vị | cà chua
43,D044,44,8164,0,0 - not relevant,Sashimi cá trích ép trứng tại nhà siêu đơn giản chuẩn nhà hàng,Món gỏi - salad,"Mê mẩn Sashimi cá trích ép trứng chuẩn vị nhà hàng? Cùng Vào bếp với công thức Món gỏi - salad độc đáo này, bạn sẽ tự tay làm ra những miếng sashimi cá trích ép trứng tươi ngon, giòn sần sật. Đảm bảo đánh thức mọi gi...",trứng cá chuồn | gia vị ăn kèm gừng hồng/rong nho/củ cải trắng/wasabi/nước tương nhật bản | phi lê cá trích đã làm sạch
44,D045,45,7034,1,1 - partially related,Phi lê cá rô phi chiên giòn siêu dễ bằng chảo chiên ngập dầu,Món chiên,"Nếu bạn đang tìm một món chiên vừa thơm ngon, dễ làm lại đưa cơm thì hãy cùng vào bếp với phi lê cá rô phi chiên giòn. Thịt cá mềm ngọt bên trong, lớp vỏ ngoài vàng ruộm giòn rụm chắc chắn sẽ làm cả nhà thích mê ngay...",gừng | cá rô phi | thì là | gia vị thông dụng hạt nêm/ tiêu xay/ bột năng | bột chiên giòn | trứng gà
45,D046,46,709,1,1 - partially related,"Nem cá rô giòn, ngon đổi vị ngày hè",Thực đơn cho ngày nắng nóng,"Nem cá rô có vỏ vàng ruộm, giòn tan, nhân nem với cá mềm ngọt quyện chút béo ngậy của thịt và tôm, nhân không bị khô, dậy mùi thơm của thì là.",bánh đa nem | thịt nạc vai có chút mỡ xay | nấm hương | thì là | cá rô đồng | mộc nhĩ | cà rốt | hành lá | hành khô | giá đỗ | miến | tôm bóc vỏ

========================================================================================================================
query_id: 270
query_text: Bánh đúc lá lúa - bánh đúc đậu xanh nước cốt dừa mỡ hành thơm béo
relevance distribution: {0: np.int64(48), 1: np.int64(1), 3: np.int64(1)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,4514,0,0 - not relevant,"Kem đậu xanh sữa dừa thơm béo, mát lạnh dễ làm tại nhà",Món kem,"Kem đậu xanh là món kem rất được cả người lớn và trẻ em yêu thích bởi mùi vị ngọt ngào, béo bùi, thơm dịu và rất dễ ăn. Hôm nay, chuyên trang Vào bếp sẽ cùng bạn khám phá tuyệt chiêu chống nóng ngày hè với kem đậu xa...",đậu xanh nguyên vỏ | đường | sữa đặc | đậu xanh đãi vỏ | nước cốt dừa | sữa tươi có đường
1,D002,2,3668,1,1 - partially related,"Nước cốt dừa béo ngậy để chấm với bánh bò, bánh đúc ngọt,...",Món bánh,"Nước cốt dừa nấu sệt là một thành phần không thể thiếu trong nhiều món bánh , món chè truyền thống của người Việt Nam ta. Nếu bạn chưa biết cách nấu nước cốt dừa béo ngon thì mời bạn hãy vào bếp và thực hiện ngay côn...",đường | muối | nước lọc | nước cốt dừa đóng lon | bột năng | bột gạo
2,D003,3,2031,0,0 - not relevant,Bánh ú đậu trắng thơm bùi ngon dễ làm,Món bánh,"Bánh ú đậu trắng mềm dẻo, bùi thơm từ đậu, béo nhẹ vị nước cốt dừa. Với cách chế biến này, bạn có thể tùy ý dùng món bánh với bất kỳ món ăn kèm nào, từ đồ chua đến muối mè cũng đều rất ngon. Vào bếp cùng Điện máy XAN...",nếp | đậu trắng | muối | nước cốt dừa | lá chuối
3,D004,4,3492,0,0 - not relevant,Bánh ú nhân đậu xanh lá dứa thơm ngon hấp dẫn đơn giản,Món bánh,"Bánh ú (bánh bá trạng) là một loại bánh thường được làm vào dịp Tết Đoan Ngọ, được cả người Việt và người Hoa ưu chuộng trong dịp lễ này. Chuyên mục Vào bếp của Điện máy XANH hôm nay sẽ cùng bạn khám phá cách làm món...",hành tây băm nhỏ | đường | á lá dứa | dầu ăn | ói đường vani | cơm dừa bào sợi | gạo nếp | gia vị thông dụng đường/ muối/ tiêu | lá chuối dùng để gói bánh | đậu xanh đãi vỏ | nước cốt dừa | hạt nêm chay
4,D005,5,1957,0,0 - not relevant,Bánh gói lá chuối miền Trung thơm ngon béo ngậy hấp dẫn,Món bánh,"Bánh gói miền Trung với những nguyên liệu đơn giản như bột năng, bột gạo, nước cốt dừa,... lại làm say lòng biết bao thực khách nhờ hương vị thơm ngon, độc đáo. Các bạn hãy vào bếp cùng Điện máy XANH thực hiện món bá...",bột gạo | dầu ăn | đậu xanh | đầu hành cắt nhỏ | bột năng | nước cốt dừa | muối/đường | nước bột gạo | hành lá cắt nhỏ | mè rang
5,D006,6,2770,0,0 - not relevant,"Bánh cuốn ngọt miền Tây nhân đậu xanh dừa thơm ngon, hấp dẫn",Món bánh,"Bánh cuốn ngọt nhân đậu xanh dừa - một món đặc sản bạn nên nếm thử khi ghé thăm miền Tây sông nước. Món bánh có lớp vỏ dai mềm, thơm nhẹ mùi mè rang cùng phần nhân đậu xanh bùi ngọt, beo béo, vô cùng hấp dẫn. Nếu bạn...",muỗng cà phê muối | bột bánh cuốn pha sẵn | đường | dầu ăn | lá cẩm | dừa nạo sợi | đậu xanh | lá dứa | mè trắng | dừa nạo nhuyễn để lấy nước cốt
6,D007,7,4472,0,0 - not relevant,Kem đậu xanh nước cốt dừa bằng máy xay sinh tố dẻo mịn thơm ngon,Món kem,"Vào hè rồi bạn đã nghĩ ra món ăn vặt nào thanh mát, giải nhiệt chưa? Hôm nay, Điện máy XANH sẽ hướng dẫn bạn cách làm kem đậu xanh nước cốt dừa bằng máy xay sinh tố dẻo mịn thơm ngon. Cùng vào bếp thực hiện ngay món ...",bột bắp | sữa tươi không đường | sữa đặc | nước cốt dừa | đậu xanh cà vỏ
7,D008,8,3327,0,0 - not relevant,Bánh bò da lợn mới lạ thơm ngon hấp dẫn đơn giản,Món bánh,"Bánh bò da lợn - một sự kết hợp hoàn hảo giữa 2 món bánh dân dã đem đến một hương vị béo ngọt, thơm ngon đến khó cưỡng. Nếu bạn cũng muốn nếm thử món bánh này thì hãy vào bếp ngay cùng Điện máy XANH nhé!",đường | bột bánh bò | đậu xanh | lá dứa tươi | bột năng | nước cốt dừa | ói men khô có sẵn trong bột bánh bò | bột gạo | nước dừa tươi
8,D009,9,3441,0,0 - not relevant,Bánh ít trần khoai mì nhân đậu xanh thơm ngon dẻo mềm dễ làm,Món bánh,"Chỉ với vài nguyên liệu rẻ tiền từ khoai mì, đậu xanh, bạn đã có thể tạo nên một món ăn vặt cực kỳ thơm ngon, hấp dẫn cho gia đình cùng thưởng thức. Hãy vào bếp ngay cùng Điện máy XANH để học cách làm bánh ít trần kh...",đường | khoai mì | muối | đậu xanh | hạt mè trắng | dừa nạo xay | bột năng | nước cốt dừa | bó lá dứa | nước
9,D010,10,2065,0,0 - not relevant,Cách gói bánh lá dừa Bến Tre đúng chuẩn dẻo thơm chắc tay,Món bánh,"Nếu đã đến miền Tây, chắc hẳn bạn sẽ không xa lạ gì với món bánh lá dừa dẻo mềm, thơm ngon. Món bánh đặc sản Bến Tre này là sự kết hợp hoàn hảo giữa lớp nếp bùi béo hòa quyện cùng nhân chuối đỏ chua ngọt hấp dẫn. Hãy...",đường | nếp | đậu trắng | muối | á lá dừa | chuối xiêm | nước cốt dừa
10,D011,11,2589,0,0 - not relevant,Bánh bèo ngọt nước cốt dừa đơn giản thơm ngon chuẩn vị miền Tây,Món bánh,"Đã bao giờ bạn nếm thử qua món bánh bèo “phiên bản” ngọt chưa? Nếu chưa, hãy tham khảo món bánh bèo ngọt nước cốt dừa dưới đây để đổi vị cho cả nhà nhé. Với chút ngọt thơm, béo ngậy hấp dẫn, đảm bảo nếm thử một lần l...",muỗng cà phê muối | đường | nước lọc | nước cốt dừa loãng nước dão | bột năng | nước cốt dừa | bột gạo | mè rang
11,D012,12,7823,0,0 - not relevant,Xôi nếp than nhân đậu xanh nước cốt dừa thơm béo đơn giản,Món hấp,"Xôi nếp than nhân đậu xanh là một món dân dã thơm ngon khó tả, cách chế biến đơn giản, được rất nhiều người yêu thích. Nhanh nhanh vào bếp cùng Điện máy XANH thực hiện ngay món hấp thơm ngon này nhé!",đậu xanh không vỏ | đường | ói bịch bánh tráng xôi | á hành lá | lá dứa thơm | trái dừa rám | muối | hạt mè trắng | gạo nếp sáp trắng | nếp than | bột năng | nước cốt dừa | đậu phộng
12,D013,13,2580,0,0 - not relevant,"Bánh đậu xanh trái cây đẹp, độc lạ, thơm ngon đơn giản",Món bánh,Bánh đậu xanh trái cây là món ăn vặt rất quen thuộc với tuổi thơ của nhiều người. Món bánh có ngoại hình đẹp mắt và ngộ nghĩnh này hoàn toàn có thể thực hiện tại nhà. Cùng bài viết vào bếp dưới đây tham khảo cách thự...,muỗng cà phê muối | đậu xanh không vỏ | màu thực phẩm | đường thốt nốt | bột rau câu | nước cốt dừa
13,D014,14,3452,0,0 - not relevant,Bánh cam lúc lắc nhân đậu xanh nước cốt dừa giòn ngon ngọt vị,Món bánh,"Bánh cam có lẽ là món bánh đã gắn liền với tuổi thơ nhiều người. Từ chiếc bánh cam truyền thống, Điện máy XANH sẽ cùng bạn vào bếp để học qua cách làm bánh cam lúc lắc nhân đậu xanh nước cốt dừa - một phiên bản biến ...",đậu xanh đã bóc vỏ | đường | dầu ăn | bột nếp | bột baking soda | nước lọc | dừa sợi bào nhỏ | nước cốt dừa | mè rang | tinh bột khoai tây | bột tẻ | ống vani
14,D015,15,3046,0,0 - not relevant,Bánh da lợn hoa đậu biếc béo thơm đơn giản hấp dẫn,Món bánh,"Món bánh da lợn truyền thống đã quá quen thuộc và gắn với tuổi thơ của nhiều thế hệ bởi hương vị ngọt ngào, thơm ngon. Hôm nay, cùng Điện máy XANH vào bếp biến tấu công thức bánh da lợn hoa đậu biếc không những thơm ...",bột gạo | đường | bột năng | nước cốt dừa | bột hoa đậu biếc | đậu xanh cà vỏ
15,D016,16,3987,0,0 - not relevant,"Xôi đậu xanh nước cốt dừa bằng xửng hấp béo thơm, tơi mềm tại nhà",Món chè,"Bạn đang tìm kiếm cách nấu xôi đậu xanh nước cốt dừa bằng xửng hấp dẻo thơm, tơi từng hạt? Đừng lo lắng! Hôm nay, Điện máy XANH sẽ vào bếp bật mí công thức làm món xôi vò nước dừa chuẩn vị, thơm béo, hấp dẫn cho bữa ...",đường | dầu ăn | muối/ lá dứa | gạo nếp | nước cốt dừa | đậu xanh cà vỏ
16,D017,17,3964,0,0 - not relevant,Chè nếp đậu xanh dẻo mềm ngọt bùi ấm lòng ngày đông,Món chè,"Chè nếp đậu xanh ấm nóng, sánh dẻo với đậu xanh mềm bùi, kết hợp cùng nếp dẻo ngọt và với vị béo ngậy của nước cốt dừa tạo nên một món chè thơm ngon, dễ dàng xoa dịu chiếc bụng đói của bạn vào những chiều đông lạnh. ...",đậu xanh hạt | nếp | muối | đường nâu | bột năng | nước cốt dừa
17,D018,18,3627,0,0 - not relevant,Bánh đậu xanh trà xanh thơm ngon dễ làm,Món bánh,"Bánh trà xanh đậu xanh ăn vào mềm tan trong miệng, vừa bùi béo lại đắng nhẹ vị matcha. Món bánh rất thích hợp để bạn mời cả nhà thưởng thức mỗi khi uống trà. Cùng Điện máy XANH vào bếp xem ngay công thức đơn giản này...",đường | dầu ăn | muối | đậu xanh | bột matcha | nước cốt dừa
18,D019,19,3895,0,0 - not relevant,Bánh chuối hấp bằng bột năng chấm nước cốt dừa dẻo thơm nịnh miệng,Món bánh,"Cùng vào bếp với Điện máy XANH và bí quyết làm bánh chuối hấp hằng bột năng dẻo dai, thơm béo. Món bánh này cực kỳ đơn giản, đảm bảo bạn sẽ thành công ngay lần đầu!",ống bột vani | nước cốt dừa từ dừa nạo | đường vàng hoặc dùng đường trắng và thêm bột nghệ | gia vị thông dụng muối/ đường | bột năng | chuối xiêm chuối sứ chín | dầu ăn/ đậu phộng rang
19,D020,20,3211,0,0 - not relevant,Bánh khoai môn ngọt nhân đậu xanh giòn thơm bùi ngậy ăn là mê,Món bánh,"Bánh khoai môn ngọt nhân đậu xanh với lớp vỏ dai mềm đan xen cùng phần nhân bùi ngọt, beo béo, cực kỳ thơm ngon. Món bánh này có công thức thực hiện vô cùng đơn giản, cuối tuần này bạn thử trổ tài để chiêu đãi cả nhà...",đường | bột nếp | khoai môn | nước cốt dừa | bột sắn dây | đậu xanh cà vỏ
20,D021,21,2272,0,0 - not relevant,"Bánh bột báng nhân đậu xanh cốt dừa thơm ngon, béo dẻo dễ làm",Món bánh,"Bánh bột báng nhân đậu xanh cốt dừa dẻo dai, bùi thơm hòa quyện thêm vị beo béo, ngọt ngọt hấp dẫn. Không quá khó để có thể thực hiện thành công món bánh này đâu, hãy thử vào bếp cùng Điện máy XANH vào bếp thực hiện ...",đường phèn | á lá dứa | dầu ăn | dừa bào sợi | muối | đậu xanh | bột báng | đậu phộng rang | bột năng | nước cốt dừa | lá chuối dùng lót bánh để hấp
21,D022,22,4052,0,0 - not relevant,"Chè trôi nước cốt dừa nhân đậu xanh dẻo ngon, dễ làm tại nhà",Món chè,"Chè trôi nước là món chè truyền thống của người Việt Nam tuy nhiên có công thức biến tấu giúp món chè ngày càng đa dạng và có thêm nhiều mùi vị thơm ngon. Hôm nay, Điện máy XANH sẽ mách thêm đến bạn cách nấu chè trôi...",đường | nước dừa khoảng dừa | dừa bào sợi | bột nếp | muối | bột năng hoặc bột sắn dây | nước cốt dừa | đậu xanh cà vỏ
22,D023,23,3279,0,0 - not relevant,Bánh trung thu dẻo lạnh nhân đậu xanh ngũ sắc thơm ngon,Món bánh,"Bánh trung thu dẻo có mùi thơm đặc trưng từ tinh dầu bưởi và màu sắc bắt mắt. Vỏ bánh dẻo mềm, ngọt vừa, nhân bên trong thì có vị bùi bùi beo béo từ đậu xanh. So với bánh nướng thì cách làm bánh dẻo lại cực kỳ đơn gi...",bột bánh dẻo nhân đậu xanh | đậu xanh nhân đậu xanh | dầu ăn cốt bánh | nước cốt chanh phần nước đường | bột bánh dẻo cốt bánh | đường phần nước đường | quả thanh long ruột đỏ phần nước màu | hương nước hoa bưởi cốt ...
23,D024,24,1054,0,0 - not relevant,Bánh da lợn dân gian,Bánh và bánh ngọt,"Món ăn dân gian này rất được phổ biến rộng khắp Việt Nam, vị ngọt của đậu, vị dẻo vừa đủ, vị dai nhẹ nhàng luôn tạo điểm nhấn cho món ăn giản dị này",đậu xanh không vỏ | nước lá dứa | bột năng | nước cốt dừa | bột gạo
24,D025,25,3699,3,3 - highly relevant,Bánh đúc lá lúa - bánh đúc đậu xanh nước cốt dừa mỡ hành thơm béo,Món bánh,"Bánh đúc lá lúa - bánh đúc đậu xanh nước cốt dừa mỡ hành là một món bánh dân dã đậm chất vùng quê Việt Nam. Hôm nay, để thưởng thức lại mùi vị của món bánh quê hương này thì hãy vào bếp cùng Điện máy XANH thực hiện n...",đường | dầu ăn | muối | đậu xanh | tinh chất vani | dầu mè | bột năng | nước cốt dừa | hành lá | bột gạo
25,D026,26,2817,0,0 - not relevant,"Bánh bột dè cốt dừa thơm ngon, béo dẻo dễ làm",Món bánh,"Bánh bột dè là món bánh phổ biến ở các chợ quê An Giang, bên ngoài có vỏ bánh màu vàng bắt mắt kèm nhân đậu xanh ngon ngọt hòa quyện thêm vị beo béo của nước cốt dứa, rất hấp dẫn. Cùng vào bếp bắt tay thực hiện bánh ...",bột dè | đường thốt nốt | đậu xanh | đường cát | nước cốt dừa
26,D027,27,2148,0,0 - not relevant,Bánh ít bột năng nhân đậu xanh giòn sần sật ngon miệng với nồi hấp,Món bánh,"Bạn muốn tự tay làm món bánh ít bột năng dẻo thơm, đẹp mắt cho gia đình hay ngày lễ Tết ? Vào bếp cùng Điện máy XANH, bạn sẽ khám phá cách làm bánh ít nhân đậu xanh ngọt béo, vỏ dẻo giòn cực kỳ đơn giản, thành công 1...",đậu xanh không vỏ | đường | nước cốt lá dứa xay từ lá dứa | cơm dừa non | muỗng cà phê hương lá dứa tùy chọn | bột năng | muối/ dầu ăn
27,D028,28,7804,0,0 - not relevant,Xôi đậu xanh hạt sen nước cốt dừa tại nhà với nồi hấp,Món hấp,Xôi đậu xanh hạt sen nước cốt dừa là một sự kết hợp độc đáo giúp món xôi thêm phần thơm béo và dẻo ngon. Nếu bạn muốn đổi mới công thức nấu xôi đậu xanh thì hãy thử kết hợp thêm với hạt sen và nước cốt dừa nhé. Hãy c...,nếp | muối | hạt sen khô | đậu xanh cà vỏ | dầu dừa hoặc dầu ăn | nước cốt dừa loại đóng hộp
28,D029,29,2533,0,0 - not relevant,Bánh tiêu nhân đậu xanh dừa phồng mềm thơm ngon dễ làm,Món bánh,"Bánh tiêu là món bánh được nhều người ưu thích nhờ mùi vị và kết cấu thơm ngon. Hôm nay, Điện máy XANH sẽ vào bếp hướng dẫn bạn thực hiện bánh tiêu nhân đậu xanh dừa phồng mềm hấp dẫn nhé!",đường | bột dừa | bột mì đa dụng | bột sữa | đậu xanh | nước cốt dừa | men nở loại instant dry yeast | gia vị thông dụng muối/dầu ăn
29,D030,30,3714,0,0 - not relevant,Bánh ít nếp xào nhân dừa đậu xanh dẻo thơm mới lạ đơn giản,Món bánh,"Bánh ít nếp nhân dừa đậu xanh dẻo mềm hòa quyện cùng phần nhân ngọt bùi béo, thơm ngon. Chẳng cần đi đâu xa để mua vì bạn cũng có thể thực hiện món bánh này ngay tại nhà. Cùng Điện máy XANH vào bếp nhé!",á lá chuối ngoài kích thước 25*50cm | dừa nạo | đường | muỗng cà phê muối | nếp | muối hột | á lá chuối trong kích thước 15*30cm | đậu xanh | lá dứa | nước cốt dừa
30,D031,31,2878,0,0 - not relevant,Bánh mochi nhân đậu xanh dừa lá dứa dẻo mịn dễ làm tại nhà,Món bánh,"Bánh mochi có lớp vỏ dai mềm, ngọt mát cùng nhân đậu xanh dừa thơm béo bùi hòa quyện với nhau, các bạn cùng Điện máy XANH vào bếp chế biến món bánh vô cùng thơm ngon này nhé!",sữa tươi | bột nếp | cùi dừa non | lá dứa thơm | bột bắp | bột năng | nước cốt dừa | đậu xanh cà vỏ
31,D032,32,8733,0,0 - not relevant,Bánh tằm nước cốt dừa chay thơm béo vô cùng đơn giản,Món chay,"Bánh tằm nước cốt dừa chay thơm ngon, mới lạ sẽ làm bữa ăn của gia đình thêm hấp dẫn. Hãy cùng vào bếp và chế biến món chay ngon này cho gia đình mình ngay hôm nay nhé!",bánh tằm | đậu phộng rang | chả chay | nước cốt dừa
32,D033,33,3348,0,0 - not relevant,Bánh mochi cốm dẻo thơm lạ miệng tại nhà nhờ máy xay cầm tay,Món bánh,"Nếu bạn yêu thích những món bánh ngọt mềm dẻo, thơm mùi cốm và không quá ngấy thì bánh mochi cốm nhân đậu xanh sẽ là lựa chọn tuyệt vời. Món bánh kết hợp giữa vỏ cốm dẻo dai, nhân đậu xanh bùi ngọt và lớp cơm dừa sấy...",tinh chất lá dứa khoảng hoặc iọt | cơm dừa sấy khô | dầu ăn | cốm tươi hoặc cốm khô | muối | nước cốt dừa dùng làm vỏ bánh và sên nhân | màu thực phẩm vàng có thể bỏ qua | đường vàng | đậu xanh khô loại đã tách vỏ | ...
33,D034,34,1098,0,0 - not relevant,Bánh chuối hấp nước cốt dừa,Món tráng miệng,"Những ngày bình thường cũng có thể tạo nên hương vị cho các thành viên gia đình bạn, nên hãy đừng ngần ngại mà bỏ qua món bánh chuối hấp nước cốt dừa này.\r\nMón ăn dân gian này lại là đặc sản không kém bằng thu hút đấy",chuối chín | vani ống | bột năng | nước cốt dừa | mè rang | đậu phộng
34,D035,35,3878,0,0 - not relevant,Bánh đậu xanh nướng cốt dừa thơm ngon béo mịn đơn giản tại nhà,Món bánh,"Còn gì tuyệt vời hơn khi được nhâm nhi tách trà cùng những miếng bánh đậu xanh nướng thơm nứt mũi. Từng miếng bánh thơm phứt mùi đậu, beo béo từ nước cốt dừa chắc chắn sẽ khiến bạn không tài nào cưỡng nổi. Cùng Điện ...",bột mì | đường | bơ lạt | vani | whipping cream | đậu xanh | sữa đặc | bột năng | nước cốt dừa
35,D036,36,3398,0,0 - not relevant,Bánh quai vạc nhân đậu xanh nướng thơm ngon dễ làm,Món bánh,"Cuối tuần, hãy cùng vào bếp với Điện máy XANH để trổ tài làm món bánh quai vạc nhân đậu xanh ngon tuyệt cho gia đình thưởng thức nhé!",muỗng cà phê muối | đường | dầu ăn | bột mì đa dụng | đậu xanh đã tách vỏ | nước
36,D037,37,2923,0,0 - not relevant,Bánh da lợn thơm bùi vị đậu xanh lá dứa cực ngon,Món bánh,"Bánh da lợn thơm ngon, dân dã chắc chắn sẽ khiến cho cả gia đình bạn phải xao xuyến đó. Dịp cuối tuần thảnh thơi mời bạn cùng vào bếp với Điện máy XANH và làm ngay món bánh siêu hấp dẫn, vừa dẻo dai, vừa thơm béo này...",đậu xanh tách vỏ đậu xanh cà vỏ | đường | dầu ăn | bột nếp | lá dứa | bột năng | nước cốt dừa | bột gạo
37,D038,38,3495,0,0 - not relevant,"Bánh quy nhân đậu xanh miền Tây dẻo mềm, đơn giản tại nhà",Món bánh,"Khác hẳn với bánh quy giòn rụm thường ăn, món bánh quy lá dứa nhân đậu xanh mà Điện máy XANH giới thiệu ngay sau đây lại có mùi vị vô cùng đặc biệt. Từ lớp vỏ dẻo mềm, dai dai đến phần nhân đậu xanh bùi béo, món bánh...",muỗng cà phê muối | đường | á lá dứa | dầu ăn | bột nếp | đậu xanh | khoai tây | dừa non bào sợi | nước cốt dừa
38,D039,39,2142,0,0 - not relevant,Bánh ú gấc dừa nhân đậu xanh độc đáo lạ miệng đơn giản,Món bánh,"Bánh ú gấc dừa nhân đậu xanh có lớp vỏ dẻo mềm, bùi ngọt, thơm nhẹ từ nhân dừa đậu xanh. Món bánh hứa hẹn sẽ khiến cả nhà bạn thích mê ngay từ lần nếm thử đầu tiên. Hãy cùng Điện máy XANH vào bếp thử sức thực hiện nhé!",đường | thịt gấc | muối | đậu xanh | dừa sợi | gạo nếp | nước cốt dừa | lá chuối
39,D040,40,3200,0,0 - not relevant,"Bánh cốm Hà Nội dẻo thơm, đơn giản tại nhà với máy xay và chảo",Món bánh,"Bánh cốm Hà Nội là món quà truyền thống đặc sắc với hương vị ngọt ngào, đậm nét văn hóa thủ đô. Bạn có thể dễ dàng làm bánh cốm dẻo mềm, thơm ngon ngay tại nhà để thưởng thức hoặc làm quà biếu. Cùng Điện máy XANH vào...",đậu xanh đã bóc vỏ | đường | cốm khô | dầu ăn | muối | tinh chất hương cốm hoặc hương lá dứa | dừa tươi bào sợi dừa tươi hoặc dừa rám | nước cốt dừa
40,D041,41,2562,0,0 - not relevant,Bánh tét lá cẩm chay nhân đậu thơm ngon hấp dẫn đón Tết,Món bánh,"Bánh tét lá cẩm đẹp mắt, nếp dẻo thơm, nhân đậu xanh và đậu thận bùi béo, thơm ngon mà lại vô cùng dễ làm. Cùng vào bếp để dịp Tết này trổ tài cho gia đình nhé.",lá cẩm | đậu xanh | gạo nếp | hộp đậu thận | nước cốt dừa | muối/đường | bột khoai tây | dầu dừa
41,D042,42,2843,0,0 - not relevant,"Bánh khoai lang tím nhân đậu xanh chiên giòn bùi ngọt, thơm ngon",Món bánh,"Bánh khoai lang tím dai mềm, bùi ngọt từ đậu xanh, thơm béo vị nước cốt dừa dùng kèm cùng trà ấm, ngon hết chổ chê. Cuối tuần này, hãy vào bếp thực hiện ngay món bánh đơn giản này để mời cả nhà thưởng thức nhé!",đường | khoai lang | dầu ăn | bột nếp | muối | đậu xanh | mè trắng | nước cốt dừa | bột gạo
42,D043,43,4003,0,0 - not relevant,Chè đậu xanh nước cốt dừa thơm ngon cho ngày hè,Món chè,Một ly chè đậu xanh nước cốt dừa ngọt bùi thơm ngon sẽ biến ngày hè oi bức trở nên thanh mát dễ chịu. Cùng Điện máy XANH vào bếp học ngay cách làm món chè đơn giản này ngay tại nhà nhé!,đường/ muối | nước cốt dừa on | á lá dứa | bột bắp | đậu xanh nguyên vỏ hoặc bỏ vỏ tùy sở thích | bột sắn dây | dừa nạo/ dừa khô không có cũng được
43,D044,44,2108,0,0 - not relevant,Bánh nậm nhân đậu xanh thơm ngon đơn giản,Món bánh,Nhắc tới Cố Đô Huế thì chắc chắn sẽ khiến người ta nhớ về món bánh đặc trưng - bánh nậm nhân đậu xanh thơm ngon. Hãy cùng vào bếp với Điện máy XANH giới thiệu tới bạn công thức làm món bánh này nhé!,đường | dầu ăn | nước lá dứa | tinh bột đậu xanh | muối | đậu xanh | nước cốt dừa | nước
44,D045,45,7502,0,0 - not relevant,Xôi vò nước cốt dừa thơm bùi hấp dẫn cho bữa sáng tiện lợi,Món hấp,"Xôi vò nước cốt dừa với hương vị thơm ngon, bùi béo nên được rất nhiều người Việt Nam yêu thích và thưởng thức thường xuyên. Hôm nay, Điện máy XANH sẽ chia sẻ đến bạn cách làm món hấp này vừa đơn giản vừa tiện lợi ch...",dầu ăn | hành tím | đậu xanh | gạo nếp | nước cốt dừa | muối/ đường
45,D046,46,1985,0,0 - not relevant,Bánh tét nước tro nhân đậu xanh ngọt trong dẻo mềm thơm ngon,Món bánh,"Bánh tét nước tro tàu nhân đậu xanh là món bánh không thể thiếu trong dịp Tết Đoan Ngọ hằng năm. Với lớp vỏ nếp dẻo mềm, nhân đậu xanh bùi béo, chắc hẳn sẽ khiến ai nếm thử cũng sẽ tấm tắc khen ngon. Vào bếp cùng Điệ...",nếp | nước tro tàu | muối | đậu xanh | đường vàng | nước cốt dừa | nước dừa tươi
46,D047,47,2422,0,0 - not relevant,Bánh đậu xanh ướt mịn ngọt thơm ngon khó cưỡng,Món bánh,"Bánh đậu xanh ướt mềm thơm, dẻo nhẹ cùng vị ngọt bùi, beo béo rất hấp dẫn, nhâm nhi từng miếng bánh ngon nhấp thêm ngụm trà đắng thì còn gì tuyệt hơn. Cùng Điện máy XANH vào bếp thực hiện ngay món bánh này nhé!",muỗng cà phê muối | đậu xanh nguyên vỏ | bơ lạt hoặc nước cốt dừa | á lá dứa | tinh chất lá dứa | đường vàng

========================================================================================================================
query_id: 485
query_text: Bắp bò hầm bạch quả đậm đà bổ dưỡng
relevance distribution: {0: np.int64(5), 1: np.int64(38), 2: np.int64(5), 3: np.int64(2)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,1418,1,1 - partially related,Gân bò hầm khoai tây cà rốt mềm thơm hấp dẫn đậm đà,Món canh,"Gân bò hầm là một món ăn được rất nhiều người yêu thích. Không chỉ là một món ăn mang lại nhiều lợi ích cho sức khỏe, đây cũng là một món ăn thích hợp trong các bữa tiệc. Hôm nay chúng ta sẽ cùng nhau vào bếp , để họ...",gừng | dầu ăn | hạt nêm/tiêu | khoai tây | nước tương | su hào | cà rốt | gân bò
1,D002,2,6450,1,1 - partially related,"Bò kho dưa cải chua đơn giản, thơm ngon, đậm đà hương vị",Món kho,Bạn là tín đồ của các món ăn hấp dẫn từ bò và đam mê tìm tòi các công thức mới. Điện máy XANH mách bạn cách làm món bò kho dưa cải chua mới lạ thơm ngon lại vô cùng đơn giản tại nhà. Cùng vào bếp với món kho hấp dẫn ...,dưa cải chua | thịt bắp bò | hành tím | dầu điều | gia vị bò kho | cà chua
2,D003,3,6474,1,1 - partially related,"Bắp bò kho gừng thơm ngon, đậm vị dễ làm tại nhà",Món kho,"Các món ăn từ bò luôn được nhiều người yêu thích, nhất là các bé nhỏ vì độ thơm ngon và vô cùng bổ dưỡng. Hôm nay, cùng vào bếp học thêm công thức bắp bò kho gừng cực ngon, hấp dẫn lại đơn giản để nấu cho gia đình th...",gừng | đường | dầu ăn | thịt bắp bò | tiêu | muối | sả | hạt nêm | tỏi
3,D004,4,464,1,1 - partially related,Lẩu bò ớt xiêm xanh,Món ngon ngày lạnh,"Nước lẩu được nấu từ tỏi ớt và nạm, xương bò mang đến vị chua cay hấp dẫn được nhiều người yêu thích, nhất là khi trời se lạnh.",tiêu | hành tây | bún tươi | rau muống | chả cá | ba chỉ bò mỹ | xương bò | nấm mỡ | ớt xiêm xanh | nạm bò | bò viên | tỏi
4,D005,5,3986,0,0 - not relevant,Chè sake bạch quả thơm ngon đơn giản vô cùng bổ dưỡng,Món chè,"Trái sake được chế biến làm nhiều món chè hấp dẫn thơm ngon khác nhau, nếu kết hợp cùng bạch quả thì hương vị chè sẽ như thế nào? Hôm nay chuyên trang Vào bếp của Điện máy XANH sẽ mách bạn công thức món chè sake bạch...",đậu phộng đã rang chín | trái sake | muối | bạch quả | bột báng | đường trắng | nước cốt dừa
5,D006,6,3957,0,0 - not relevant,Cách nấu chè bo bo bạch quả tàu hủ ky bổ dưỡng chuẩn vị người Hoa,Món chè,"Tàu hủ ky không chỉ là một loại nguyên liệu sử dụng trong các món chay, mà nay nó còn được kết hợp với bo bo và bạch quả cho ra một món chè thơm ngon, bổ dưỡng. Hôm nay, hãy cùng vào bếp với Điện máy XANH để thực hiệ...",đường phèn | lá dứa | bạch quả | á tàu hủ ky | hạt bo bo | lòng trắng trứng
6,D007,7,1683,1,1 - partially related,"Đuôi bò hầm củ sen thơm ngon, thanh mát và bổ dưỡng",Món canh,"Những món từ bò luôn có sức hấp dẫn với mọi người vì thịt rất ngon, hấp dẫn đặc biệt là các món bò hầm. Cùng vào bếp với Điện máy XANH ngay để thực hiện món đuôi bò hầm củ sen thơm ngon và cùng thưởng thức với mọi ng...",đường phèn | củ sen | hạt kỷ tử | cà rốt | gia vị thông dụng bột ngọt/ muối/ đường | bắp | đuôi bò khoảng
7,D008,8,8056,1,1 - partially related,Lẩu xương bò ngọt thơm hấp dẫn đơn giản tại nhà,Món lẩu,"Mỗi khi nhắc đến các món ngon từ bò thì điều đầu tiên hiện ra trong ý nghĩ của mọi người ngoài sự bổ dưỡng còn là cảm giác say đắm, muốn được thưởng thức ngay lập tức. Do đó, hôm nay hãy cùng vào bếp với Điện máy XAN...",dầu ăn | hoa hồi | sả | quế chi | xương bò | gia vị bò kho | gân bò
8,D009,9,7529,1,1 - partially related,"Bắp bò hấp gừng thơm ngon, đơn giản tại nhà",Món hấp,"Những món từ bò từ lâu đã luôn là những món không thể thiếu từ những bữa tiệc trọng đại cho đến những bữa cơm gia đình. Hôm nay, chuyên trang Vào bếp của Điện máy XANH sẽ hướng dẫn bạn làm một món hấp từ bò, đó chính...",gừng | gia vị thông dụng muối/ tiêu/ hạt nêm | hành tây | hành tím | sả | bắp bò | ớt
9,D010,10,8275,1,1 - partially related,"Gỏi bắp bò cần tây thơm ngon, giòn ngọt và vô cùng đơn giản",Món gỏi - salad,"Nếu bạn đang muốn đổi vị cho bữa cơm gia đình thay vì các món nhiều dầu mỡ thì gỏi bắp bò cần tây sẽ là một gợi ý cực kỳ lý tưởng vì cực kỳ thơm ngon, hấp dẫn, giòn ngọt, ít dầu mỡ và dễ làm tại nhà. Hôm nay hãy vào ...",gừng | củ hành tây tím có thể thay bằng hành tây thường | hoa hồi | bắp bò | nước mắm | vừng | gia vị thông dụng muối/ đường/ hạt nêm
10,D011,11,4258,1,1 - partially related,Phở bắp bò bằng nồi áp suất thơm ngon đậm đà hương vị,Món nước,"Nếu bạn là một người yêu thích các món ăn từ bò , thì hãy mau mau xắn tay áo lên và bắt tay ngay vào bếp thôi nào. Hôm nay, Điện máy XANH sẽ theo chân bạn vào bếp để hướng dẫn chi tiết cách nấu phở bắp bò bằng nồi áp...",hành lá | giá | bắp bò | gia vị thông dụng đường/ hạt nêm/ bột ngọt | ói gia vị nấu phở bò | sợi phở | rau ăn kèm phở ngò gai/ rau thơm/ húng lủi/ húng quế | củ hành tây | bò viên
11,D012,12,1541,1,1 - partially related,Gà ác hầm đậu đen mềm rục bổ dưỡng bằng nồi cơm điện,Món canh,"Bạn đang tìm kiếm món ăn bồi bổ? Món gà ác hầm đậu đen bổ dưỡng này là ""chân ái"" cho người mới ốm dậy. Vào bếp ngay để chế biến món từ gà thơm ngon với công thức chi tiết nhé!",nấm hương | gà ác | đậu đen
12,D013,13,8564,1,1 - partially related,Thịt bò rim khô chuẩn vị Nghệ An đón mùa Tết đến,Món từ bò,"Thịt bò rim khô là món ăn nổi tiếng ở miền Trung trong ngày Tết, có hương vị gần giống bò khô nhưng thịt mềm, thơm, ăn kèm cùng cơm nóng là chuẩn vị. Cùng vào bếp với Điện máy XANH thực hiện cách làm bò rim chuẩn vị ...",gừng | thịt bắp bò | nước mắm | lá tỏi | đường/ tiêu | tỏi
13,D014,14,8562,1,1 - partially related,Gân bò hầm ngũ vị mềm ngon đậm đà siêu lạ miệng,Món từ bò,Nếu bạn đang loay hoay đi tìm món ăn mới lạ nhưng cũng không kém phần bổ dưỡng để chiêu đãi mọi người thì còn gì phù hợp bằng món gân bò hầm ngũ vị nữa. Ắt hẳn món ăn bổ dưỡng này sẽ khiến ai cũng thích thú không thô...,hành boa rô | bia lon | thịt gân bò | ớt khô | rượu nấu ăn chén ăn cơm | cà rốt | át gừng | giấm dấm | ói gia vị sốt bò hầm ngũ vị | hành lá
14,D015,15,8534,1,1 - partially related,"Nạm bò với gấc mềm thơm, đậm vị đổi món cho cả nhà",Món từ bò,"Nếu bạn là người yêu thích các món ngon từ bò thì chắc chắn bài viết hôm nay là dành cho bạn đấy! Món nạm bò nấu gấc mềm ngon, đậm đà mà Điện máy XANH sắp sửa chia sẻ sẽ khiến bạn ngạc nhiên cho mà xem, cùng vào bếp ...",bột ngũ vị hương | muối | quả gấc | bột canh | tỏi | thịt nạm bò
15,D016,16,6564,1,1 - partially related,"Bò kho mật mía Nghệ An siêu ngon, siêu dễ làm nhâm nhi ngày Tết",Món kho,"Bắp bò kho mật mía Nghệ An với hương vị thơm ngon, đặc biệt sẽ làm cho thực đơn ngày Tết của gia đình bạn thêm phong phú. Hãy cùng vào bếp với Điện máy XANH để thực hiện món ăn hấp dẫn này nhé!",gừng | mật mía | rượu trắng | sả | thanh quế | bắp bò | tiêu xay | tỏi khô | nước mắm | ớt bột | hành khô
16,D017,17,7737,1,1 - partially related,Bắp bò hấp bia mềm ngon cứ ăn là ghiền,Món hấp,"Bắp bò hấp bia là một trong những món hấp ""gây nghiện"", vừa dùng được trong bữa cơm hằng ngày, vừa có thể làm mồi để nhâm nhi. Món ăn là sự kết hợp hoàn hảo giữa bắp bò mềm ngon thấm vị và mùi thơm của bia, sả,... Hã...",gừng | bia | dầu ăn | thịt bắp bò | củ hành tây | ớt xanh hoặc đỏ | gia vị thông dụng muối/ đường/ bột ngọt/ hạt nêm | muỗng canh bột tiêu | sả khô hoặc sả đập dập thái khúc 3cm | tỏi
17,D018,18,7862,0,0 - not relevant,"Óc heo (óc lợn) hầm ngải cứu dinh dưỡng, cho gia đình thưởng thức",Món hấp,"Óc heo vốn dĩ được biết đến là nguyên liệu đầy bổ dưỡng, chuyên dùng để bồi bổ cho cơ thể mỗi khi chúng ta cảm thấy mệt mỏi. Chính vì lẽ đó, hôm nay hãy nhanh tay vào bếp cùng Điện máy XANH trổ tài thực hiện món óc h...",rau ngải cứu | gia vị thông dụng hạt nêm/ muối/ bột ngọt | dầu ăn | óc heo óc lợn
18,D019,19,812,3,3 - highly relevant,Bắp bò hầm bạch quả siêu cấp bổ dưỡng cho cả nhà,Món chính,"Bắp bò hầm bạch quả không chỉ là một món ăn có hương vị hấp dẫn mà còn đem lại giá trị dinh dưỡng tuyệt vời. Chỉ với một vài thao tác đơn giản, bạn hoàn toàn có thể tự tay làm món ăn này ngay tại nhà. Cùng tìm hiểu n...",gừng am | đằng sâm | gia vị: hạt nêm bột năng tương cà muối. phần | khoai môn am | bạch quả | kỷ tử | bắp bò | táo đỏ am | nước dừa tươi
19,D020,20,5896,1,1 - partially related,Thịt bò xào đậu bắp đầy dinh dưỡng ngon khó cưỡng,Món xào,"Món xào đậm đà, thơm ngon cho bữa cơm thêm dinh dưỡng, đủ hương, tròn vị. Hôm nay Điện máy XANH sẽ mách bạn công thức làm thịt bò xào đậu bắp siêu lạ miệng, siêu bắt cơm. Chần chừ gì nữa cùng chúng mình vào bếp ngay ...",đậu bắp | thịt bò | dầu ăn | gia vị thông dụng hạt nêm/ muối/ bột ngọt/ tiêu xay
20,D021,21,8526,1,1 - partially related,"Bắp bò muối đơn giản, thơm ngon ăn không ngán",Món từ bò,"Bắp bò muối là một món khô mắm lạ miệng, thơm ngon, thích hợp để bạn chế biến ăn chơi hay lai rai trò chuyện cùng mọi người. Cùng vào bếp với Điện máy XANH và thực hiện ngay món ăn này thôi nào!",đường | gừng cắt lát | hành tây | sả | bắp bò | nước mắm | tỏi | ớt xanh
21,D022,22,8537,2,2 - relevant,"Bắp bò hầm khoai tây lạ miệng, thơm ngon",Món từ bò,"Hôm nay Điện máy XANH sẽ giới thiệu cho bạn cách làm bắp bò hầm khoai tây thơm ngon lạ miệng. Nếu muốn thử một món từ bò hoàn toàn mới và ngon thì đừng bỏ qua bài viết này nhé, cùng vào bếp thực hiện thôi!",bột cà ri | bắp bò | cà rốt | tương cà | gừng | khoai tây | dầu hào | cà chua | gia vị thông dụng đường/ muối/ hạt nêm/ tiêu | hành tây | dầu điều | nước lọc | vỏ quế | tiêu hạt | hành tím | ớt sừng | bông hồi | sả |...
22,D023,23,5612,1,1 - partially related,"Bắp bò sốt pate chấm muối ớt tắc đơn giản, mới lạ đậm đà",Món xào,"Bắp bò sốt pate là một món xào có vị thơm, ngọt đặc trưng hấp dẫn, đậm đà, cách chế biến lại độc đáo. Nhân ngày rảnh rỗi cùng Điện máy XANH vào bếp thực hiện món ăn hấp dẫn này ngay và luôn nhé!",gừng | tắc | pate gan heo | cải bẹ xanh | hành tím | gia vị dầu ăn/tiêu/đường/ớt bột/nước tương/bột canh | bắp bò | bột năng | á cọng đầu hành | ngò rí
23,D024,24,8572,1,1 - partially related,Cách luộc bắp bò ngon và mềm chỉ với 4 bước ai cũng làm được,Món từ bò,"Bí quyết luộc bắp bò sao cho ngon, để không bị khô sẽ giúp cho món ăn tăng thêm phần hấp dẫn. Vậy hãy dành chút thời gian để vào bếp cùng Điện máy XANH tìm hiểu ngay cách luộc bắp bò ngon và mềm chỉ với 4 bước ra sao...",dầu ăn | muối | hoa hồi | xì dầu | gừng thái lát | bắp bò | chén hành lá thái khúc
24,D025,25,8143,1,1 - partially related,Gỏi trái vả bắp bò siêu phá mồi bàn nhậu tại nhà,Món gỏi - salad,"Những món gỏi trộn luôn rất được ưa chuộng không chỉ trong những bữa tiệc trang trọng mà còn rất phổ biến ở các bữa ăn gia đình, hay thậm chí là trên các bàn nhậu. Hôm nay, chuyên trang Vào bếp của Điện máy XANH sẽ h...",dầu ăn | húng quế | quả vả | ngò gai | át chanh | bắp bò | đậu phộng | át gừng | gia vị thông dụng muối/ đường/ bột ngọt | nước mắm | cà rốt | tỏi | ngò rí
25,D026,26,7579,1,1 - partially related,"Bắp bò luộc mắm đơn giản, ngon mê ly",Món hấp,"Bắp bò luộc mắm, nhắc đến thôi cũng đủ cảm nhận được mùi thơm khó cưỡng rồi. Hôm nay hãy cùng Điện máy XANH vào bếp làm thử ngay món từ bò thơm ngon, khó cưỡng này nhé. Món này mà mang làm mồi nhắm thì bảo đảm ngon q...",thịt bắp bò có thể diềm thăn bò | gừng | sả | hạt nêm | nước mắm
26,D027,27,4772,1,1 - partially related,"Bắp bò nướng tiêu xanh thơm lừng, hấp dẫn, ngon khó cưỡng",Món nướng,"Bắp bò nướng tiêu xanh là một món ăn hấp dẫn, thơm ngon, hứa hẹn sẽ thỏa mãn vị giác của bất kỳ thực khách sành ăn. Cùng Điện máy XANH vào bếp thực hiện ngay món bò này nhé!",tương ớt xí muội | dầu ăn | sốt ướp thịt nướng | trái dứa thơm | bắp bò | dầu hào | tiêu xanh | sa tế tôm
27,D028,28,553,1,1 - partially related,"Món bò kho thơm ngon, đậm đà, ai cũng khen ngon",Món ngon cho cuối tuần,"Đây là món ăn quen thuộc của người miền Nam, gần giống món bò sốt vang của miền Bắc, có thể thưởng thức cùng gia đình vào cuối tuần.",ói gia vị bò kho mua sẵn trong siêu thị nếu không có | bột nêm | gia vị: nước mắm | sốt cà chua mua sẵn chai trong siêu thị | 5- tỏi | gừng nhỏ | khoai tây | thịt nạm bò bắp bò | rượu vang đỏ không có thì dùng rượu g...
28,D029,29,7914,1,1 - partially related,Cách luộc nạm bò ngon mềm màu đẹp chuẩn vị phở bằng bộ nồi inox,Món hấp,"Bạn yêu thích món nạm bò luộc nhưng ngại thịt bị thâm đen, dai cứng? Đừng lo! Vào bếp hôm nay sẽ bật mí cách luộc nạm bò ngon mềm đẹp mắt, chuẩn vị để nấu phở hay ăn kèm mắm gừng. Đảm bảo bạn sẽ có món nạm bò hoàn hảo!",nạm bò | đá viên | gia vị thông dụng muối/ đường/ bột ngọt
29,D030,30,1768,1,1 - partially related,Gân bò hầm tiêu xanh mềm ngon hấp dẫn cay cay bổ dưỡng,Món canh,"Gân bò hầm là món canh ngon giàu dinh dưỡng, nếu được nấu đúng độ thì sẽ mềm giòn và thơm ngon khó cưỡng. Cùng chuyên trang Vào bếp của Điện máy XANH khám phá cách nấu gân bò hầm tiêu xanh ngon bổ chuẩn vị đơn giản t...",dầu ăn | tiêu xanh tươi | gia vị thông dụng đường/ muối/ bột ngọt | chanh | sả | cà rốt | bắp non | tỏi băm | nấm rơm | gân bò
30,D031,31,63,1,1 - partially related,Bắp bò ngâm xì dầu,Món Tết,"Bắp bò ngâm xì dầu là món ăn vừa ngon miệng, đẹp mắt, rất xứng đặt trong mâm cỗ ngày Tết.",gừng | nước trắng | tỏi: bát ăn cơm | hạt tiêu xanh | sả | xì dầu | bắp bò | dấm ăn | đường cát vàng | ớt hiểm cay: tuỳ sở thích
31,D032,32,7313,1,1 - partially related,"Bò cuốn kiểu Đức lạ miệng, thịt mềm sốt đậm đà cực ngon",Món chiên,"Bạn đã từng nghe, đã ăn hay làm thử bò cuốn kiểu Đức ? Nếu bạn chưa nghe, chưa ăn, chưa làm qua món ăn ngon tuyệt này. Vậy sao bạn không thử thực hiện món ăn với sự kết hợp rất độc đáo của dưa chua, thịt bò và thịt h...",thịt bò bít tết thái lát mỏng | dưa chua cắt làm mỗi quả | rau mùi khô | bột bắp | cốc nước ép dưa chua | nước hầm thịt bò | thịt heo xông khói | tỏi
32,D033,33,4441,1,1 - partially related,Phở bò Hà Nội chuẩn vị nước dùng ngọt thanh đơn giản với nồi luộc,Món nước,"Phở bò Hà Nội khác biệt so với phở bò ở các nơi khác đó chính là nhờ vào nước dùng trong vắt, có vị ngọt thanh và hương thơm đặc trưng. Khi ăn sẽ chỉ ăn kèm với hành lá, hành tây và rau mùi. Hôm nay, bạn hãy cùng Điệ...",thanh quế nhỏ | trái thảo | hành tây | gừng nhỏ | hoa hồi | xương ống bò | bắp bò để làm thịt bò chín | xương bò có lẫn thịt | thịt bò loại ngon để làm thịt bò tái
33,D034,34,512,1,1 - partially related,Bắp bò ngâm mắm tỏi,Món ngon cho cuối tuần,Món ăn dễ làm này có thể dùng trong bữa cơm bình thường hay là đồ nhắm khoái khẩu trong tiệc rượu.,đường | nước lọc bát | hạt tiêu xanh hoặc tiêu đen nguyên hạt số lượng tùy sở thích | bắp bò | nước mắm ngon loại bát ăn cơm | ớt | dấm bát | tỏi
34,D035,35,1464,2,2 - relevant,Bắp bò hầm ngũ quả thanh mát cho bữa cơm thêm ngon miệng,Món canh,Phần bắp bò thường ngon nhất trong các phần thịt bò thì bởi độ săn chắc và ăn giòn giòn nhờ có gân bò. Hôm nay nãy cùng Điện máy XANH chế biến món canh bắp bò hầm ngũ quả ngon đơn giản và giàu chất dinh dưỡng với bí ...,bắp bò | nước tương | hạt sen | hoài sơn | táo đỏ | dầu mè | khoai tây | rượu gừng | đường phèn | rượu trắng | củ sen | muối/ bột ngọt | đảng sâm | củ gừng | hành tím băm | củ cải đỏ | đỗ trọng | thục địa | dầu ăn | ...
35,D036,36,8585,1,1 - partially related,Bắp bò ngâm mắm tiêu xanh tại nhà đảm bảo thành công,Món từ bò,"Chào bạn, đã đến lúc Vào bếp ! Món bắp bò ngâm mắm tiêu xanh giòn sần sật, đậm đà sẽ là lựa chọn tuyệt vời cho bữa cơm hay Ngày lễ Tết . Bài viết sẽ hướng dẫn bạn cách làm bò ngâm mắm tiêu xanh chuẩn vị, đảm bảo thàn...",gừng | quế nhỏ | thảo quả | hành tím | hoa hồi | tiêu xanh cọng và hạt | sả | bắp bò | nước đá lạnh | ớt | tỏi | gia vị thông dụng nước mắm ngon/giấm gạo/đường/hạt nêm/bột ngọt/nước lọc
36,D037,37,8554,1,1 - partially related,Bắp bò ngâm chua ngọt đơn giản hấp dẫn cho gia đình,Món từ bò,Các món từ bò luôn nhận được sự yêu thích đặc biệt trong bữa cơm nhiều gia đình nhờ vào hương vị thơm ngon lại giàu chất dinh dưỡng. Thế còn chờ gì mà không cùng Điện máy XANH vào bếp ngay với món bắp bò ngâm chua ng...,đường | bột canh | ớt cắt nhỏ | gừng cắt lát mỏng | tỏi cắt lát mỏng | bắp bò | giấm | muối hạt | nước sôi để nguội | sả đập dập
37,D038,38,8581,2,2 - relevant,"Bắp bò hầm tiêu xanh lạ miệng, đơn giản và đưa cơm",Món từ bò,"Thịt bò hầm là một trong những món thơm ngon từ bò và giàu chất dinh dưỡng. Khi kết hợp thịt bò với tiêu xanh tạo nên một món vừa lạ miệng, vừa bổ dưỡng. Hôm nay, các bạn hãy vào bếp cùng điện máy XANH để thực hiện m...",gừng | lá quế khô | dầu ăn | bột mì rang vàng | hành tây | hành tím | tương cà | khoai tây | bắp bò | giấm | nước tương | bột năng | cà rốt | tiêu xanh | nước dừa tươi | gia vị thông dụng đường/muối/bột ngọt/hạt nêm/...
38,D039,39,8532,1,1 - partially related,Bò bít tết sốt bbq thơm ngon đổi vị cho buổi tối Tết Dương lịch,Món từ bò,"Bò bít tết sốt BBQ với vị mềm ngọt của thịt bò mềm quyện với sốt BBQ đậm đà thơm ngon, chắc chắn sẽ trở thành tâm điểm trên bàn tiệc của bạn vào những Ngày lễ Tết , đặc biệt là dịp Tết Dương lịch sắp đến đấy! Cùng xắ...",muối/ tiêu xay | bơ lạt | sốt ướp thịt nướng | dầu ăn | thịt thăn bò khoảng | tương ớt | nước hầm bò
39,D040,40,9027,1,1 - partially related,Bắp bò ngâm nước tương (xì dầu) hấp dẫn đãi khách ngày Tết,Ăn vặt,"Bắp bò ngâm nước tương (xì dầu) là một món ăn thú vị cho Ngày lễ Tết . Ngoài những món ăn truyền thống phải có, thì còn gì bằng khi có thêm một món ăn ngon cho những dịp gia đình xôm tụ. Cùng vào bếp thực hiện công t...",gừng | tỏi lớn | quả dứa thơm | ớt sừng | sả | bắp bò | đường trắng | nước tương | hạt nêm
40,D041,41,8566,2,2 - relevant,Bắp bò hầm xì dầu (nước tương) bằng nối áp suất thơm ngon hấp dẫn,Món từ bò,Bắp bò hầm xì dầu (nước tương) là một trong những món ăn chiếm được cảm tình của nhiều người. Với cách chế biến khá đơn giản cùng với hương vị thơm ngon thì bạn hoàn toàn có thể chế biến món ăn này ngay tại nhà cho c...,gừng | dầu ăn | xì dầu nước tương | hành tây | đường thốt nốt | muối | hành tím | ớt sừng | đinh hương | hoa hồi | sả | bắp bò | quế | hạt ngò | thảo quả | tiêu hạt
41,D042,42,4228,1,1 - partially related,"Bún bắp bò thơm ngon, dai giòn cho gia đình thưởng thức",Món nước,"Bún bắp bò là món ăn thích hợp nấu trong những ngày bạn muốn đổi khẩu vị cho bữa cơm gia đình hoặc chiêu đãi bạn bè vào dịp cuối tuần. Hãy cùng vào bếp với Điện máy XANH nấu món nước thơm ngon, bổ dưỡng này nhé!",bắp bò | nạm bò | hành/ ngò | mắm ruốc huế | xương ống bò | gia vị thông dụng muối/ bột ngọt/ tiêu hạt/ hạt nêm | ớt bột | đường phèn | rượu trắng | hành tây | bún | củ cải | rau sống | dầu ăn | chả quết bò | hành tí...
42,D043,43,10094,1,1 - partially related,Bắp bò ngâm rau tiến vua giòn ngon sần sật ăn là ghiền,Món khô - mắm,"Nhắc đến các món khô - mắm có thể bảo quản được lâu được làm từ bắp bò thì chắc hẳn nhiều người sẽ nghĩ đến cách ngâm mắm chua ngọt. Sau đây, bạn hãy cùng vào bếp với Điện máy XANH để tìm hiểu ngay công thức làm món ...",gừng | ớt sừng | sả | bắp bò | rau tiến vua | gia vị thông dụng nước mắm/ muối/ đường/ bột ngọt | ớt chỉ thiên | tỏi
43,D044,44,5469,1,1 - partially related,"Bò xào sả nghệ chỉ với 2 bước cực đơn giản, ăn là mê",Món xào,"Nếu bạn đang muốn thưởng thức một món từ bò thật mới mẻ thì bò xào sả nghệ sẽ là một sự lựa chọn tuyệt vời. Hôm nay, Điện máy XANH sẽ hướng dẫn bạn cách làm món xào thơm ngon với 2 bước cực đơn giản này nhé! Vào bếp ...",dầu ăn | bắp bò hoặc thịt bò mềm | bột nghệ | sả | nước mắm | gia vị thông dụng đường/ bột nêm/ muối/ bột ngọt/ tiêu xay
44,D045,45,321,1,1 - partially related,Bắp bò luộc mắm,Món ngon hàng ngày,"Món ăn ngon, dễ làm, rất thích hợp để bạn trổ tài cho bữa nhậu của ông xã hay bữa cơm họp mặt gia đình.",gừng | bắp bò | tương ớt ngọt | nước mắm | sả cây
45,D046,46,8530,3,3 - highly relevant,Bắp bò hầm bạch quả đậm đà bổ dưỡng,Món từ bò,"Bắp bò hầm bạch quả là một món ăn ngon, không những đậm đà hương vị mà còn vô cùng bổ dưỡng. Hãy thử vào bếp làm ngay món bò ngon này cho gia đình có thêm nhiều món ăn hấp dẫn nhé!",gia vị hạt nêm/tương vcaf/bột năng | gừng | đằng sâm | táo đỏ | khoai môn | bạch quả | bắp bò nguyên cái | kỷ tử | nước dừa tươi

========================================================================================================================
query_id: 135
query_text: Cheesecake chanh dây thơm ngon đơn giản không cần lò nướng
relevance distribution: {0: np.int64(36), 1: np.int64(8), 2: np.int64(4), 3: np.int64(2)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,9179,0,0 - not relevant,Kẹo trái cây hương chanh thơm ngon nhanh chóng chỉ với 15 phút,Ăn vặt,"Với nguyên liệu dễ tìm và cách làm đơn giản, nhanh chóng sau đây, bạn có thể tự làm món kẹo dẻo trái cây hương chanh để chiêu đãi cả nhà mình. Cùng vào bếp làm ngay nhé.",nước cốt chanh dây lọc lấy nước và bỏ bã | đường cát để lăn kẹo | nước cốt chanh xanh | đường cát | pectin
1,D002,2,3076,0,0 - not relevant,Bánh nếp chanh dây thơm ngon mềm mịn,Món bánh,"Bánh nếp chanh dây thơm ngon, dẻo mềm, được kết hợp cùng các nguyên liệu tốt cho sức khỏe nên cực kỳ bổ dưỡng. Cách làm món bánh rất đơn giản và nhanh chóng, vậy nên hãy vào bếp ngay cùng Điện máy XANH nhé!",nước cốt chanh dây | đường | bột nếp | nhân đậu xanh | bột bánh dẻo | bột gạo
2,D003,3,9638,0,0 - not relevant,"Trà trái cây nhiệt đới tại nhà đơn giản, hạ nhiệt cho ngày hè",Thức uống,"Trà trái cây nhiệt đới được kết hợp giữa vị trà thơm nhẹ cùng nhiều loại trái cây giòn mát, ngọt thanh đem đến một món thức uống giải khát cực kỳ hiệu quả trong mùa hè oi bức. Cùng Điện máy XANH vào bếp thực hiện nhé!",đường | chanh xanh | cam | chanh dây | lá bạc hà | quả dưa hấu | ói trà olong túi lọc | dứa | táo
3,D004,4,9309,0,0 - not relevant,Mứt chanh dây hình hoa mai chua ngọt dẻo thơm đãi khách dịp Tết,Ngày lễ Tết,"Tết đến xuân về, ai ai cũng muốn chuẩn bị cho một mùa tết thật tuyệt với đầy đủ món ngon. Với món mứt chanh dây vừa quen vừa lạ, từng miếng mứt dẻo dẻo, ngon ngon sẽ khiến ai thưởng thức nó cũng thích thú lắm đấy! Hã...",chanh dây | muối | đường
4,D005,5,9639,0,0 - not relevant,Nước dứa chanh dây mát lạnh ngày hè,Thức uống,"Ngày hè oi bức chắc chắn không thể thiếu những ly nước trái cây nhiệt đới mát lạnh, vừa giúp giải khát lại bổ sung vitamin cho cơ thể. Hôm nay Điện máy XANH vào bếp làm nước dứa chanh dây ngon ngất ngây cho ngày nắng...",dứa thơm | đá viên | chanh dây | đường cát gia giảm theo khẩu vị
5,D006,6,1951,1,1 - partially related,Bánh Gato tiramisu chanh dây thơm ngon khó cưỡng,Món bánh,"Vị chua ngọt thơm lừng của chanh dây quyện với kem phô mai béo ngậy, lại thêm bánh bông lan mềm mịn, tất cả tạo nên món bánh Gato tiramisu chanh dây thơm ngon không thể cưỡng lại. Các bạn vào bếp làm bánh ngay với Đi...",bột mì | muỗng cà phê muối | nước cốt chanh dây | đường xay | dầu ăn | lòng trắng trứng gà | kem sữa tươi | lòng đỏ trứng gà | tinh dầu chanh dây | kem phô mai | đường cát | bột ngô | ruột chanh dây
6,D007,7,8930,0,0 - not relevant,Thạch chanh dây không bị tách lớp giòn dẻo thơm ngon đẹp mắt,Ăn vặt,"Món thạch chanh dây dai giòn sần sật, không những dễ làm mà còn khá hiệu quả trong việc giải nhiệt. Cùng Điện máy XANH tham khảo công thức và vào bếp thực hiện ngay nhé!",đường | rau câu dẻo | dừa sấy khô | nước lọc | chanh dây | sữa tươi có đường có thể dùng sữa chua
7,D008,8,3563,1,1 - partially related,Bánh quy chanh leo thơm ngon giòn rụm không cần lò nướng,Món bánh,"Bánh quy chanh leo có độ giòn vừa phải, mềm tan ngay trong miệng, bùi béo, chua ngọt và cực kỳ thơm ngon. Cách làm món bánh khá đơn giản vì chẳng cần dùng đến lò nướng hay máy đánh trứng. Hãy vào bếp ngay cùng Điện m...",nước cốt chanh | bột mì số | bơ | vỏ chanh bào | lòng đỏ trứng gà | đường bột | chanh dây cô đặc | trứng gà
8,D009,9,4482,0,0 - not relevant,"Kem chanh dây (chanh leo) chua ngọt, mịn dẻo cực ngon tại nhà",Món kem,"Kem chanh dây (chanh leo) là món kem ưa thích của nhiều người trong những ngày nắng. Món kem này có vị chua ngọt kèm theo một chút vị béo từ kem sữa tươi, làm cho nhiều người mê mẩn. Hôm nay, Điện máy XANH sẽ hướng d...",đường | chanh leo | sữa đặc | bột gelatin | kem sữa tươi whipping cream
9,D010,10,664,0,0 - not relevant,Rau câu chanh dây,"Món tráng miệng, giải khát","Từ quả chanh dây với mùi thơm quyến rũ và vị chua thanh, chúng ta có thể chế biến được nhiều món ngon, trong đó, rau câu chanh dây rất lý tưởng trong dịp hè này.",chanh dây | đường | bột rau câu
10,D011,11,9154,1,1 - partially related,Panna cotta sữa chua thạch chanh dây thơm ngon hấp dẫn ai cũng mê,Ăn vặt,"Panna cotta là một món tráng miệng nổi tiếng trên khắp thế giới đến từ vùng Piedmont, miền Bắc nước Ý. Hôm nay, Điện máy XANH sẽ cùng bạn vào bếp để thử thách với món panna cotta sữa chua thạch chanh dây thơm ngon hấ...",đường | sữa chua không đường | sữa tươi không đường | nước lọc | gelatin bột | siro chanh dây | ống vani
11,D012,12,9553,0,0 - not relevant,"Trà chanh giã tay mát lành, thơm ngon, hot trend một thời",Thức uống,Trà chanh giã tay là một món thức uống vừa lạ vừa quen với sự kết hợp giữa chanh tươi và nước trà. Món thức uống này đã từng là hot trend trong thời gian dài và trở thành món đồ uống yêu thích của nhiều người. Hôm na...,trà hoa nhài | nước đá viên | chanh tươi quảng đông | nước đường
12,D013,13,8384,0,0 - not relevant,Hướng dẫn 2 cách làm món gỏi nấm chanh dây có thể ăn chay hoặc ăn mặn,Món gỏi - salad,Nấm là một món ăn quen thuộc bới chúng được chế biến thành các món khác nhau vì hàm lượng dinh dưỡng trong nấm khá cao. Món gỏi nấm chanh dây cũng là một trong những món ăn phổ biến vì hương vị chua ngọt vừa phải của...,đường | tàu hủ | nấm đùi gà | hành tây bào | nước mắm | củ cà rốt bào sợi | nước chanh dây cả hạt
13,D014,14,2436,2,2 - relevant,Bánh mousse xoài chanh dây ngon ngất ngây không cần lò nướng,Món bánh,"Tong mùa hè oi ả như thế này thưởng thức những món bánh mát lạnh thì còn gì tuyệt vời hơn. Nhân dịp đang trong mùa xoài, Điện máy XANH vào bếp làm bánh mousse xoài chanh dây không cần lò nướng cực kỳ thơm ngon!",gelatine | đường | bơ lạt | whipping cream | chanh dây | xoài chín | bánh oreo
14,D015,15,9440,0,0 - not relevant,Sữa chua uống trái cây tươi cực dễ,Thức uống,"Sữa chua vốn đã rất tốt cho sức khỏe, làn da và vóc dáng. Dưới đây Điện máy XANH sẽ mách bạn cách làm sữa chua uống kết hợp với hương vị của các loại trái cây tươi, không chỉ là thức uống bổ dưỡng mà còn vô cùng hấp ...",dâu tây hoặc có thể thay bằng phúc bồn tử | hộp sữa đặc | hộp sữa chua | sữa tươi không đường | kiwi | chanh dây | đường tùy theo khẩu vị | đào
15,D016,16,9379,0,0 - not relevant,Soda chanh muối giải nhiệt mùa hè đơn giản tại nhà,Thức uống,"Cách pha soda chanh muối tươi mát giúp thanh lọc cơ thể, giải nhiệt mùa hè, dễ làm tại nhà làm. Cùng vào bếp với Điện máy XANH làm thử ngay thức uống này nhé!",chanh muối | đường | đá | quả chanh | soda chanh
16,D017,17,9660,0,0 - not relevant,Mojito chanh dây - passion mojito mát lạnh giải nhiệt mùa nóng,Thức uống,"Giải tỏa cơn nóng oi bức của hè cùng món mojito chanh dây chua ngọt, the mát chỉ với công thức thực hiện siêu nhanh và đơn giản. Hãy vào bếp cùng Điện máy XANH xem ngay công thức món thức uống này nhé!",nước cốt chanh | quả chanh cắt lát | siro đường | chanh dây | đá viên | á lá bạc hà | soda
17,D018,18,8455,0,0 - not relevant,"Cánh gà, đùi gà sốt chanh dây chua ngọt hấp dẫn ăn là ngất ngây",Món từ gà,"Một chút chua của chanh dây, cay cay của tương ớt, giòn giòn của của đậu sắn và đậu que cùng với độ dai thơm ngon của thịt gà sẽ là món ăn tuyệt vời cho những ngày thời tiết ẩm ương, hay bữa cơm cuối tuần của gia đìn...",cánh gà | đậu que | chanh dây | củ sắn
18,D019,19,3254,1,1 - partially related,Bánh quy cookies chanh dây Tây Ban Nha thơm ngon giòn rụm,Món bánh,"Không cần phải ra tiệm để mua bánh quy nữa, bạn có thể vào bếp làm món bánh quy chanh dây độc đáo ngay tại nhà nhờ hướng dẫn của Điện máy XANH.",bột mì | bơ lạt | đường bột | chanh dây | trứng gà
19,D020,20,4485,0,0 - not relevant,Kem chanh muối mát lạnh ngon khó cưỡng,Món kem,"Bạn là tín đồ thích các món kem mát lạnh! Hôm nay, Điện máy XANH sẽ hướng dẫn bạn cách làm kem chanh muối mát lạnh ngon khó cưỡng. Cùng vào bếp để trổ tài món ăn chiêu đãi gia đình bạn nhé!",chanh muối | đường | tắc | ói sữa tươi không đường | nước sôi | sữa đặc on
20,D021,21,9469,0,0 - not relevant,Hướng dẫn cách làm trà mãng cầu hot trend giải nhiệt cho mùa nắng nóng,Thức uống,"Trà mãng cầu đang là thức uống hot trend hiện nay bởi hương vị thơm ngon và thanh mát giải khát cho mùa nóng ơi bức. Hôm nay, cùng vào bếp với Điện máy XANH để làm món trà mãng cầu ngay tại nhà ngay nhé!",trà túi lọc | chanh dây | đường | mãng cầu gai
21,D022,22,9300,0,0 - not relevant,"Mứt vỏ chanh dây (chanh leo) dẻo ngọt, lạ miệng cho ngày Tết",Ngày lễ Tết,"Mứt vỏ chanh dây là món rất quen thuộc với chúng ta trong các ngày lễ tết , 1 món ăn rất ngọt ngào và rất thơm. Nay chuyên trang Vào bếp của Điện máy XANH sẽ hướng dẫn các bước đơn giản để thực hiện món mứt này nhé!",chanh dây | muối | đường
22,D023,23,9788,0,0 - not relevant,Hướng dẫn chi tiết cách làm soda mùa hè giải nhiệt thơm ngon,Thức uống,"Mùa hè ngoài những món ăn thanh mát thì không thể thiếu những loại thức uống. Nếu bạn đã quá quen thuộc với những loại nước ngọt... sao không làm thử vào bếp cùng Điện máy XANH thực hiện món soda trái cây lạ miệng, h...",đường | dâu tây | chanh dây chanh leo | kiwi | lá bạc hà hoặc húng lủi trang trí | chanh tươi | đá viên | soda
23,D024,24,8986,0,0 - not relevant,"Sữa chua trái cây tươi ngon tuyệt vời, ăn là ghiền mãi thôi",Ăn vặt,"Sữa chua là một món tráng miệng quá quen thuộc đối với mọi người rồi phải không nào. Hôm nay, chuyên trang Vào bếp của Điện máy XANH sẽ hướng dẫn bạn cách làm món sữa chua trái cây tươi cực lạ, cực hấp dẫn. Hãy cùng ...",đường | dâu tây | sữa đặc | kiwi | chanh dây | sữa tươi có đường | sữa chua
24,D025,25,9624,0,0 - not relevant,Trà chanh kim quất giải khát tại gia bằng bình thủy điện,Thức uống,"Trà chanh kim quất chua ngọt, thơm lừng là thức uống giải nhiệt mùa hè tuyệt vời. Cùng vào bếp pha chế món trà chanh dây kim quất thanh nhiệt, giàu Vitamin C này để cả nhà cùng thưởng thức và detox cơ thể mỗi ngày!",nước sôi để pha trà | trà đen phúc long | quả tắc hay còn gọi là kim quất tươi | muối | đường đường cát vàng hoặc đường phèn | chanh dây
25,D026,26,4476,0,0 - not relevant,Kem xoài chanh dây chua ngọt thanh mát,Món kem,"Kem là món khoái khẩu của phái nữ, tự tay làm những viên kem thơm ngon thì còn gì bằng. Hôm nay, Điện máy XANH sẽ mách bạn cách làm món kem xoài chanh dây siêu ngon, cực dễ. Cùng vào bếp khám phá nhé!",gelatine | nước cốt chanh dây | đường | whipping cream | sữa đặc | chanh dây | quả xoài chín
26,D027,27,2268,3,3 - highly relevant,Cheesecake chanh dây thơm ngon đơn giản không cần lò nướng,Món bánh,"Cheesecake chanh dây thơm ngon, mềm mịn với bánh thơm thơm béo béo, chanh dây chua nhẹ thật hấp dẫn đúng không nào? Hãy vào bếp thực hiện ngay món bánh ngon này cho gia đình mình nhé!",muỗng cà phê chiết xuất vani | gelatin á | sữa chua nguyên chất | kem phô mai cream cheese | đường bột | bơ lạt làm tan chảy | chanh dây | kem whipping | siro ngô | bánh quy nghiền nát
27,D028,28,2619,1,1 - partially related,Bánh Flan caramen chanh leo mềm mịn không bị rỗ,Món bánh,"Bánh flan mềm mịn, thơm béo nay được kết hợp cùng vị chua nhẹ từ chanh dây, vừa lạ miệng lại vô cùng thơm ngon. Đây sẽ là một gợi ý hay để bạn thay đổi thực đơn món tráng miệng cho gia đình mình đấy. Vào bếp cùng Điệ...",sữa tươi | đường | nước cốt chanh | sữa đặc | chanh dây | nước | trứng gà
28,D029,29,3086,2,2 - relevant,Cheesecake biển xanh - Cheesecake ocean ngon không cần lò nướng,Món bánh,"Bánh cheesecake biển xanh - Cheesecake ocean được tạo hình đẹp mắt, hương vị vô cùng thơm ngon, bổ dưỡng, cách làm món bánh này cũng rất đơn giản, vào bếp cùng Điện máy XANH thực hiện ngay nhé!",cream cheese kem phô mai | đường | dừa vụn khô | hoa đậu biếc khô | nước chanh dây pha từ chanh dây hoặc nước cam | bơ lạt | kem tươi whipping cream | socola trắng | gelatin | màu thực phẩm màu đỏ | bánh quy bánh quy...
29,D030,30,9764,0,0 - not relevant,Trà chanh dây macchiato chua chua ngọt ngọt giải nhiệt mùa hè,Thức uống,"Trà chanh dây macchiato là một loại đồ uống đặc biệt được tạo nên bởi sự hòa quyện hoàn hảo giữa độ chua, ngọt, béo và thơm vô cùng độc đáo, mới lạ. Hôm nay, cùng Điện máy XANH vào bếp và chinh phục vị giác của gia đ...",muối thái | kem béo thực vật heavy cream | nước cốt hồng trà | nước đường phèn | bột nền vanilla | đá viên | syrup chanh dây | chanh dây tươi | topping cream | sốt caramel
30,D031,31,7452,0,0 - not relevant,Sườn sốt chanh dây chua ngọt độc đáo cực hấp dẫn,Món chiên,"Món sườn sốt chanh dây với sườn mềm, thấm đẫm nước sốt sóng sánh, thơm nức vị chanh dây khiến cả nhà không thể chối từ. Cách chế biến món chiên này khá đơn giản, chỉ cần bỏ ra chút thời gian là bạn đã có ngay món ăn ...",dầu ăn | chanh dây | gia vị thông dụng muối/ đường/ bột ngọt/ hạt nêm/ tiêu | tương ớt | dầu hào | hành lá | sườn non
31,D032,32,8471,0,0 - not relevant,Ức gà sốt chanh dây chua ngọt hấp dẫn thơm ngon khó cưỡng,Món từ gà,"Ức gà sốt chanh dây là một món ăn lạ miệng được nhiều tín đồ món kho yêu thích. Vậy các tín đồ yêu bếp ơi, cùng Vào Bếp tham khảo cách làm ức gà sốt với chanh dây ngon nức mũi này tại bài viết dưới đây nào.",dầu ăn | chanh dây | gia vị thông dụng đường/ muối/ tiêu xay | nước mắm | ức gà | bột chiên giòn khô
32,D033,33,9630,0,0 - not relevant,Sinh tố chanh dây - chanh leo chua ngọt thanh mát siêu giải nhiệt,Thức uống,"Chanh dây - chanh leo rất được ưa chuộng vào những ngày nắng nóng vì có thể chế biến được các loại thức uống vừa thanh mát, vừa nhiều vitamin từ loại quả này. Hôm nay Điện máy XANH sẽ gợi ý cho các bạn cách làm sinh ...",đường | sữa đặc | chanh dây | đá viên | sữa tươi có đường
33,D034,34,8926,0,0 - not relevant,Mứt dừa viên cực lạ đãi khách ngày Tết dễ làm tại nhà,Ăn vặt,"Mứt dừa không còn quá xa lạ với chúng ta trong dịp Tết . Tuy nhiên, để món mứt thêm mới lạ và hấp dẫn hơn, thay vì mứt dừa sợi như truyền thống, sao bạn không vào bếp làm thử làm mứt dừa viên vừa đẹp, vừa ngon để đãi...",đường | lá dứa | sữa tươi không đường | chanh dây chanh leo | cùi dừa cái dừa
34,D035,35,876,2,2 - relevant,Bánh mouse chanh dây,Món tráng miệng,"Bánh mouse chanh dây thanh mát với vị chua chua, ngọt ngọt và mềm mịn sẽ là món ăn rất đáng để bạn làm cho gia đình mình thưởng thức. Dịp cuối tuần, hãy thử làm món bánh Âu này với phương pháp đơn giản dưới đây, bạn ...",nước cốt chanh dây | hạt chanh dây | bột gelatine | chanh dây | kem tươi
35,D036,36,9706,0,0 - not relevant,Soda Blue Sky đẹp mắt cực mát lạnh,Thức uống,"Soda trái cây là loại thức uống mới lạ nhưng lại cực kì hấp dẫn, tươi mát, thích hợp cho những ngày hè nóng bức. Hôm nay, Điện máy XANH cùng vào bếp với bạn để khám phá cách làm soda Blue Sky tại nhà nhé!",syrup blue curacao | chanh dây chanh leo | chanh | đá viên | soda trắng hoặc 7up
36,D037,37,9182,0,0 - not relevant,Hạt đác rim chanh dây giải nhiệt mùa hè ngon miệng đơn giản,Ăn vặt,"Một trong những món ăn vặt nổi tiếng của thành phố biển Nha Trang là hạt đác - loại hạt ngọt mát, bổ dưỡng, rất thích hợp để giải nhiệt trong những ngày hè nóng nực. Hôm nay, hãy cùng vào bếp với Điện máy XANH nghiên...",đác trắng | đường trắng | chanh dây tính riêng phần ruột
37,D038,38,9935,0,0 - not relevant,"Kem túi hoa quả sữa chua mát lạnh, thơm ngon giải nhiệt cực thích",Món tráng miệng,"Giải nhiệt hiệu quả với món kem túi hoa quả mềm dẻo, mát lạnh, có mùi vị thơm béo, chua ngọt và cực kỳ tốt cho sức khỏe. Cùng Điện máy XANH vào bếp xem ngay công thức làm món tráng miệng hấp dẫn này nhé!",đường | sữa chua ít đường | dâu tây | sữa đặc | kiwi | chanh dây | sữa tươi có đường | nước ấm độ c
38,D039,39,7399,0,0 - not relevant,"Tôm sốt chanh dây giòn rụm, ngọt ngon ai cũng mê",Món chiên,"Tôm sốt chanh dây cực kỳ thơm ngon, lạ miệng sẽ là món chiên hấp dẫn giúp làm mới thực đơn cho bữa cơm của gia đình bạn. Với hương vị đậm đà cùng cách làm đơn giản, chần chờ gì nữa mà không cùng Điện máy XANH vào bếp...",bột bắp | ói bột chiên giòn | chanh dây | trứng gà | đường/ bột nêm | tôm
39,D040,40,2269,1,1 - partially related,"Bánh flan đậu hũ non chanh dây caramel mềm mịn, ngọt ngào",Món bánh,"Bánh flan được làm với nguyên liệu kết hợp thêm đậu hũ sẽ mang đến hương vị mới lạ và vô cùng thơm ngon. Bài viết vào bếp dưới đây sẽ hướng dẫn đến bạn bánh flan đậu hũ non chanh dây caramel mềm mịn, ngọt ngào.",sữa tươi | vani | đậu hũ non | sữa đặc | chanh dây | đường trắng | trứng gà
40,D041,41,9168,0,0 - not relevant,Cách làm kẹo dẻo chanh dây dai dẻo thơm ngon dễ làm,Ăn vặt,"Bạn đang tìm kiếm một món ăn vặt dai dẻo, an toàn, lại dễ thực hiện trong thời gian ngắn? Hãy cùng vào bếp với Điện máy XANH thử thực hiện món kẹ̣o dẻo chanh dây nhé!",đường | chanh dây chanh leo | nước lọc | bột gelatin
41,D042,42,657,0,0 - not relevant,"Sinh tố chuối, chanh dây","Món tráng miệng, giải khát","Không chỉ là loại trái cây vừa ngon, vừa bổ dưỡng lại rẻ tiền, bạn còn có thể biến chuối thành một món sinh tố rất ngon nữa.",nước cốt chanh dây | đá bào hay đá đập nhuyễn | dù | hũ yaourt | chuối chín chuối tiêu | chuối già | sirô bạc hà | sơ ri | át chanh | kem vani
42,D043,43,2114,2,2 - relevant,Bánh mousse chanh leo dừa thơm ngon béo ngậy không cần lò nướng,Món bánh,"Mousse hương vị chanh leo (chanh dây) và dừa chắn chắn là món bánh gây nghiện với bất kể ai với vị béo của dừa và vị chua thanh của chanh leo, cùng vào bếp với Điện máy XANH trổ tài làm món bánh Mousse chanh leo dừa ...",đường | dừa vụn khô | gelatin dạng lá | muối | bột mì đa dụng | sữa tươi không đường | bột cốt dừa | chanh dây | nước cốt dừa | kem sữa tươi whipping cream | trứng gà
43,D044,44,9711,0,0 - not relevant,Trà đào chanh dây giải nhiệt chuẩn vị bằng bình đun siêu tốc,Thức uống,"Mùa hè nắng nóng, còn gì tuyệt vời hơn một ly trà đào chanh dây mát lạnh giải nhiệt? Hôm nay, hãy cùng vào bếp thực hiện món thức uống này với công thức cực kỳ đơn giản mà vẫn đảm bảo hương vị hấp dẫn.",tắc | đá bi | đào ngâm | ói trà đào túi lọc cozy | syrup đường | chanh dây | hồng trà | syrup đào
44,D045,45,9471,0,0 - not relevant,Soda Deep Blue Sea biển xanh sâu thẩm mát lạnh đẹp mắt,Thức uống,"Không đơn thuần là một loại nước thơm ngon, soda Deep Blue Sea còn mang đến cho bạn hương vị biển khơi mát lạnh. Cùng vào bếp thực hiện ngay thức uống ngon lành đẹp mắt này bạn nhé!",lá bạc hà hoặc húng lũi | trái chanh dây | syrup blue curacao | sữa tươi không đường | syrup chanh dây | soda
45,D046,46,2696,3,3 - highly relevant,Bánh cheesecake chanh dây phô mai không cần lò nướng siêu đơn giản,Món bánh,Bánh cheesecake chanh dây phô mai mát lạnh là sự kết hợp hoàn hảo vị béo của nhân kem phô mai hòa cùng hương thơm và vị chua thanh từ chanh dây sẽ làm các tín đồ bánh ngọt không khỏi mê mẩn. Chẳng cần đi đâu xa tìm m...,đường | cream cheese | bơ lạt | whipping cream | chanh dây | bột gelatin | bánh oreo
46,D047,47,3804,1,1 - partially related,Panna cotta chanh dây (chanh leo) mềm béo chua nhẹ cực đơn giản,Món bánh,"Panna cotta là một món bánh tráng miệng nổi tiếng có nguồn gốc từ nước Ý xinh đẹp. Hôm nay, Điện máy XANH sẽ cùng bạn vào bếp để thực hiện panna cotta chanh dây mềm béo, chua nhẹ thanh mát vừa đơn giản vừa đẹp mắt để...",gelatin | mật ong | chanh dây | sữa tươi không đường
47,D048,48,9550,0,0 - not relevant,Trà măng cụt chanh dây uống là ghiền bằng bình siêu tốc hiện đại,Thức uống,"Hè đến, còn gì tuyệt vời hơn khi được thưởng thức một ly trà măng cụt chanh dây thơm lừng, chua ngọt và cực kỳ giải nhiệt? Hôm nay, hãy cùng vào bếp khám phá cách làm trà măng cụt chanh dây đơn giản tại nhà. Bài viết...",sirô măng cụt | đường | măng cụt tươi đã tách vỏ lấy phần thịt | nước sôi nhiệt độ khoảng 80°c để pha trà | muối | chanh dây tươi nước cốt | trà xanh hoa nhài | đá viên | đường vàng
48,D049,49,2893,1,1 - partially related,Muffin chanh leo không cần lò nướng thơm ngon khó cưỡng,Món bánh,Bánh muffin chanh leo không chỉ mang đến hương vị thơm ngon mà còn rất dễ thực hiện. Bài viết dưới đây sẽ cùng bạn vào bếp với hướng dẫn cách làm món bánh muffin chanh leo không cần lò nướng hấp dẫn khó cưỡng.,bột mì | đường | bơ lạt | muỗng cà phê bột cream of tartar | chanh dây | trứng gà | bột nở baking powder

========================================================================================================================
query_id: 151
query_text: Canh cá diêu hồng nấu ngót thanh ngọt thơm ngon đơn giản tại nhà
relevance distribution: {0: np.int64(10), 1: np.int64(22), 2: np.int64(17), 3: np.int64(1)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,5141,1,1 - partially related,Cháo cá lóc rau ngót cho bé thơm ngon bổ dưỡng cực dễ làm,Món cháo,"Cháo cá lóc rau ngót là một món cháo vừa thơm ngon lại vừa bổ dưỡng rất phù hợp cho các bé ăn dặm. Món này mang mùi vị dễ ăn mà cách làm vô cùng đơn giản, các bà mẹ nội trợ có thể thử nấu cho bé ăn đổi vị. Vào bếp cù...",muỗng cà phê nước mắm | dầu ăn | gừng cắt lát | rau ngót | muối | cháo trắng loại chén ăn cơm | át cá lóc
1,D002,2,6068,1,1 - partially related,Cá diêu hồng om dưa thơm ngon hấp dẫn dễ làm cho bữa cơm,Món kho,Cá diêu hồng là thực phẩm quen thuộc trong bữa cơm gia đình Việt bởi nó rất dễ ăn lại dễ chế biến. Hôm nay cùng Điện máy XANH vào bếp học cách làm cá diêu hồng om dưa để tăng sự phong phú cho thực đơn gia đình bạn nhé!,dầu ăn | dưa cải chua | hành tím | thịt ba chỉ | ớt chuông | nước mắm | cá diêu hồng khoảng | cà rốt | hành lá | gia vị thông dụng đường/ hạt nêm/ bột ngọt | cà chua | tỏi
2,D003,3,7891,1,1 - partially related,Cá diêu hồng hấp bầu thơm ngon ngọt mát đơn giản,Món hấp,"Cá diêu hồng hấp bầu là một món hấp cực kì dễ làm, lại ngon ngọt, thích hợp cho dịp tụ họp cuối tuần cho cả nhà. Cùng vào bếp học làm để chiêu đãi các thành viên món ăn hấp dẫn này thôi!",gừng | hành tím | rau ngò | cá diêu hồng | tương ớt | dầu hào | nước mắm | bầu | hành lá | ớt | gia vị thông dụng đường/hạt nêm/tiêu xay
3,D004,4,1610,3,3 - highly relevant,Canh cá diêu hồng nấu ngót thanh ngọt thơm ngon đơn giản tại nhà,Món canh,"Bạn có thể làm nhiều món ngon với cá diêu hồng như kho, chiên, nấu lẩu, ... và nấu canh cũng rất hấp dẫn. Các bạn hãy vào bếp cùng Điện máy XANH làm canh cá diêu hồng nấu ngót vô cùng đơn giản mà ngon mê ly nhé!",rau cần tàu cần tây loại nhỏ | dầu ăn | hành tím/ tỏi băm | chanh | cá diêu hồng | nước mắm | hành lá | cà chua | muối/ đường
4,D005,5,7474,1,1 - partially related,"Món cá diêu hồng hấp xì dầu thơm ngon, chuẩn vị",Món hấp,"Cá diêu hồng có thể chế biến với nhiều cách khác nhau để tạo nên nhiều món ăn hấp dẫn. Bài viết dưới đây sẽ cùng bạn vào bếp với cách làm món cá diêu hồng hấp xì dầu thơm ngon, chuẩn vị. Cùng tham khảo để thực hiện m...",gừng | đường | dầu ăn | hành tím | gừng băm | ớt sừng | dầu mè | cá diêu hồng | nước tương | hành lá | tỏi băm
5,D006,6,165,0,0 - not relevant,Canh cá Quỳnh Côi chuẩn vị đặc sản Thái Bình,Món ngon hàng ngày,"Một bát canh cá dân dã, trọn hương - sắc - vị với thịt cá dai giòn, nước dùng thanh, trứng cá vàng ươm, rau xanh, bánh đa trắng... tựa bức họa đồng quê hấp dẫn. Đây là món ăn nổi tiếng Thái Bình.",hạt tiêu | dầu ăn | cải cúc... tùy mùa nào thức nấy | bó rau cần hoặc rau ngót | hành tím | muối | bó hành hoa | cá rô đồng | bánh đa quỳnh côi sợi mỏng mịn | khi nấu vẫn dữ được độ dai do làm từ gạo chiêm mùa trước ...
6,D007,7,1563,0,0 - not relevant,Cá chình nấu canh chua nhìn thôi đã thèm bằng nồi nhôm chống dính,Món canh,Canh chua cá chình là món canh đặc sản nổi tiếng ở miền Tây. Cá chình nấu canh chua có hương vị thanh mát và ngọt tự nhiên. Vào bếp làm ngay món ăn bổ dưỡng này để xua tan cái nắng ngày hè nhé!,cá chình | khế chua | trái dứa | rau nấu canh chua quế/ngỗ/dọc mùng/ngò tàu/giá đỗ | lá giang | gia vị muối/đường/bột ngọt/nước măm | cà chua
7,D008,8,1713,2,2 - relevant,Canh cá chét (cá nhụ) nấu ngót ngon miệng dễ làm cho bữa cơm,Món canh,"Với thịt chắc, thơm ngọt, cá chét (cá nhụ) là một trong những loại cá thơm ngon được rất nhiều người ưa chuộng. Hôm nay, hãy cùng vào bếp với Điện máy XANH và thử tài thực hiện ngay một món canh với cá chét mang tên ...",cà chua | cải trắng | cá chét cá nhụ | cần tàu | hành lá | ớt hiểm | gia vị thông dụng muối/đường/bột ngọt
8,D009,9,1764,0,0 - not relevant,"Cá nấu dưa chua miền Bắc đơn giản, nhanh gọn cùng nồi inox 20cm",Món canh,"Món canh cá nấu dưa chua là một trong những món ăn dân dã, đậm đà hương vị miền Bắc, mang đến sự thanh mát và bổ dưỡng cho bữa cơm gia đình. Hôm nay, Điện máy XANH sẽ cùng bạn vào bếp khám phá cách chế biến món canh ...",gia vị thông dụng muối/ nước mắm/ hạt nêm/ đường/ hạt tiêu | dầu ăn | cá diêu hồng khoảng khứa | hành lá/thì là | hành khô hành tím | dưa chua | thịt lợn | ớt | cà chua
9,D010,10,382,2,2 - relevant,Canh chua đầu cá diêu hồng nấu đậu rồng,Món ngon hàng ngày,"Canh chua đầu cá diêu hồng nấu đậu rồng vị chua ngọt thanh mát, thịt cá tươi dai kèm đậu rồng giòn giòn lạ miệng.",1-2 đầu cá diêu hồng | ngò gai | 5-10 cọng đậu rồng | hành | tỏi băm | cà chua
10,D011,11,1693,2,2 - relevant,Canh rau ngót thịt băm thanh mát đơn giản cho bữa cơm gia đình,Món canh,"Ngày hè oi bức bạn cần một món canh giải nhiệt. Đâu là một sự lựa chọn tốt nhất, vừa đơn giản trong cách làm mà có tác dụng giải nhiệt thanh mát tốt? Nếu còn đang suy nghĩ thì Điện máy XANH đề xuất đến bạn món canh r...",rau ngót | hành tím băm nhuyễn | thịt heo băm | gia vị thông dụng muối/ bột ngọt/ hạt nêm/ tiêu xay
11,D012,12,1448,2,2 - relevant,"Canh cá nục nấu ngót thơm ngon, thanh mát cho bữa cơm gia đình",Món canh,"Để bữa cơm tròn vị ngoài các món mặn như món xào , món kho thì món canh là thứ không thể thiếu. Hôm nay Điện máy XANH sẽ chia sẻ cùng bạn công thức nấu canh cá nục nấu ngót thanh mát cho gia đình nhé. Cùng vào bếp ng...",gia vị thông dụng muối/ bột ngọt/ tiêu | dầu ăn | củ nén khoảng | rau ngót khoảng bó | nước mắm | cá nục nhỏ
12,D013,13,7716,1,1 - partially related,"Cá diêu hồng chưng tương thơm ngon, lạ miệng, cực đơn giản",Món hấp,Cá diêu hồng chưng tương là món ăn quen thuộc và giàu dinh dưỡng thường xuất hiện trong những mâm cơm gia đình Việt. Hãy cùng Điện máy XANH vào bếp ngay hôm nay và thực hiện món hấp ngon này cho bữa ăn gia đình mình ...,dầu ăn | lá nhàu | gia vị thông dụng đường/tiêu/hạt nêm/bột ngọt | cá diêu hồng | nấm tai mèo mộc nhĩ | lá cách | hành tím băm | nấm rơm | hành lá | tương hột | tỏi băm
13,D014,14,1502,2,2 - relevant,Canh cá diêu hồng nấu măng chua thanh mát hấp dẫn cho ngày oi bức,Món canh,"Cho bữa cơm gia đình bạn thêm thơm ngon, ấm cúng với món canh cá diêu hồng nấu măng chua nóng hổi, vừa thổi vừa ăn này. Để Điện máy XANH mách bạn công thức siêu đơn giản và chi tiết. Cùng vào bếp thực hiện ngay nhé!",hành lá | gia vị thông dụng muối/ đường/ hạt nêm/ bột ngọt | hành tím | măng chua | đậu bắp | trái dứa thơm | nước mắm | cá diêu hồng khoảng | muỗng canh dầu ăn | ớt | cà chua
14,D015,15,7627,1,1 - partially related,Cá diêu hồng hấp nấm ngon mềm đậm đà đơn giản,Món hấp,"Các món hấp luôn là sự lựa chọn tuyệt vời để có một bữa ăn thanh đạm, lành mạnh, đảm bảo dinh dưỡng và hương vị hấp dẫn mà không cần chế biến cầu kì. Hôm nay, hãy cùng Điện máy XANH vào bếp thực hiện món cá diêu hồng...",gừng | dầu ăn | muối hột | hành ngò | hành tây | hành tím | sả | cá diêu hồng | cải bẹ trắng cải thìa | nước tương | dầu hào | hành phi | nấm rơm | gia vị thông dụng bột nêm/ bột ngọt/ muối/ tiêu | ớt | tỏi
15,D016,16,6777,1,1 - partially related,"Cá diêu hồng sốt cà chua thơm ngon hấp dẫn, ăn là ghiền",Món chiên,"Cá diêu hồng chiên sốt cà chua là một món chiên quen thuộc đến từ loài cá diêu hồng đầy dinh dưỡng kèm với sốt cà chua thơm ngon, đậm đà. Cuối tuần vào bếp cùng Điện máy XANH thực hiện ngay món ăn đơn giản này nhé!",gia vị thông dụng muối/tiêu/đường/hạt nêm | dầu ăn | thì là | muỗng canh nước mắm | con cá diêu hồng khoảng khoanh | hành lá | cà chua | ngò rí
16,D017,17,5020,1,1 - partially related,Cháo cá hồi rau ngót ngon không tanh bằng nồi cơm điện,Món cháo,"Bạn đang tìm cách nấu cháo cá hồi rau ngót thơm ngon, bổ dưỡng cho bé yêu? Vào bếp cùng khám phá công thức nấu món cháo chuẩn vị mà không lo tanh.",gừng | dầu ăn | rau ngót | hành tím | gia vị nêm nếm muối/hạt nêm | cháo trắn tô | cá hồi | tiêu bột tùy chọn
17,D018,18,1479,2,2 - relevant,Canh hến nấu rau ngót đơn giản thanh nhiệt cơ thể hiệu quả,Món canh,"Rau ngót nấu canh sẽ có vị thanh mát đặc trưng, khi kết hợp hến ngọt thịt sẽ càng thêm ngon và tròn vị. Hôm nay, Điện máy XANH hướng dẫn các bạn vào bếp nấu canh hến rau ngót - món canh đơn giản vừa giải nhiệt lại vừ...",rau ngót | gia vị thông dụng muối/ hạt nêm/ bột ngọt/ tiêu xay | hành lá cắt nhỏ | thịt hến
18,D019,19,8186,1,1 - partially related,Gỏi cá diêu hồng thơm ngon hấp dẫn lạ miệng dễ làm,Món gỏi - salad,Cuối tuần này bạn đã có thực đơn gì để tụ tập cùng với bạn bè chưa? Nếu chưa thì hãy lưu lại ngay công thức món gỏi cá diêu hồng vừa độc đáo lại hấp dẫn mà Điện máy XANH sẽ chia sẻ ngay sau đây nhé! Cùng vào bếp và t...,gừng | bột thính | dầu ăn | rau lá mơ/ lá cóc/ lá ổi/ lá xoài | gạo | sả | cá diêu hồng | nước | gia vị thông dụng muối/ đường/ bột ngọt | nước mắm | củ nghệ | ớt | men chua
19,D020,20,1447,2,2 - relevant,Canh cá hường nấu ngót thanh nhiệt dễ làm tại nhà,Món canh,"Cá hường là loài cá biển thơm ngon với thịt chắc, ngọt. Ngoài các món chiên , món nướng trong bài viết ngày hôm nay, hãy cùng Điện máy XANH vào bếp và trổ tài thực hiện ngay một món canh đầy hấp dẫn mang tên canh cá ...",cá hường | trái dứa thơm | nước mắm | gia vị thông dụng đường/muối/bột ngọt | hành lá | cà chua | ngò rí
20,D021,21,6721,1,1 - partially related,"Món cá diêu hồng rang muối HongKong thơm ngon, bắt miệng",Món chiên,"Cá diêu hồng rang muối HongKong là một món ăn vô cùng hấp dẫn, thích hợp để ăn trong các bữa tiệc hoặc dịp lễ. Trong bài viết này, Vào bếp sẽ hướng dẫn bạn làm món cá diêu hồng rang muối thơm ngon, hấp dẫn đơn giản n...",đường | bột chiên xù | nguyên liệu húng quế/ớt sừng/sả bào | tiêu | muối | bột chiên giòn | ớt bột | tôm khô | bột ngọt | cá diêu hồng file | đậu phộng xay | muỗng hạt nêm | tỏi phi xay
21,D022,22,7796,1,1 - partially related,Cá diêu hồng hấp Hong Kong mềm ngon đậm đà hấp dẫn,Món hấp,"Cá diêu hồng hấp Hong Kong là món hấp thơm ngon, hấp dẫn. Với những nguyên liệu gần gũi, cùng công thức chế biến đơn giản, nhanh chóng vẫn mang đến cho bữa cơm gia đình bạn món ăn chất lượng nhất. Cùng vào bếp thực h...",nấm đông cô khô nấm hương | gừng | hành tím | ớt sừng | cá diêu hồng | giấm | nước tương | gia vị thông dụng muối/ đường/ bột ngọt | hành lá | ngò rí
22,D023,23,1324,2,2 - relevant,"Canh cá bớp nấu ngót thơm ngon, đơn giản hấp dẫn ai cũng nấu được",Món canh,"Cá bớp là một trong những thực phẩm giàu dinh dưỡng và dễ ăn, có thể được chế biến thành nhiều món ăn phong phú và hấp dẫn. Những ngày hè thế này nếu được ăn một tô canh cá bớp nấu ngót thì thật là đúng điệu. Hôm nay...",gia vị thông thường hạt nêm/ muối/đường | muỗng canh nước mắm | cần tàu | cá bớp | hành lá | ớt | cà chua | ngò rí
23,D024,24,1404,2,2 - relevant,"Canh rau ngót nấu tôm khô thanh mát, chuẩn vị cho bữa cơm",Món canh,"Canh rau ngót tôm khô là sự lựa chọn hợp lý cho món canh vào những ngày hè nóng bức, vừa thơm ngon, vừa thanh mát, cực kỳ bắt cơm. Hãy cùng vào bếp với Điện máy XANH và thực hiện món ăn được chị Xuân chia sẻ ngay nhé!",gia vị thông dụng đường/ bột ngọt/ hạt nêm/ muối/ tiêu xay | dầu ăn | rau ngót | hành tím | tôm khô
24,D025,25,4307,2,2 - relevant,Cá ngừ nấu ngót ăn bún ngày lạnh bằng nồi inox Fivestar,Món nước,"Cá ngừ nấu ngót ăn bún là món ăn dân dã mà cực kỳ nổi tiếng của người dân miền Trung. Món ăn này mà được thưởng thức trong không khí se lạnh dịp cuối năm thì không gì thích hợp hơn. Hôm nay, hãy cùng Vào bếp làm món ...",hành ngò | át cá ngừ | gia vị nước mắm/muối/bột ngọt/tiêu | ớt | tỏi
25,D026,26,7194,1,1 - partially related,Cá diêu hồng chiên mắm xoài chua ngọt thơm ngon hấp dẫn,Món chiên,Cá chiên không còn quá xa lạ trong những bữa cơm gia đình. Hôm nay các bạn hãy cùng vào bếp với Điện máy XANH đổi vị cho cả nhà mình bằng món chiên vô cùng hấp dẫn là món cá diêu hồng chiên mắm xoài với vị chua ngọt ...,dầu ăn | quả xoài xanh | nước mắm | con cá diêu hồng khoảng | ớt | tỏi | muối/ đường
26,D027,27,7748,1,1 - partially related,Cá diêu hồng hấp dưa cải thơm ngon đơn giản cho gia đình,Món hấp,"Cá diêu hồng hấp là món ăn quá quen thuộc trong bữa ăn gia đình. Nhưng liệu bạn đã biết đến 2 cách làm cá diêu hồng hấp dưa cải và hấp cải thìa này chưa? Ngay sau đây, Điện máy XANH cùng bạn vào bếp thực hiện ngay 2 ...",dầu ăn | giấm trắng hoặc nước cốt chanh | cá diêu hồng | tỏi băm | gia vị thông dụng muối/ đường/ bột ngọt | dưa cải | nấm rơm | hành lá | ớt
27,D028,28,6956,0,0 - not relevant,Cách ướp cá chiên giòn rụm như da heo quay mà bên trong vẫn mọng nước,Món chiên,"Bạn đang tìm cách ướp cá chiên giòn để da cá vàng ươm, giòn rụm như cốm? Đừng lo! Cùng vào bếp với mẹo hay này, bạn sẽ có ngay món cá chiên giòn tan, thơm lừng, đảm bảo cả nhà mê tít với món chiên hấp dẫn này!",gia vị đường/nước mắm/bột ngọt | nước cốt chanh | cá diêu hồng khoảng sau làm sạch | bột chiên giòn hoặc bột mì đa dụng
28,D029,29,422,0,0 - not relevant,Canh cá Quỳnh Côi tại nhà,Món ngon hàng ngày,Canh cá Quỳnh Côi được ghi vào danh sách các món ngon đặc trưng của Thái Bình từ khoảng thế kỷ 17.,mắm | giấm tỏi ớt | phần nước dùng: nước dùng từ xương cá chính | gừng giã | nước mắm ngon | hạt nêm rau củ | nhưng theo thời gian tùy theo khẩu vị mỗi người thì thêm phần này để phần topping thêm phong phú: lấy các ...
29,D030,30,7849,1,1 - partially related,Cá diêu hồng hấp muối ớt thơm ngon đậm đà lạ miệng,Món hấp,"Món cá diêu hồng hấp muối ớt là món hấp cực kì lạ miệng và hấp dẫn. Với cách chế biến cực kì đơn giản, bạn có thể chiêu đãi cả gia đình một bữa tối ngon lành và tuyệt vời vô cùng nhanh chóng. Cùng vào bếp học làm nga...",dưa leo ăn kèm | đường | gừng | cá diêu hồng cá | muối ớt | bột ngọt | hành lá/rau răm | tỏi băm
30,D031,31,1780,2,2 - relevant,Canh cá chim nấu ngót thơm ngon đơn giản dễ làm,Món canh,"Không phải ai cũng biết nấu canh cá sao cho không tanh, giữ được vị ngon ngọt và thanh mát. Hôm nay cùng vào bếp với Điện máy XANH để thực hiện món canh hấp dẫn là canh cá chim nấu ngót thanh mát, không tanh vô cùng ...",dầu ăn | cá chim | gia vị thông dụng đường/ muối/ bột ngọt/ tiêu | cần tàu | nước mắm | hành lá | ớt | cà chua | tỏi
31,D032,32,6426,1,1 - partially related,Cá diêu hồng kho lạt thơm ngon đậm đà cho bữa cơm,Món kho,"Cá diêu hồng là một loại cá vô cùng quen thuộc trong các bữa ăn của mọi nhà. Hôm nay Điện máy XANH sẽ vào bếp cùng bạn thực hiện cá diêu hồng kho lạt, đảm bảo món kho này sẽ rất thơm ngon, bắt cơm cho bữa cơm gia đìn...",gừng | dầu ăn | hành tây | hành tím | cá diêu hồng | nước mắm | hành lá | ớt | cà chua | tỏi | gia vị thông dụng muối/ đường/ hạt nêm
32,D033,33,10134,1,1 - partially related,Khô cá diêu hồng mới lạ hấp dẫn an toàn cho gia đình thưởng thức,Món khô - mắm,"Cá diêu hồng là một trong những loài cá có thịt chắc, ngọt rất được ưa chuộng trong rất nhiều món ăn như món hấp, món kho, món canh, món khô ,... Hôm nay, hãy cùng Điện máy XANH vào bếp và thử tài thực hiện ngay món ...",đường | nước cốt chanh | muối | ớt sừng | cá diêu hồng | tiêu xay | bột ngọt | tỏi
33,D034,34,6594,1,1 - partially related,Cá diêu hồng kho nghệ thơm lừng ngon miệng dễ làm,Món kho,"Cá diêu hồng kho nghệ là một món kho hấp dẫn, cực bắt cơm và kích thích vị giác của người ăn. Vào bếp cùng Điện máy XANH thực hiện ngay món ăn thơm ngon này nhé!",đường | nghệ tươi | dầu ăn | hành tím | nước dừa | cá diêu hồng | nước mắm | hành lá | ớt
34,D035,35,1802,1,1 - partially related,Canh rau đắng cá lóc đậm đà thơm ngon cực đơn giản tại nhà,Món canh,"Nếu bạn đang tìm kiếm một món canh vừa thơm ngon, hấp dẫn đậm đà lại có công thức làm đơn giản, nhanh chóng để chiêu đãi gia đình thì canh rau đắng cá lóc có thể đáp ứng đủ tiêu chí trên. Hãy vào bếp cùng Điện máy XA...",rau đắng | gia vị thông dụng muối/ hạt nêm/ bột ngọt/ tiêu xay | muỗng canh nước mắm | cá lóc | hành lá
35,D036,36,149,2,2 - relevant,Canh rau ngót riêu tép ngọt mát ngày nóng,Món ngon hàng ngày,"Một bát canh với rau ngót xanh mềm, riêu tép ngọt thơm, thanh mát, nhanh chóng xua tan những mệt mỏi ngày nóng bức.",bó rau ngót | tép đồng nhỏ | muối | hạt nêm | hành khô | gia vị: mắm
36,D037,37,7391,1,1 - partially related,Cá diêu hồng chiên nước mắm tỏi ớt ngon đậm đà dễ làm,Món chiên,"Cá diêu hồng rất được ưa chuộng bởi sớ thịt dai, vị ngọt và ít khi gây dị ứng cho người ăn, nhất là các món chiên từ cá. Vì thế, chuyên trang Vào bếp sẽ hướng dẫn cho bạn thêm cách làm món cá diêu hồng chiên nước mắm...",muỗng cà phê bột ngọt | đường | dầu ăn | muối hột | muỗng canh ớt băm | tiêu | cá diêu hồng | tương ớt | hành tím băm | nước mắm | tỏi băm
37,D038,38,4968,0,0 - not relevant,Cháo cá thu cho bé siêu dinh dưỡng ngay tại nhà,Món cháo,"Cháo cá thu là món ăn đơn giản với hương vị thơm ngon lại vô cùng bổ dưỡng, giúp trẻ ăn mau chóng lớn trong giai đoạn phát triển. Hôm nay, hãy cùng Điện máy XANH vào bếp và thử nấu món cháo hấp dẫn này cho bé nhà mìn...",gừng | bó rau ngót nhật có thể thay bằng rau ngót thông thường | cơm khoảng | dầu ăn | muối | át cá thu khoảng | nước mắm
38,D039,39,340,0,0 - not relevant,Canh cá giấm mẻ,Món ngon hàng ngày,Canh cá là món ăn dân dã thơm ngon và bổ dưỡng. Món canh sẽ làm bữa cơm ngày hè của gia đình bạn ngon hơn nhờ vị thanh mát và ngọt đậm vị cá.,dầu ăn | rau xà lách | muối | thì là | philê cá điêu hồng | cơm mẻ | hạt nêm | nước mắm | hành lá | cà chua
39,D040,40,1653,2,2 - relevant,Canh cá hồi nấu ngót thơm ngon độc đáo tại nhà,Món canh,"Canh cá hồi nấu ngót hay canh cá hồi nấu với cà chua cần tây là một món ăn thanh mát, chua ngọt hài hoà rất ngon miệng, lại vô cùng bổ dưỡng nữa. Cùng vào bếp thực hiện món canh này cho gia đình mình bạn nhé.",dầu ăn | hành tím | gia vị thông dụng đường/ muối/ hạt nêm | thì là | cần tây | cá hồi | hành lá | ớt | cà chua
40,D041,41,1559,0,0 - not relevant,Bí quyết làm cá nấu dọc mùng miền Bắc thanh mát nhanh gọn cùng nồi lẩu điện,Món canh,"Vào những ngày thời tiết oi nóng, không gì hợp hơn là vào bếp chuẩn bị một món canh thanh mát, dễ ăn mà lại giàu dinh dưỡng. Cá nấu dọc mùng miền Bắc với vị chua nhẹ, ngọt tự nhiên từ cá kết hợp cùng dọc mùng giòn má...",dọc mùng bạc hà | gừng | cá diêu hồng hoặc cá sộp | gia vị thông dụng muối/ hạt nêm/ hạt tiêu/ dầu ăn/ bột canh | rau om/ ớt/ hành lá/ thì là | nước mắm | hành khô | mẻ đã lọc | cà chua | tỏi
41,D042,42,1457,2,2 - relevant,Canh cá thu nấu ngót thơm ngon ngọt nước cho bữa cơm thêm đậm vị,Món canh,"Canh cá thu nấu ngót không chỉ thơm ngon ngọt nước mà còn chứa nhiều chất dinh dưỡng cho cơ thể. Hôm nay cùng Điện máy XANH đổi vị với món canh cá thu nấu ngót chua chua ngọt ngọt nhé. Chờ gì nữa, vào bếp nấu ngay mó...",gia vị thông dụng đường - muối - hạt nêm - bột ngọt | tắc | dầu ăn | cá thu | hành tím | gừng nhỏ | rau cần | nước mắm | hành lá | cà chua
42,D043,43,1547,1,1 - partially related,"Canh riêu cá siêu hấp dẫn, ai ăn cũng sẽ ghiền",Món canh,"Canh riêu cá là món canh được nhiều người ưa thích và thường xuyên có mặt trong các bữa cơm. Với cách làm đơn giản, nguyên liệu dễ tìm nhưng lại đem đến hương vị thơm ngon khó cưỡng. Bạn còn chần chờ gì nữa mà không ...",mẻ | gừng | dầu ăn | hành tím | muối | cá diêu hồng | rau thì là | nước mắm | cà chua
43,D044,44,1325,2,2 - relevant,Canh rau ngót không - rau ngót chay thanh đạm mà đưa cơm,Món canh,"Rau ngót là loại rau có nhiều chất dinh dưỡng tốt cho sức khỏe như khoáng chất, vitamin, chất xơ,... và với vị mềm ngọt đặc trưng nên được nhiều người ưa thích. Hôm nay các bạn hãy cùng vào bếp với Điện máy XANH nấu ...",hạt nêm chay | muỗng cà phê bột ngọt | bó rau ngót khoảng | muỗng cà phê muối
44,D045,45,939,1,1 - partially related,Cá diêu hồng muối chiên,Món chính,"Mùa đông lạnh nên ăn món gì cũng có cảm giác nóng, rất là ngon miệng.",muối | cá diêu hồng | đường trắng | nước mắm | ớt | tỏi
45,D046,46,7450,1,1 - partially related,Cá diêu hồng chiên sả ớt ngon đậm đà cho bữa cơm,Món chiên,"Cá diêu hồng chiên là một món chiên quen thuộc, thơm ngon giòn ngọt, nay được kết hợp thêm sả và ớt sẽ cho chúng ta một món ngon mới rất hấp dẫn để chiêu đãi gia đình. Hãy cùng Điện máy XANH vào bếp thực hiện ngay mó...",dầu ăn | sả | ớt bột | cá diêu hồng khoảng | tỏi đập dập | ớt | gia vị thông dụng muối/ hạt nêm/ bột ngọt/ tiêu

========================================================================================================================
query_id: 317
query_text: Sữa đậu phộng thơm ngon giúp tăng cân nhanh chóng
relevance distribution: {0: np.int64(46), 1: np.int64(3), 3: np.int64(1)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,9796,0,0 - not relevant,"Sữa đậu Hà Lan và sinh tố đậu Hà Lan thơm béo, đầy dinh dưỡng",Thức uống,"Sữa và sinh tố là một trong những thức uống dinh dưỡng, với nhiều tác dụng tốt đối với sức khỏe. Hôm nay, Điện máy XANH sẽ cùng vào bếp mách bạn 2 cách làm sữa đậu Hà Lan và sinh tố đậu Hà Lan thơm béo, đơn giản tại ...",sữa đặc on | nước | đậu hà lan
1,D002,2,4496,0,0 - not relevant,[Video] Cách làm kem chuối cacao bằng máy xay sinh tố đơn giản tại nhà,Món kem,Có phải bạn luôn nghĩ để có làm được một viên kem tươi mát phải cần có máy làm kem và rất nhiều nguyên liệu đắt tiền? Hãy tạm gác suy nghĩ đó qua một bên vì hôm nay chuyên mục Vào bếp sẽ hướng dẫn cho các bạn làm kem...,chuối lớn | hạt đậu phộng dùng để trang trí | bột ca cao | bơ đậu phộng | sữa tươi tùy theo sở thích
2,D003,3,9847,1,1 - partially related,Sinh tố bơ đậu phộng thơm béo cho bữa sáng đầy dinh dưỡng,Sinh tố,"Bổ sung dinh dưỡng mỗi sáng với món sinh tố bơ đậu phộng thơm ngon, bùi béo để cho cơ thể có thêm nhiều năng lượng cho ngày mới thật năng động nhé! Cùng vào bếp với Điện máy XANH xem ngay công thức và thực hiện món s...",muỗng cà phê muối | đậu phộng rang giã dập | whipping cream | bột bơ đậu phộng peanut butter powder | sữa hạnh nhân không đường hoặc sữa tươi không đường | bơ đậu phộng | topping cream dùng trang trí | đá viên | bột ...
3,D004,4,8946,0,0 - not relevant,"Đậu phộng nướng ngũ vị hương thơm ngon, giòn tan dễ làm",Ăn vặt,Đậu phộng nướng ngũ vị là một trong những món ăn vặt mà bạn không nên bỏ qua bởi cách làm khá đơn giản và hương vị lại vô cùng thơm ngon. Cùng bài vào bếp dưới đây thực hiện món ăn này nhé!,muỗng canh ngũ vị hương | nước cốt dừa | đậu phộng
4,D005,5,9014,0,0 - not relevant,Đậu phộng ngào đường giòn tan đơn giản nhâm nhi cả ngày,Ăn vặt,"Để các cuộc trò chuyện không còn nhàm chán hay là khi thưởng thức 1 bộ phim được gay cấn hơn thì không thể thiếu sự xuất hiện của các món ăn vặt rồi! Nhân đây, hôm nay Điện máy XANH sẽ tiết lộ cho mọi người món đậu p...",đường | muối | bột bắp | gừng nhỏ | đậu phộng
5,D006,6,2495,0,0 - not relevant,Kẹo socola đậu phộng giòn giòn cả nhà đều thích,Món bánh,"Kẹo socola đậu phộng giòn tan, thơm lừng lại có cách làm đơn giản đến bất ngờ. Các bạn cùng vào bếp với Điện máy XANH làm món ăn vặt hấp dẫn này nhé!",muối | socola đen 70 | socola sữa | đậu phộng
6,D007,7,6999,0,0 - not relevant,Đậu phụ từ sữa đậu nành nhanh gọn đơn giản tại nhà,Món chiên,"Đậu phụ làm từ sữa đậu nành nhanh gọn, đơn giản nhưng không kém phần thơm ngon, hấp dẫn. Món hấp này có lớp vỏ ngoài vàng giòn cùng với độ mềm mịn, béo ngậy bên trong thì chắc chắn sẽ đem đến cho bạn một trải nghiệm ...",muỗng cà phê muối | sữa đậu nành ít đường | dầu ăn | bột bắp | trứng gà
7,D008,8,9648,0,0 - not relevant,"Sữa đậu nành hột gà béo ngậy, hấp dẫn tại nhà",Thức uống,"Mách bạn cách làm sữa đậu nành hột gà thơm bùi, béo ngậy vừa ngon miệng lại vừa bổ dưỡng. Với cách chế biến đơn giản, kết hợp hài hòa giữa các nguyên liệu nên thức uống không hề có mùi tanh từ trứng. Hãy cùng Điện má...",sữa đậu nành | lòng đỏ trứng gà | bột cacao không bắt buộc | sữa đặc
8,D009,9,9741,0,0 - not relevant,Sữa đậu ngự mix hạt điều bằng máy nấu sữa hạt thơm ngon đơn giản,Thức uống,"Sữa hạt là một thức uống thơm ngon, bổ dưỡng và đặc biệt được nhiều chị em yêu thích vì có công dụng đẹp da, giữ dáng. Hôm nay, hãy vào bếp cùng Điện máy XANH thực hiện món sữa đậu ngự mix hạt điều cực ngon và đơn gi...",đường thốt nốt hoặc đường phèn | nước lọc | hạt điều | đậu ngự
9,D010,10,9730,0,0 - not relevant,Sữa đậu nành bằng máy làm sữa hạt thơm béo không bã,Thức uống,"Bạn muốn tự tay làm sữa đậu nành thơm ngon, sánh mịn ngay tại nhà? Với công thức cách làm sữa đậu nành bằng máy làm sữa hạt này, dù bạn là người mới Vào bếp cũng dễ dàng có ngay một thức uống bổ dưỡng, không cần lọc ...",mè đen | hạnh nhân đã sấy | gia vị thông dụng đường/đá | đậu nành | nước
10,D011,11,8651,0,0 - not relevant,Muối vừng lạc (muối mè đậu phộng) đơn giản cho bữa ăn chay đạm bạc,Món chay,"Muối vừng lạc là một món muối chấm vô cùng thơm ngon và hấp dẫn với vị bùi, thơm của đậu phộng cùng với vị mặn vừa ăn. Đây là món ngon khi kết hợp ăn cùng với các món như: xôi, cơm trắng, bánh khoai mì hấp,.. Cùng và...",mè trắng | muối hột | đậu phộng sống
11,D012,12,9103,0,0 - not relevant,"Cách luộc đậu phộng (lạc) mau mềm, không thâm, không bị nứt vỏ",Ăn vặt,"Đậu phộng có giá trị dinh dưỡng cao, được làm ra nhiều món ăn hấp dẫn như xôi đậu phộng và chè bà ba , thậm chí luộc ăn cũng rất ngon. Vậy hãy vào bếp cùng Điện máy XANH hướng dẫn cho bạn và cùng lưu lại một số mẹo s...",muỗng cà phê muối | đậu phộng nguyên vỏ
12,D013,13,9522,0,0 - not relevant,"Hướng dẫn cách làm sữa đậu đỏ bằng máy làm sữa hạt thơm ngon, bổ dưỡng",Thức uống,"Sữa hạt là món thức uống được nhiều chị em lựa chọn vì có nhiều dưỡng chất tốt cho sức khỏe, nhất là đối với những người muốn giảm cân hoặc tăng cân. Hãy vào bếp cùng Điện máy XANH để học ngay công thức nấu sữa đậu đ...",sữa tươi | đường | đậu đỏ
13,D014,14,894,0,0 - not relevant,"Pate chay từ đậu nành, đậu phộng, đậu xanh",Món chay,Béo béo thơm thơm không cưỡng nổi khi ăn cùng bánh mì,sữa tươi | đậu xanh | bánh mì khô ổ | đậu nành | đậu phộng
14,D015,15,9160,0,0 - not relevant,"Đậu phộng da cá ăn vặt cực ngon, dễ làm",Ăn vặt,"Đậu phộng không chỉ được sử dụng để làm kẹo bánh mà còn có thể chế biến món ăn vặt hàng ngày. Cùng Điện máy XANH vào bếp và thử ngay cách làm đậu phộng da cá ăn vặt cực ngon, dễ làm nhé!",bột mì | đường cát trắng | muối | đậu phộng khô
15,D016,16,9829,0,0 - not relevant,Hướng dẫn cách làm sữa đậu gà kết hợp cùng hạt macca bằng máy làm sữa hạt,Thức uống,"Sữa hạt là thức uống thơm ngon chứa nhiều dinh dưỡng không chỉ tốt cho sức khỏe mà còn giúp giữ dáng đẹp da. Hôm nay, hãy cùng chuyên mục Mẹo vào bếp của Điện máy XANH thực hiện món sữa đậu gà kết hợp hạt macca bằng ...",đậu gà | đường | nước lọc | hạt macca
16,D017,17,8889,0,0 - not relevant,Bơ đậu phộng không đường giảm cân giàu dinh dưỡng đơn giản dễ làm,Ăn vặt,"Bơ đậu phộng béo bùi rất phù hợp để dùng ăn kèm cùng các món ăn vặt hoặc dùng làm các món bánh cũng đều rất ngon. Với công thức bơ đậu phộng giảm cân không đường mà Điện máy XANH sắp giới thiệu, bạn vừa có được món b...",muỗng cà phê muối | đậu phộng | mật ong | dầu oliu
17,D018,18,9346,0,0 - not relevant,"Thử làm Pudding đậu nành giảm cân, giải nhiệt cho dịp Tết",Ngày lễ Tết,"​Dù đã chuẩn bị kha khá thực đơn cho dịp tết nhưng bạn còn đang băn khoăn không biết làm món tráng miệng nào cho gia đình? Vậy sao không vào bếp thử làm Pudding đậu nành, vừa giải nhiệt giảm cân mà lại vô cùng đơn giản!",đường | mật ong | gelatin | sữa đậu nành | kem tươi - whipping cream
18,D019,19,681,0,0 - not relevant,Làm tào phớ trong nháy mắt bằng đường nho,"Món tráng miệng, giải khát","Cho một muỗng nhỏ đường nho vào sữa đậu nành, bạn nhanh chóng thu được mẻ tào phớ mềm mịn, ngon như ngoài tiệm.",sữa đậu nành
19,D020,20,9504,0,0 - not relevant,Sữa đậu xanh bí đỏ sánh mịn thơm ngon đầy dinh dưỡng,Thức uống,"Sữa đậu xanh bí đỏ là thức uống thơm ngon, hấp dẫn, thanh mát cho mùa hè này. Hôm nay, chuyên trang Vào bếp của Điện máy XANH sẽ hướng dẫn bạn cách món sữa đậu xanh bí đỏ sánh mịn và độc đáo này nhé! Hãy cùng thực hi...",đường | đậu xanh không vỏ | bí đỏ | sữa đặc
20,D021,21,9878,0,0 - not relevant,Trà sữa đậu nành kem phô mai ngọt dịu thơm ngon đơn giản tại nhà,Trà sữa,"Trà sữa đậu nành là sự kết hợp hoàn hảo giữa lớp kem phô mai béo ngậy cùng với vị trà đậu nành thơm dịu, ngọt nhẹ cùng lớp thạch mềm mịn hấp dẫn. Nếu đã chán các hương vị trà sữa truyền thống , hãy thử đổi vị sang mó...",đường | cream cheese | whipping cream | sữa đặc | sữa đậu nành | đậu nành | á lá gelatin | ói trà túi lọc
21,D022,22,9803,0,0 - not relevant,"Sữa đậu đỏ thơm ngon, béo ngậy để chiêu đãi cả nhà",Thức uống,"Với món sữa đậu đỏ vô cùng thơm ngon, bổ dưỡng với vị ngọt của sữa và vị béo bùi của đậu mà Điện máy XANH vừa chia sẻ hy vọng bạn có thể thực hiện thức uống này chiêu đãi gia đình vào những dịp cuối tuần. Cùng vào bế...",đường | đậu đỏ | sữa tươi không đường
22,D023,23,9678,0,0 - not relevant,Sữa đậu đen thơm ngon bổ dưỡng tại nhà để chiêu đãi gia đình,Thức uống,"Với cách nấu sữa đậu đen vô cùng thơm ngon, bổ dưỡng với vị béo của sữa và vị thơm của đậu mà Điện máy XANH vừa chia sẻ hy vọng bạn có thể thực hiện thức uống này vào những dịp cuối tuần. Cùng vào bếp ngay nhé!",sữa tươi | đường phèn | muỗng cà phê muối | vani | đậu đen xanh lòng | lá dứa
23,D024,24,8702,0,0 - not relevant,Sữa chua chay thơm béo healthy đơn giản bằng nồi,Món chay,"Bạn muốn tự tay làm sữa chua chay sánh mịn, tốt cho sức khỏe? Vào bếp ngay để khám phá cách làm sữa chua thuần chay siêu đơn giản này! Món tráng miệng thanh mát, bổ dưỡng này sẽ là lựa chọn ăn vặt hoàn hảo. Đảm bảo t...",sữa đậu nành | sữa chua cái ở nhiệt độ phòng | đường
24,D025,25,9617,0,0 - not relevant,Nước đậu ván rang thơm ngon thanh mát tốt cho sức khỏe,Thức uống,"Nước đậu ván rang là món thức uống giải nhiệt mùa hè khá quen thuộc. Bên cạnh đó, loại nước này còn có nhiều lợi ích khác tốt cho đường ruột, trị nôn mửa và hỗ trợ trẻ ăn ngon cơm hơn. Vì vậy, hôm này cùng chuyên tra...",đậu ván khô
25,D026,26,2699,0,0 - not relevant,"Bánh mochi nhân bơ đậu phộng thơm ngon, đơn giản dễ làm",Món bánh,"Mochi là món bánh có thể chế biến theo nhiều cách khác nhau, chuyên mục vào bếp của Điện máy XANH giới thiệu tới bạn thêm công thức bánh mochi nhân bơ đậu phộng, các bạn hãy thực hiện ngay nhé!",sữa tươi | đường | bột nếp | bột bắp | bơ đậu phộng | bơ thực vật
26,D027,27,5925,0,0 - not relevant,"Mì Udon sốt bơ đậu phộng béo ngon, hấp dẫn đổi vị cuối tuần",Món xào,"Mì Udon dai ngon trộn với sốt bơ đậu phộng vô cùng thơm béo, lạ miệng. Các bạn hãy vào bếp với Điện máy XANH để thực hiện món mì trộn siêu ngon này nhé!",mì udon | hành boa rô | đậu hũ viên chiên | tiêu | đậu phộng rang giã nhuyễn | giấm gạo | ớt sừng | bơ đậu phộng | dầu mè | xì dầu | ớt bột | gừng tươi hoặc bột gừng | mè rang
27,D028,28,7276,0,0 - not relevant,Đậu phộng da cá cốt dừa giòn tan béo ngậy bằng chảo chiên ngập dầu,Món chiên,"Hôm nay, hãy cùng vào bếp khám phá cách làm đậu phộng da cá cốt dừa giòn tan, béo ngậy chỉ trong 30 phút. Món ăn vặt hấp dẫn này chắc chắn sẽ làm cả gia đình bạn mê mẩn, đặc biệt là các bé.",đường | muối | bột mì bột mì đa dụng | lạc hạt nhỏ và đều đậu phộng | nước cốt dừa
28,D029,29,4029,0,0 - not relevant,Chè sake đậu phộng mềm béo thơm ngon cả nhà mê tít,Món chè,Trái sake ngọt bùi đặc trưng kết hợp cùng đậu phộng thơm béo sẽ cho ta một món chè thơm ngon bổ dưỡng. Hãy cùng chuyên mục Vào bếp của Điện máy XANH làm ngay món chè sake đậu phộng thơm ngon đầy hấp dẫn nhé.,ống chiết xuất vani | muối | bột khoai | bột báng | đường trắng | sake khoảng | đậu phộng
29,D030,30,3912,0,0 - not relevant,"Chè mít đậu xanh bùi ngọt, thơm ngon, đơn giản tại nhà",Món chè,Chè mít đậu xanh có vị bùi ngọt nhẹ từ đậu xanh cùng mùi thơm nức mũi từ mít tươi đem đến cho bạn một món chè lạ miệng nhưng lại vô cùng thơm ngon. Hôm nay hãy vào bếp ngay cùng Điện máy XANH khám phá công thức và th...,đường phèn | muối | đậu xanh nguyên hạt | đậu phộng rang | quả mít
30,D031,31,2846,0,0 - not relevant,Bánh bột đậu phộng thơm ngon giòn xốp dễ làm,Món bánh,"Bánh bột đậu phộng thơm béo, mềm tan trong miệng vừa dễ ăn lại vừa dễ làm. Nếu bạn đang tìm một món bánh ăn vặt có cách thực hiện nhanh chóng thì hãy vào bếp ngay cùng Điện máy XANH nhé!",muỗng cà phê muối | dầu ăn | đậu phộng rang giã nhuyễn | muỗng cà phê bột nở baking powder | đường bột | bột mì đa dụng bột mì số
31,D032,32,8833,0,0 - not relevant,Bơ đậu phộng - bơ lạc thơm ngon siêu đơn giản tại nhà,Ăn vặt,"Bơ đậu phộng thơm thơm béo béo, đậm đà, lại an toàn và vệ sinh thật hấp dẫn đúng không nào? Hãy cùng vào bếp thực hiện ngay món bơ thơm ngon này với mẹo chế biến đơn giản dưới đây cho gia đình mình nhé!",dầu ăn | muối | mật ong | đường bột | đậu phộng
32,D033,33,9754,0,0 - not relevant,"Sữa đậu nành mè đen bằng máy cực thơm ngon, đơn giản",Thức uống,"Sữa đậu nành mè đen sánh mịn, không những thơm ngon lại còn cực kỳ tốt cho sức khỏe. Nếu cách nấu truyền thống tốn quá nhiều thời gian thì với công thức này, bạn chỉ cần bỏ ra 30 phút là có ngay thức uống hấp dẫn. Cù...",mè đen | đậu nành | đường phèn | nước lọc
33,D034,34,9845,1,1 - partially related,"Sinh tố đậu phộng chuối thơm béo, nhiều protein đơn giản tại nhà",Sinh tố,"Một bữa sáng vội vàng sẽ trở nên đơn giản hơn với ly sinh tố đậu phộng bùi béo, thơm ngon, vừa dễ uống lại nạp nhiều năng lượng cho sức khỏe với lượng protein cao. Món sinh tố này chỉ mất vài phút để thực hiện, hãy c...",chuối | đậu phộng rang | hạt chia | chà là khô | muỗng cà phê bột quế | đậu phộng
34,D035,35,9466,3,3 - highly relevant,Sữa đậu phộng thơm ngon giúp tăng cân nhanh chóng,Thức uống,"Đậu phộng là loại hạt chứa rất nhiều chất dinh dưỡng tốt cho cơ thể. Sữa đậu phộng được xay từ những hạt đậu phộng có vị bùi bùi, béo thơm mà còn giúp bổ sung vitamin cần thiết. Hãy cùng vào bếp thực hiện loại thức u...",đường phèn | lá dứa | tinh chất vani | sữa đặc | đậu phộng
35,D036,36,9962,0,0 - not relevant,Sữa chua dừa béo mịn nhanh chóng dễ dàng,Món tráng miệng,"Sữa chua là món tráng miệng thơm ngon, bổ dưỡng được mọi người ở nhiều lứa tuổi yêu thích. Nay sữa chua lại được kết hợp với dừa béo ngậy không biết hương vị sẽ như thế nào đây? Vào bếp cùng Điện máy XANH tham khảo n...",men làm sữa chua viên nang probiotic | nước cốt dừa
36,D037,37,7649,0,0 - not relevant,"Xôi đậu 3 màu ăn cùng muối đậu phộng thơm ngon, cực dễ làm",Món hấp,"Xôi đậu là món hấp thơm ngon với vị bùi béo đặc trưng của 3 loại đậu bao gồm đậu đen, đậu phộng và đậu xanh cùng với độ mềm, dẻo của nếp mang đến sự thú vị và cuốn hút mỗi khi thưởng thức. Hôm nay, chuyên trang vào b...",đường | dầu ăn | nếp | đậu đen | muối | đậu xanh | lá dứa | đậu phộng
37,D038,38,9757,0,0 - not relevant,"Sữa đậu nành lá dứa bằng máy làm sữa hạt cực thơm ngon, đơn giản",Thức uống,"Sữa đậu nành là thức uống thơm ngon, nay lại kết hợp với lá dứa có hương thơm đặc trưng tạo nên mùi vị vô cùng mới lạ. Hãy Vào bếp cùng Điện máy XANH khám phá ngay cách nấu sữa đậu nành lá dứa bằng máy làm sữa hạt cự...",đậu nành khô | á dứa tươi | nước lọc
38,D039,39,8621,0,0 - not relevant,Nước chấm gỏi cuốn chay từ đậu phộng thơm ngon khó cưỡng tại nhà,Món chay,"Các món chay như gỏi cuốn, phở cuốn,... sẽ ngon hơn nhiều nếu có loại nước chấm phù hợp. Hôm nay, Điện máy XANH giới thiệu tới bạn nước chấm đậu phộng dùng cho gỏi cuốn chay cực kỳ hấp dẫn, công thức được chia sẻ bởi...",dầu ăn | hành tím | nước tương | muối/ đường | bột năng | hạt nêm chay | giấm táo | đậu phộng
39,D040,40,8888,0,0 - not relevant,Đậu phộng rang bơ tỏi ớt thơm ngon vừa miệng cực đơn giản tại nhà,Ăn vặt,"Một trong những món ăn vặt ""thần thánh"" được nhiều người đem lòng thương nhớ đó chính là đậu phộng rang. Thế nhưng, ngoài cách rang muối, rang ngũ vị,... thì bạn có biết đậu phộng rang bơ tỏi ớt cũng thơm ngon lắm kh...",dầu ăn | ớt băm | đậu phộng lạc | tỏi băm | gia vị thông dụng muối/ đường/ bột ngọt | bơ thực vật
40,D041,41,10015,0,0 - not relevant,"Sữa chua Hy Lạp từ sữa đậu nành thơm ngon, dẻo mịn, bổ dưỡng",Món tráng miệng,"Sữa chua Hy Lạp là một “phiên bản” nâng cấp từ sữa chua truyền thống với độ dẻo, đặc quánh như kem. Bên cạnh hỗ trợ giảm cân hiệu quả, làm đẹp da, món ăn vặt này còn cực kỳ tốt cho sức khỏe. Cách làm sữa chua Hy Lạp ...",đường thô | sữa đậu nành | hộp sữa chua cái | nước cốt dừa
41,D042,42,4557,0,0 - not relevant,Kem đậu phộng bùi ngậy thơm béo mát lạnh ăn thử là mê,Món kem,"Chiêu đãi gia đình món kem đậu phộng bùi ngậy thơm béo lại mát lạnh, vừa ngọt ngào vừa nhiều dinh dưỡng khiến ai ăn cũng thích mê. Hôm nay, theo chân chuyên trang Vào bếp của Điện máy XANH thực hiện ngay món kem hấp ...",đường | sữa tươi nguyên kem | tinh chất vani | trứng gà | double cream | đậu phộng
42,D043,43,9560,0,0 - not relevant,Đá xay sữa bò đậu đỏ mát lạnh ngọt thơm cực đơn giản,Thức uống,"Vào những ngày hè nóng bức mà có một ly đá xay sữa bò đậu đỏ ngọt ngọt, bùi bùi để giải nhiệt thì còn gì bằng phải không nào? Hôm nay hãy vào bếp cùng Điện máy XANH và trổ tài thực hiện ngay món thức uống đơn giản và...",hộp sữa bò tươi | đá viên | đậu đỏ | đường vàng
43,D044,44,7303,0,0 - not relevant,"4 món nhậu đơn giản dễ làm mà ngon, ăn cực phê",Món chiên,"Ngày mưa còn gì bằng tụ họp bạn bè, gia đình bên những dĩa mồi nhắm và bia bọt mát lạnh. Bài viết này Điện máy XANH hướng dẫn bạn cách làm 4 món nhậu vừa ngon vừa dễ làm để đãi cả nhà, cùng vào bếp ngày nhé!",muối | dầu ăn | đậu phộng
44,D045,45,9229,0,0 - not relevant,"Đậu phộng (lạc) rang nước tương lạ miệng, giòn ngon hấp dẫn",Ăn vặt,Đậu phộng (lạc) là một nguyên liệu được sử dụng nhiều trong những món ăn. Đặc biệt đậu phộng rang sẽ là một món ăn vặt thơm ngon được nhiều người yêu thích. Hãy cùng vào bếp thực hiện ngay món đậu phộng (lạc) rang nư...,đường | rượu trắng | đậu phộng lạc | si rô ngô | mè trắng | nước tương
45,D046,46,8813,0,0 - not relevant,Đậu phộng rang mật ong bột quế bằng nồi chiên không dầu thơm ngon,Ăn vặt,"Những ngày ở nhà mà có một món ăn vặt thơm ngon, hấp dẫn, giòn giòn để nhâm nhi thưởng thức trong lúc tán gẫu, xem phim thì còn gì bằng. Hôm nay, hãy cùng vào bếp để Điện máy XANH giới thiệu cách làm món đậu phộng ra...",đường/ muối | mật ong | nước lọc | bột quế | đậu phộng
46,D047,47,9468,1,1 - partially related,Sữa bí đỏ tăng cân cho người gầy cực thơm ngon mà hiệu quả,Thức uống,"Sữa bí đỏ có hương vị ngon ngọt, vừa thơm vừa béo ngậy dành cho người gầy muốn tăng cân. Không chỉ thế, món đồ uống này còn cực kỳ bổ dưỡng và tốt cho sức khoẻ nữa. Hãy cùng vào bếp với Điện máy XANH làm ngay thức uố...",sữa đặc | bí đỏ | nước cốt dừa | sữa tươi không đường
47,D048,48,9838,0,0 - not relevant,Sữa đậu nành không bỏ xác đơn giản bổ dưỡng thơm ngon tại nhà,Thức uống,Nếu bạn đang tìm một loại thức uống vừa dinh dưỡng lại thơm ngon với cách làm siêu đơn giản tại nhà thì hãy thử ngay cách làm sữa đậu nành không bỏ xác này nhé. Với công thức xay nguyên xác giúp bạn hấp thu tối đa cá...,đậu nành | nước lọc
48,D049,49,8963,0,0 - not relevant,Sữa chua đậu nành úp ngược thơm ngon tốt cho sức khỏe tại nhà,Ăn vặt,"Đậu nành được xem là loại thực phẩm tốt cho sức khỏe và vóc dáng của phụ nữ. Bên cạnh chế biến thành sữa, đậu nành còn được sử dụng làm sữa chua với hương vị cực kỳ thơm ngon, bổ dưỡng. Cùng Điện máy XANH vào bếp học...",đường | sữa chua | sữa đậu nành không đường
49,D050,50,2172,0,0 - not relevant,Mắm đậu phộng ăn bánh xèo miền Trung thơm ngon khó cưỡng,Món bánh,"Mắm đậu phộng bùi, béo, chua, ngọt, mặn hòa quyện hài hòa với nhau. Món nước chấm này có thể sử dụng cho rất nhiều món ăn như thịt cuốn bánh tráng, cá cuốn bánh tráng,... đặc biệt dùng chấm bánh xèo cực ngon. Vào bếp...",gừng | đường | chanh | nước mắm | ớt | tỏi | đậu phộng

========================================================================================================================
query_id: 360
query_text: Đậu phụ nhồi thịt sốt cà chua đơn giản cho bữa cơm hàng ngày
relevance distribution: {0: np.int64(23), 1: np.int64(18), 2: np.int64(8), 3: np.int64(1)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,171,0,0 - not relevant,Mỳ Ý Spaghetti thịt bò bằm sốt cà chua đơn giản tại nhà,Món ngon hàng ngày,"Tranh thủ cà chua đang vào mùa ngon và rẻ, bạn đổi vị cho các bé với món mỳ Ý thơm ngon như ngoài hàng.",2- tỏi | đường | bơ | hành tây | thịt bò xay | lá oregano | giấm | gia vị: muối | mỳ spaghetti | cà chua chín | tương cà chua | bột basil | hạt tiêu | dầu ô liu
1,D002,2,1191,1,1 - partially related,Đậu phụ Tứ Xuyên sốt cay,Món chay,Đậu phụ Tứ Xuyên cay này rất dễ.\r\nHôm nay nấu món này nha,gừng | sa tế | nấm hương | hành tím | đậu phụ | tỏi
2,D003,3,7403,1,1 - partially related,"Cà tím nhồi đậu phụ (đậu hũ) thơm ngon, đơn giản tại nhà",Món chiên,"Hôm nay Điện máy XANH sẽ hướng dẫn các bạn làm một món chiên từ cà tím và đậu phụ, đây là một món ăn đậm vị và vô cùng hấp dẫn. Thích hợp cho những ngày ăn chay. Cùng vào bếp ngay để thực hiện món chiên đơn giản mà l...",cà tím | nấm mèo | dầu ăn | gia vị thông dụng muối/ đường/ hạt nêm/ tiêu | đậu hũ trắng đậu phụ | nước tương | hành lá | ớt hiểm | tỏi băm | củ cà rốt | ngò rí
3,D004,4,1190,0,0 - not relevant,Bún xào chay cho ngày rằm,Món chay,Những ngày rằm thay vì những món ăn chay với cơm thì hôm nay làm món bún xào chay này sẽ tiết kiệm được thời gian cho bạn cũng đảm bảo được độ ngon mà nó mang lại.,bún gạo | đậu phụ chiên | cà rốt | cải thìa
4,D005,5,1411,0,0 - not relevant,Canh chua rau muống chay thanh đạm mà vẫn ngon cơm,Món canh,"Những món ăn từ thịt cá đôi khi khiến bạn ngán ngẩm và ăn cơm không ngon miệng, những lúc như thế hãy nghĩ đến món canh chua rau muống nấu chay, vừa thanh đạm vừa bổ dưỡng, cả nhà cùng tấm tắc khen ngon. Còn bây giờ ...",dầu ăn | nấm hải sản | đậu phụ chiên khoảng | rau muống | rau nêm ngổ/ ngò gai | gia vị thông dụng muối/ đường/ bột ngọt | sấu | ớt | cà chua | tỏi
5,D006,6,871,2,2 - relevant,Đậu hũ chiên sốt cà chua,Món chay,"Đậu hũ chiên sốt cà chua là món ăn không còn xa lạ với nhiều người, nhất là các bạn sinh viên. Món này hội tụ 3 yếu tố ngon, bổ, rẻ. Từng miếng đậu hũ mềm, thấm đậm gia vị, thêm phần nước sốt chua chua, ngọt ngọt thậ...",hành boa rô | dầu ăn | đường trắng cafe | muối cafe | đậu hũ chiên | bột ngọt | cà chua
6,D007,7,7437,0,0 - not relevant,"Trứng sốt cà chua đơn giản, ngon miệng cho bữa cơm nhà tròn vị",Món chiên,"Bạn đang tìm món trứng sốt cà chua ngon miệng, dễ làm cho bữa cơm gia đình? Vào bếp ngay để khám phá cách làm trứng gà sốt cà chua đơn giản, biến tấu bữa ăn thêm hấp dẫn với món chiên này nhé. Đảm bảo cả nhà sẽ thích...",hành tím | cà chua khoảng | nước lọc | gia vị thông dụng tương ớt/ dầu hào/ đường/ hạt nêm/ bột ngọt/ nước mắm/ dầu ăn/ muối | hành lá | trứng gà | ngò rí
7,D008,8,1428,0,0 - not relevant,Canh chua đậu chay đơn giản cho bữa cơm chay thêm vị,Món canh,Canh chua đậu chay là một trong những món chay hấp dẫn lại còn rất dẽ thực hiện. Bài viết vào bếp dưới đây sẽ hướng dẫn đến bạn cách thực hiện món canh chua thơm ngon này.,gia vị đường/hạt nêm chay/nước mắm chay | tắc | dầu ăn | các loại đậu đậu rồng/đậu bắp/đậu đũa | rau thơm ngò gai/rau ngò om | đậu hũ | thơm | ớt | cà chua
8,D009,9,4680,0,0 - not relevant,"Lasagna đơn giản, đúng chuẩn kiểu Ý ngay tại nhà",Món nướng,"Bạn đã bao giờ nghe đến món lasagna - một loại mì của nền ẩm thực Ý chưa? Hôm nay hãy để Điện máy XANH vào bếp cùng bạn thử sức thực hiện món ăn độc đáo này với cách làm đơn giản, dễ thực hiện mà lại đúng chuẩn này nhé!",cà chua nghiền đóng hộp | tỏi xay | thịt bò xay | lá mì lasana | trứng | hành tây cắt hạt lựu | sốt cà chua cô đặc tùy loại | phô mai ricotta | phô mai parmesan rắc lên bề mặt | sốt cà chua | dầu ô liu | phô mai mozz...
9,D010,10,857,1,1 - partially related,Rau cuộn đậu phụ,Món chay,"Từng miếng rau cuộn chỉ nhìn thôi cũng thấy hấp dẫn rồi. Đảm bảo khi ăn món này bạn sẽ thích ngay! Món ăn vừa ngọt lại béo ngậy hòa với sốt chua cay rất ngon. Đặc biệt, với món rau cuộn này dù bạn có ăn nhiều ăn no đ...",đường | rượu nấu ăn | cải thảo xanh á | dầu mè | sốt miso | đậu phụ | tỏi băm
10,D011,11,848,1,1 - partially related,Cà tím nhồi đậu phụ,Món chay,"Cà mềm ngọt, được nhồi bên trong là đậu phụ, thêm nấm giòn giòn cảm giác không thể nào quên được",nấm rơm | cà tím | nấm mèo | đậu phụ | cà rốt | hành lá
11,D012,12,5263,1,1 - partially related,Cà tím xào thịt đậu hũ thơm ngon cho bữa cơm tròn vị,Món xào,"Cà tím xào thịt đậu hũ là món xào dân dã, đơn giản nhưng không kém phần thơm ngon, đậm vị, hỗ trợ kích thích vị giác hiệu quả cho bữa cơm thơm ngon hơn. Hôm nay, bạn hãy cùng Điện máy XANH vào bếp nấu ngay món ăn này...",gia vị thông dụng muối/ hạt nêm/ bột ngọt/ đường/ tiêu xay | thịt nạc dăm | cà tím | đậu hũ trắng | dầu ăn | hành tím | tỏi
12,D013,13,6555,0,0 - not relevant,Thịt cừu hầm đậu trắng sốt cà chua của người Kurd cực hấp dẫn,Món kho,"Món thịt cừu hầm đậu trắng sốt cà chua sẽ đem đến gia đình bạn một món lạ miệng, đầy dinh dưỡng cho những ngày cuối tuần hoặc những dịp lễ tết sum vầy bên nhau đấy. Chắc chắn món ăn mới lạ này sẽ khiến bạn say mê và ...",bột nêm gà | dầu ăn | thịt hoặc xương cừu | thìa bột nghệ | rượu trắng | muối | đậu trắng | sốt cà chua đậm đặc tomato paste | hành tây củ hành tây
13,D014,14,7225,2,2 - relevant,Đậu phụ nhồi thịt bằng nồi chiên không dầu độc lạ cực thơm ngon,Món chiên,"Đậu phụ nhồi thịt là một món ăn được yêu thích trong bữa cơm của nhiều gia đình, vậy bạn đã biết cách làm món chiên này bằng nồi chiên không dầu cực kỳ đơn giản chưa? Hôm nay, hãy vào bếp cùng Điện máy XANH để tìm hi...",hành tím băm nhuyễn | dầu ăn | dầu hào | đậu phụ | muỗng cà phê tiêu xay | hạt nêm | thịt heo xay thịt nạc dăm xay nhuyễn
14,D015,15,6148,1,1 - partially related,"Cà tím bung đậu thịt đơn giản, ngon miệng cho bữa cơm gia đình",Món kho,"Cà tím bung đậu thịt là món ăn thơm ngon và đậm vị, với công thức đơn giản và nguyên liệu dễ dàng tìm thấy. Cùng Điện máy XANH vào bếp ngay để tự tay thực hiện món ăn hấp dẫn này, làm phong phú thêm thực đơn cho gia ...",cà tím | dầu ăn | bột nghệ | thịt ba chỉ | hành tím | đậu hũ | gia vị thông dụng muối/đường/hạt nêm | nước mắm | hành lá | cà chua | tỏi
15,D016,16,8729,1,1 - partially related,Đậu phụ sốt bơ đậu phộng ngon bùi béo cho ngày chay ngon miệng,Món chay,"Đậu phụ sốt bơ đậu phộng là món chay có sự kết hợp giữa ẩm thực Thái Lan và Malaysia, có vị bùi béo, thơm ngon đặc trưng cho ngày ngay ngon miệng. Hôm nay, hãy cùng vào bếp ngay với Điện máy XANH để nấu cho gia đình ...",hành boa rô | dầu ăn | muối | ớt băm | dầu màu điều | bơ đậu phộng | gia vị thông dụng đường/ muối | đậu phụ trắng | đậu phộng rang | nước cốt dừa | muỗng cà phê đường | giá đỗ
16,D017,17,7378,2,2 - relevant,Thịt nhồi cà tím chiên sốt cà lạ miệng cực bắt cơm,Món chiên,Cà tím là một loại trái dân dã được chế biến thành nhiều món ăn khác nhau cho bữa cơm gia đình đơn giản đến các bữa tiệc sang trọng. Vào bếp cùng Điện máy XANH để học ngay công thức món chiên đẹp mắt với tên gọi thịt...,cà tím | dầu ăn | muối/ tiêu | bột bắp | muỗng cà phê xì dầu | sốt cà chua | thịt heo xay | tỏi băm | tương cà
17,D018,18,237,0,0 - not relevant,Món trộn hỗn hợp,Món ngon hàng ngày,"Đây là một loại salad cung cấp cả đạm động vật lẫn thực vật, cùng rất nhiều vitamin và nguyên tố vi lượng. Nó hấp dẫn ngay cả với người ngại ăn rau.",đường | ớt chuông đỏ | xà lách | đậu cô ve | muối | đậu phụ bìa | nước cốt chanh vừa đủ | mộc nhĩ tai | trứng gà | cà chua
18,D019,19,6507,2,2 - relevant,"Đậu hũ kho nấm rơm, cà chua mềm thơm cho bữa cơm thêm tròn vị",Món kho,"Bạn cảm thấy chán ngán các món từ thịt và đang muốn tìm cho mình một món ăn dân dã, đậm đà được chế biến từ các nguyên liệu đơn giản và thân thuộc? Mời bạn tham khảo món đậu hũ kho nấm rơm, cà chua mà Điện máy XANH s...",dầu ăn | đậu hũ | nước tương | ớt bột | hạt nêm | nấm rơm | cà chua
19,D020,20,1584,0,0 - not relevant,"Canh mồng tơi đậu hũ chay đơn giản, cho ngày chay thêm hấp dẫn",Món canh,"Vào những ngày ăn chay, bạn thường phải suy nghĩ ra nhiều món ăn để làm phong phú thực đơn phải không? Hôm nay, Điện máy XANH sẽ mách bạn c ách nấu canh mồng tơi đậu hũ chay đơn giản, cho ngày chay thêm hấp dẫn. Cùng...",gia vị thông dụng muối/ bột ngọt/ tiêu | hạt nêm chay | đậu hũ trắng khoảng | rau mồng tơi
20,D021,21,126,3,3 - highly relevant,Đậu phụ nhồi thịt sốt cà chua đơn giản cho bữa cơm hàng ngày,Món ngon hàng ngày,"Đậu phụ vỏ dai, bên trong dồn thịt mềm ngọt, nước sốt cà chua đỏ vàng sóng sánh, vị hài hòa dễ ''bắt cơm'' khi thời tiết chuyển mùa.",hạt tiêu | tai mộc nhĩ | dầu ăn | muối | nấm hương | thịt vai xay | hạt nêm | bìa đậu phụ | cà chua chín | hành lá | hành khô | gia vị: mắm
21,D022,22,5599,1,1 - partially related,Cà tím xào tỏi ớt đậu phụ thơm ngon lạ vị đưa cơm tại nhà,Món xào,Các món xào với cà tím luôn được yêu thích trong bữa cơm gia đình nhờ vào vị ngon và rất đưa cơm. Thế nên hôm nay Điện máy XANH sẽ cùng bạn vào bếp thực hiện món cà tím xào tỏi ớt đậu phụ thơm ngon hấp dẫn với cách l...,á lá lốt | ớt đỏ | dầu ăn | cà tím lớn | đậu phụ trắng | nước mắm | tỏi | muối/ đường
22,D023,23,6008,0,0 - not relevant,Thịt bò xào cà chua đơn giản bắt cơm cho cả nhà,Món xào,"Nếu trong bữa cơm gia đình bạn đã có những món canh , món chiên , và cần một món xào có vị chua chua ngọt ngọt để bữa cơm trọn vị hơn thì món thịt bò xào cà chua là một món ăn thích hợp lắm đấy. Điện máy XANH sẽ hướn...",gia vị thông dụng tiêu xay/ bột ngọt/ hạt nêm/ muối | cà chua | thịt bò | dầu ăn
23,D024,24,5498,1,1 - partially related,"Mì Ý chay sốt cà chua đậu hũ, thơm ngon đơn giản tại nhà",Món xào,"Mì Ý chay sốt cà chua đậu hũ chắc chắn sẽ làm bạn thích mê, dù trong những ngày ăn chay nhưng vẫn có thể giúp bạn cùng cả nhà thưởng thức món mì Ý ngon tuyệt này. Nhanh tay vào bếp thực hiện ngay món chay này nào!",dầu ăn | đậu hũ trắng đậu khuôn | mì ý | hành tím băm | gia vị thông dụng bột ngọt/ đường/ muối/ tiêu xay | hạt nêm chay | củ cà rốt | cà chua
24,D025,25,8558,0,0 - not relevant,"Lagu bò nấu đậu đậm vị, béo bùi cho cả nhà cùng thưởng thức",Món từ bò,"Nếu bạn đang muốn đổi vị cho bữa cơm gia đình thì lagu bò nấu đậu sẽ là một gợi ý cực kỳ lý tưởng vì cực kỳ thơm ngon, hấp dẫn, đậm vị, béo bùi và dễ làm tại nhà. Hãy cùng vào bếp với Điện máy XANH học ngay cách thực...",rượu vang | dầu ăn | hạt đậu hà lan | hành tây | hành tím | nước dừa | khoai tây | thịt bò bắp bò hoặc tùy ý thích | gia vị thông dụng muối/ đường/ hạt nêm/ tiêu xay | cà rốt | sốt cà chua | cà chua | tỏi
25,D026,26,7331,1,1 - partially related,Đậu phụ sốt cay Hàn Quốc cực ngon đậm đà đưa cơm,Món chiên,"Nếu bạn yêu thích các món chiên ngon mang đậm hương vị Hàn Quốc thì hãy cùng theo Điện máy XANH vào bếp , thực hiện ngay món đậu phụ sốt cay Hàn Quốc cực ngon, cực đơn giản ngay sau đây nhé!",đậu phụ trắng đậu hũ trắng | mạch nha | hạt bí | tương ớt hàn quốc | tương cà | bột bắp hoặc bột khoai tây
26,D027,27,175,1,1 - partially related,Canh cà bung thịt đậu dân dã mà bổ dưỡng miền Bắc,Món ngon hàng ngày,"Cà tím mềm ngọt quyện thịt béo ngậy, đậu phụ bùi bùi, nước canh sóng sánh ánh vàng giúp bữa ăn ngày chớm hè trở nên ngon miệng, bổ dưỡng.",mẻ | cà tím | nghệ tươi | dầu ăn | gia vị: nước mắm | mắm tôm | muối | thịt ba chỉ | rau gia vị: tía tô | hạt nêm | bìa đậu phụ | lá lốt | hành lá | hành khô | cà chua | tỏi
27,D028,28,5394,0,0 - not relevant,Nui xào thịt heo viên sốt cà chua đậm đà cho bữa sáng,Món xào,"Nui xào thịt heo viên sốt cà chua là món xào ngon và tiện lợi cho bữa sáng. Với công thức làm nui xào thịt heo đơn giản, hãy cùng vào bếp thực hiện ngay cho gia đình mình món ăn đầy dinh dưỡng này nhé.",muỗng cà phê muối | bột chiên xù | dầu ăn | thịt heo băm | nui | muỗng cà phê tiêu | sốt cà chua | củ hành tây | trứng gà | mùi tây
28,D029,29,839,0,0 - not relevant,"Pate chay nấm, bột đậu chay",Món chay,Mùi nấm thơm lừng béo béo mang đến cảm giác vô cùng lạ miệng và thích thú,bơ đậu phộng | nấm bào ngư | đậu phụ trắng | bột đậu đen
29,D030,30,8664,0,0 - not relevant,Chao đỏ thơm ngon đẹp mắt mà cực đơn giản tại nhà,Món chay,"Món chao là món ăn quen thuộc với những người ăn chay hoặc làm nước chấm của một số món nướng hay món lẩu và ăn kèm với cơm trắng cũng rất ngon. Ngoài chao trắng, người ta vẫn ưa chuộng chao đỏ vì làm bắt mắt món ăn ...",muối | rượu vodka | ớt bột | đậu phụ | ớt tươi băm nhuyễn
30,D031,31,7384,1,1 - partially related,"Đậu phụ thối chiên giòn cực đơn giản, chuẩn vị Đài Loan",Món chiên,"Đậu phụ thối chiên giòn là đặc sản bình dân tại Đài Loan, khách du lịch đến đây thường tìm món này để thưởng thức. Hôm nay, Điện máy XANH sẽ giúp bạn vào bếp để thực hiện món ăn đặc sản này ngay tại nhà nhé.",rượu độ | dầu ăn hoặc mỡ | muối | nước đun sôi để nguội | đậu phụ đậu hũ
31,D032,32,7306,1,1 - partially related,"Đậu phụ viên chiên giòn thơm ngon, đơn giản, hấp dẫn",Món chiên,"Các món ăn từ đậu phụ luôn bổ dưỡng và quen thuộc trong bữa cơm của người Việt. Chỉ với nguyên liệu chính là đậu phụ, ta có thể biến tấu thành những món ăn khác nhau. Hôm nay, Điện máy XANH sẽ hướng dẫn các bạn món đ...",dầu ăn | thìa cà phê tiêu | trứng | thìa cà phê hạt nêm | xúc xích | rau ngò | bột chiên giòn | cà rốt | hành lá | đậu phụ non
32,D033,33,1523,0,0 - not relevant,Canh dưa chua đậu phụ chay thanh mát cho bữa cơm rằm,Món canh,"Canh dưa chua đậu phụ là một món chay thanh mát, đặc biệt vào những bữa cơm rằm. Với công thức đơn giản, bạn hoàn toàn có thể chế biến món ăn này ngay tại nhà. Hãy cùng Điện máy XANH vào bếp để thực hiện ngay món ăn ...",hành boa rô | nấm linh chi trắng | dầu ăn | gia vị thông dụng muối/đường | ớt sừng | rau om | á ngò gai | đậu phụ | cà chua chín | nước mắm chay | hạt nêm chay | dưa cải muối chua
33,D034,34,7501,0,0 - not relevant,"Xíu mại viên sốt cà chua mềm ngon, đậm đà chuẩn như ngoài hàng",Món hấp,"Những viên xíu mại chiên béo thơm, thấm vị cùng sốt cà chua đậm đà, ăn kèm bánh mì cho bữa sáng đầy đủ dinh dưỡng. Các bạn hãy cùng vào bếp với Điện máy XANH đổi vị cho gia đình bằng món xíu mại viên sốt cà chua nhé!",bánh mì dùng ăn kèm và để bóp vụn trộn thịt | dầu ăn | hành tây | hành tím | củ đậu | hành lá | thịt heo xay | gia vị thông dụng muối/ hạt nêm/ tiêu xay/ đường/ bột ngọt | cà chua | ngò rí
34,D035,35,7448,2,2 - relevant,Cà chua nhồi thịt bằng nồi chiên không dầu ngon khó cưỡng,Món chiên,"Cà chua là một loại thực phẩm không những giàu chất dinh dưỡng mà còn chế biến được rất nhiều món. Hôm nay, Điện máy XANH sẽ hướng dẫn bạn làm món cà chua nhồi thịt bằng nồi chiên không dầu cực kỳ đơn giản. Mời bạn v...",phô mai bào | dầu ăn | giò sống | muỗng cà phê bột nêm rau củ | hành tím băm | tiêu xay | lá basil khô | muỗng cà phê đường | thịt heo xay | cà chua | muỗng cà phê dầu hào
35,D036,36,6828,1,1 - partially related,Đậu phụ - đậu hũ chiên trứng muối lạ miệng thơm ngon cho cả nhà,Món chiên,"Đậu phụ chiên trứng muối là món chiên được chế biến vừa đơn giản vừa thơm ngon, lạ miệng và khi ăn kích thích vị giác vô cùng. Hôm nay, bạn hãy cùng với Điện máy XANH vào bếp để thực hiện ngay món đậu phụ chiên trứng...",dầu ăn | hành tím | sữa tươi không đường | lòng đỏ trứng muối hấp chín | đậu phụ đậu hũ trắng | muỗng cà phê hạt nêm
36,D037,37,5521,0,0 - not relevant,Mì udon xào trứng cà chua đơn giản cho bữa ăn thêm ngon,Món xào,"Quá bận rộn nhưng vẫn muốn ăn ngon, ăn khỏe? Thử ngay mì udon xào trứng cà chua siêu ngon, lại đơn giản cho bữa ăn thêm hấp dẫn. Hãy cùng Điện máy XANH vào bếp để thực hiện ngay nhé!",dầu ăn | mì udon có thể chọn mì tươi hoặc khô | ngò tây parsley | hành boa rô vừa | nước lọc | ớt bột | cà chua chín | sốt cà chua khoảng cơm | muối/ tiêu | trứng gà | tôm
37,D038,38,5905,1,1 - partially related,Đậu hũ xào giá hẹ chay thơm ngon dễ làm cho bữa cơm thêm thanh vị,Món xào,"Bạn đã ngán những món thịt cá hoặc dầu mỡ quá nhiều, cần món ăn thanh đạm cho bữa cơm hằng ngày. Hôm nay, Điện máy XANH sẽ mách bạn công thức làm món đậu hũ xào giá hẹ chay thơm ngon dễ làm. Cùng vào bếp thực hiện ng...",dầu ăn | giá | muỗng cà phê bột ngọt/ muối | đậu hũ trắng khoảng | hẹ | muỗng cà phê hạt nêm chay
38,D039,39,6999,0,0 - not relevant,Đậu phụ từ sữa đậu nành nhanh gọn đơn giản tại nhà,Món chiên,"Đậu phụ làm từ sữa đậu nành nhanh gọn, đơn giản nhưng không kém phần thơm ngon, hấp dẫn. Món hấp này có lớp vỏ ngoài vàng giòn cùng với độ mềm mịn, béo ngậy bên trong thì chắc chắn sẽ đem đến cho bạn một trải nghiệm ...",muỗng cà phê muối | sữa đậu nành ít đường | dầu ăn | bột bắp | trứng gà
39,D040,40,5894,1,1 - partially related,Đậu phụ xào trứng béo mềm thơm ngon khó cưỡng,Món xào,"Đậu phụ xào trứng là món xào có sự kết hợp giữa ẩm thực Hàn Quốc và Trung Hoa, có vị bùi béo, thơm ngon đặc trưng lại vô cùng ngon miệng. Hôm nay, hãy cùng vào bếp ngay với Điện máy XANH để nấu cho gia đình cùng thưở...",mè | hành boa rô | dầu ăn | nấm hương | nước lọc | nước tương | dầu hào | đậu phụ | muỗng canh tương ớt | gia vị thông dụng đường/ muối/ tiêu xay | hành lá | thịt heo xay | trứng gà | tỏi | muỗng cà phê bột năng
40,D041,41,5539,0,0 - not relevant,Đậu bắp xào cà chua chay thanh đạm hương sắc bắt mắt,Món xào,"Một món xào thanh đạm, có màu sắc xanh đỏ cực bắt mắt thu hút người ăn ngay từ cái nhìn đầu tiên không món nào khác đó là đậu bắp xào cà chua. Cách làm đơn giản lắm đấy để Điện máy XANH hướng dẫn cho bạn nhé. Vào bếp...",dầu ăn | đậu bắp | gia vị thông dụng tiêu/ muối/ bột ngọt | hạt nêm chay | cà chua
41,D042,42,6331,1,1 - partially related,"Đậu hũ kho tiêu thơm ngon, bắt vị cho bữa cơm",Món kho,"Đậu hũ kho tiêu là món kho thơm ngon, thấm vị và kết hợp với mùi thơm cay nồng đặc trưng của tiêu xay rất hấp dẫn. Ngoài ra nó còn được sử dụng là món chay kích thích vị giác rất tốt, cùng chị Kim Minh vào bếp và thê...",dầu ăn | nước tương | đậu hũ chiên | muỗng cà phê hạt nêm chay | tỏi | gia vị thông dụng đường/ bột ngọt/ tiêu xay
42,D043,43,1233,0,0 - not relevant,Mì ý thịt bằm xúc xích sốt cà chua,Món chính,"Hôm nay, chúng ta thực hiện món mang phong cách châu Âu nhưng đã được Việt hóa một tý. Món mì ý thịt bằm, xúc xích sốt cà chua.",mì ý ói | sốt cà chua ói | xúc xích | tỏi băm | cà chua | thịt heo bằm
43,D044,44,8741,2,2 - relevant,Cách làm nấm hương nhồi đậu hũ sốt cà thơm ngon khó cưỡng vào ngày rằm,Món chay,Nấm hương nhồi đậu hũ sốt cà là món chay vô cùng đơn giản thực hiện với những nguyên liệu dễ tìm và rất bắt cơm. Hãy để Điện máy XANH mách bạn cách nấu món ăn ngon tuyệt này tại nhà nhé! Cùng Vào bếp thôi nào!,chả chay băm | tương cà nước sốt | nấm tai mèo | hạt nêm nước sốt | dầu ăn nước sốt | nấm hương | hộp đậu hũ ta | đường nước sốt | hành boaro nước sốt | muỗng cà phê tiêu | dầu mè nước sốt | bột năng | cà chua băm nh...
44,D045,45,5655,0,0 - not relevant,Chả cá sốt cà chua đơn giản đậm đà cho bữa cơm nhà thêm thú vị,Món xào,"Chả cá sốt cà chua được làm từ những nguyên liệu tuy đơn giản nhưng chúng lại phù hợp với nhau kì lạ. Chả cá dai dai, kết hợp với sốt cà chua sẽ trở nên mềm và đậm đà hơn, cực hấp dẫn và ngon cơm. Hôm nay, cùng vào b...",dầu ăn | hành tím | chả cá | nước mắm | đường/ hạt nêm | hành lá | ớt | cà chua
45,D046,46,5256,2,2 - relevant,"Đậu hũ xào thịt sốt cà chua đơn giản hao cơm, thơm ngon hấp dẫn",Món xào,"Đậu hũ là món ăn chứa rất nhiều dinh dưỡng và được chọn nhiều trong các bữa cơm gia đình. Hôm nay, chuyên mục vào bếp của Điện máy XANH sẽ mách bạn một công thức cực đơn giản để làm món đậu hũ xào thịt sốt cà chua. N...",đậu hũ chiên sẵn | hành lá | gia vị thông dụng muối/đường/hạt nêm/tiêu xay | thịt heo | hành tím băm | muỗng canh dầu ăn | tỏi băm | cà chua | ngò rí
46,D047,47,864,1,1 - partially related,Đậu hũ sốt chua ngọt,Món chay,"Đậu hũ là món ăn ngon bùi, vừa rẻ, vừa dễ làm và đặc biệt là mất rất ít thời gian để chế biến nên nhiều người rất thích món này. Cùng vào bếp để chế biến món đậu hũ sốt chua ngọt này cùng mình nhé!",nước tương cafe | đậu hũ trắng | dầu ăn | bột bắp cafe | đường trắng cafe | hành lá | sốt cà chua

========================================================================================================================
query_id: 214
query_text: Bánh sinh nhật rau câu trái cây dễ làm, không cần máy đánh trứng
relevance distribution: {0: np.int64(3), 1: np.int64(45), 3: np.int64(2)}

,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description,normalized_ingredients
0,D001,1,3250,1,1 - partially related,Bánh thạch dâu tây sữa chua thơm ngon đơn giản ai ai cũng ghiền,Món bánh,"Thạch rau câu là một trong những món tráng miệng yêu thích của trẻ nhỏ lẫn người lớn. Dưới đây, cùng vào bếp với Điện máy XANH thực hiện cách làm bánh thạch dâu tây sữa chua tươi mát, giàu vitamin đảm bảo ai ai cũng ...",đường | dâu tây | bột rau câu agar | phô mai | sữa chua | đường đen hoặc bột cacao/cà phê
1,D002,2,3021,3,3 - highly relevant,"Bánh sinh nhật rau câu trái cây dễ làm, không cần máy đánh trứng",Món bánh,"Bạn muốn tự tay làm một chiếc bánh sinh nhật độc đáo, mát lạnh và tốt cho sức khỏe mà không cần đến lò nướng hay máy đánh trứng phức tạp? Bánh sinh nhật rau câu trái cây chính là lựa chọn lý tưởng. Trong bài viết dướ...",thanh long ruột trắng | đường | nước cốt chanh | cream cheese kem phô mai | bơ nhạt | thanh long ruột đỏ | sữa chua không đường | bánh quy bơ | tinh chất vani | bột gelatin | heavy cream kem sữa béo
2,D003,3,679,0,0 - not relevant,Làm bánh lòng trắng trứng béo xốp không cần bột,"Món tráng miệng, giải khát","Chỉ cần 3 lòng trắng trứng gà và một muỗng đường, bạn có ngay chiếc bánh nướng thơm, vừa béo vừa xốp.",trứng gà:
3,D004,4,8859,1,1 - partially related,Rau câu trái cây thơm ngon thanh mát cho cả nhà,Ăn vặt,"Rau câu trái cây là món tráng miệng thơm ngon, thích hợp giải nhiệt ngày nắng nóng. Hôm nay, bạn hãy cùng chị Ngọc Hiền vào bếp thực hiện ngay món rau câu thanh mát, chuẩn vị này cho cả nhà cùng thưởng thức sau mỗi b...",đường | xoài chín cỡ vừa | bột rau câu dẻo | nước lọc | thanh long cỡ vừa
4,D005,5,9951,1,1 - partially related,"Thạch dưa lưới lạ vị, thơm mát, giải nhiệt",Món tráng miệng,"Đến mùa dưa lưới rồi, bạn đã nghĩ ra món tráng miệng nào được làm ra từ loại quả thanh mát này chưa? Hôm nay, Điện máy XANH sẽ mách bạn cách làm thạch dưa lưới lạ vị, thơm mát, giải nhiệt. Cùng vào bếp thực hiện ngay...",đường | bột rau câu dẻo | dưa lưới khoảng
5,D006,6,9992,1,1 - partially related,"Rau câu sữa milo nhanh chóng, ngon cực đỉnh chỉ với 10 phút",Món tráng miệng,"Chớ vội lầm tưởng sữa milo chỉ có thể là món thức uống bổ dưỡng mà thôi, đó là do bạn chưa biết đến món rau câu sữa milo hấp dẫn, thanh mát, hạ nhiệt vào các ngày nắng nóng cực hiệu quả. Nào hãy cùng chị Ngọc Hiền và...",đường | nước | sữa milo hộp | bột rau câu giòn
6,D007,7,9969,1,1 - partially related,Món trứng pha lê độc lạ bắt mắt cho bữa tráng miệng,Món tráng miệng,"Rau câu hình trái trứng trong veo, đẹp mắt cùng với hương vị thơm ngon sẽ làm cho bữa cơm gia đình bạn thú vị hơn rất nhiều. Hãy cùng vào bếp ngay với Điện máy XANH làm trứng pha lê - món tráng miệng vô cùng độc đáo,...",ói bột rau câu | gia vị thông dụng muối/ đường/ hạt nêm | hành lá | trứng gà | bông cải trắng | tôm tươi
7,D008,8,8954,1,1 - partially related,"Rau câu sợi giòn thơm béo, giòn sựt sựt lạ miệng với nồi inox",Ăn vặt,"Với hương vị ngọt thanh, giòn sựt sựt và chút béo thơm, rau câu sợi giòn là món tráng miệng vừa ngon miệng vừa đẹp mắt, thích hợp cho cả gia đình thưởng thức. Chỉ cần một chiếc nồi inox và vài nguyên liệu đơn giản, b...",đường | sữa đặc | bột rau câu giòn agar | ói cafe đen | rau câu sợi | nước cốt lá dứa xay từ lá dứa tươi và nước | nước cốt dừa
8,D009,9,9187,1,1 - partially related,Rau câu thanh long ruột đỏ đẹp mắt bằng máy xay sinh tố,Ăn vặt,"Mùa nắng nóng đã bắt đầu với nền nhiệt ngày càng cao. Để chăm sóc sức khoẻ, bạn hãy thử chế biến những món có công dụng giải nhiệt. Trong số đó, đừng quên món ăn vặt quen thuộc rau câu thanh long. Vào bếp trổ tài để ...",thanh long ruột đỏ | đường | nước | bột rau câu giòn
9,D010,10,3221,1,1 - partially related,Rau câu 4D hoa nổi hương bắp thơm ngon đẹp mắt đơn giản tại nhà,Món bánh,Rau câu là một món tráng miệng quen thuộc với mọi người. Hãy cùng vào bếp làm ngay món rau câu 4D hoa nổi vừa thơm ngon lại vừa đẹp mắt cho gia đình mình nhé!,sữa tươi | đường | củ dền nguyên liệu tạo màu | bột rau câu giòn bột rau câu agar | whipping cream | cái á dứa | cà rốt nguyên liệu tạo màu | hạt g bắp
10,D011,11,1982,1,1 - partially related,Bánh sinh nhật kem tươi tại nhà đơn giản bằng máy đánh trứng,Món bánh,"Bạn đang muốn làm một chiếc bánh sinh nhật kem tươi thơm ngon, mềm mịn và đẹp mắt cho dịp đặc biệt? Với công thức đơn giản nhưng cực kỳ chi tiết, Vào bếp sẽ giúp bạn hoàn thành món bánh này để gửi tặng người thân yêu.",whipping cream để lạnh | đường | bột mì số | đường xay | dầu ăn | muối | vani tùy chọn | sữa tươi không đường | trứng gà nhiệt độ phòng | trái tươi ít xoài/dâu tây/nho/kiwi/việt quất | thìa cà phê vani tùy chọn
11,D012,12,9293,1,1 - partially related,Bánh Trung thu rau câu nhân xoài đẹp mắt thơm ngon,Ngày lễ Tết,"Bánh Trung thu rau câu nhân xoài được hòa trộn bởi nhiều màu sắc nhìn rất đẹp mắt. Không những vừa giòn dẻo, món bánh lại còn có hương vị chua ngọt cực kỳ thơm ngon và không có cảm giác ngán khi ăn. Cùng Điện máy XAN...",mirinda vị soda kem lon | xoài | đường | siro dâu | muỗng canh bột rau câu dẻo | bột rau câu giòn
12,D013,13,612,1,1 - partially related,Rau câu trái cây,Quà - Món ăn vặt,Rau câu trái cây là món ăn bổ dưỡng và mát nhờ được kết hợp với các loại quả thập cẩm. Món ăn dùng lạnh sẽ ngon miệng hơn.,đường | các loại trái cây: kiwi | cam | rau câu | dâu | trái thanh long | nước | ống vani
13,D014,14,9224,1,1 - partially related,Thạch rau câu sợi mì giòn sừn sựt thanh mát cho trẻ,Ăn vặt,"Thạch rau câu sợi mì mát mạnh có nước dùng ngọt béo, chua chua ăn cùng sợi mì giòn dai tạo nên một món ăn vặt cực kỳ hấp dẫn và thơm ngon. Hãy vào bếp cùng Điện máy XANH để thay đổi màu sắc cho món rau câu thường ngà...",siro cam/ việt quất/sâm dứa/dâu | đường | bột rau câu dẻo | sữa đặc
14,D015,15,8625,0,0 - not relevant,Tai heo ngâm chua ngọt chay cho ngày Tết chay thêm vị,Món chay,"Những ngày Tết này, bạn hãy thử trổ tài làm món tai heo ngâm chua ngọt chay để ăn kèm với bánh chưng, giò chả chống ngán cho cả gia đình nhé. Hãy cùng vào bếp với Điện máy XANH để trổ tài nấu nướng với công thức chay...",đường | muối | bột rau câu dẻo | rau câu sợi | giấm chua | củ cà rốt | nấm mèo trắng khô | ớt | nước | tỏi | bột rau câu giòn
15,D016,16,9872,1,1 - partially related,Thạch dừa viên bi thơm ngon đẹp mắt giòn dai dễ làm tại nhà,Trà sữa,Món thạch dừa viên bi với sự kết hợp hài hòa giữa rau câu cùng với nước dừa tươi đem lại cảm giác ngon miệng và hấp dẫn cùng với hình dáng vô cùng bắt mắt. Cùng Điện máy XANH vào bếp nhé!,bột rau câu giòn bột agar | đường tùy khẩu vị | nước dừa tươi | bột rau câu dẻo bột jelly
16,D017,17,8980,1,1 - partially related,"Thạch rau câu viên bi hoa quả (trái cây) trong suốt, hấp dẫn",Ăn vặt,"Thạch rau câu viên bi hoa quả với hình dáng xinh xắn, đẹp mắt cùng với hương vị giòn ngon, chua ngọt vô cùng hấp dẫn. Đảm bảo đây sẽ là một món ăn ngon, chinh phục được mọi lứa tuổi. Hãy vào bếp với Điện máy XANH và ...",mâm xôi | việt quất | bột rau câu dẻo | cam | bưởi quả | nhãn chùm | xoài chín | nước
17,D018,18,9057,1,1 - partially related,Rau câu khoai lang tím sữa dừa thơm béo núng nính dễ làm tại nhà,Ăn vặt,Sau bữa cơm gia đình mà mọi người cùng nhau ngồi lại ăn món tráng miệng với miếng rau câu khoai lang tím sữa thơm béo thì còn gì bằng. Nhanh tay cùng vào bếp với Điện máy XANH thực hiện để chiêu đãi cả nhà thôi nào!,đường | khoai lang tím | sữa đặc | ói rau câu giòn | kem béo
18,D019,19,8799,1,1 - partially related,Thạch trái cây trong suốt thơm ngon cho ngày hè,Ăn vặt,"Thạch viên bi trái cây không chỉ có màu sắc bắt mắt, mùi vị thơm ngon mà còn giúp bạn bổ sung các loại vitamin cần thiết cho cơ thể. Cùng vào bếp với Điện máy XANH làm ngay món thạch trái cây ngon ngất ngây này nhé!",bột rau câu giòn bột agar | trái cây tùy thích dâu/cam/kiwi/nho | đường tuỳ khẩu vị | lá dứa | bột rau câu dẻo bột jelly | nước lọc | vani không bắt buộc
19,D020,20,2481,1,1 - partially related,"Bánh Trung Thu rau câu phô mai kiwi lạ miệng, đẹp mắt, cực ngon",Món bánh,"Mùa Trung Thu tới rồi, ngoài những hương vị bánh trung thu truyền thống, món bánh trung thu rau câu cũng đang được quan tâm. Cùng Điện máy XANH vào bếp thực hiện cách làm bánh Trung Thu rau câu phô mai kiwi với hương...",sữa tươi không đường hoặc có đường tùy thích | kiwi | đường trắng | phô mai | cà rốt | bột rau câu giòn
20,D021,21,2654,1,1 - partially related,Bánh trung thu nhân trái cây ngon ngất ngây không cần lò nướng,Món bánh,"Lại một mùa Trung Thu nữa sắp về, chẳng cần đến lò nướng bạn vẫn có thể làm những chiếc bánh Trung Thu nhân trái cây cực thơm ngon và đơn giản để chiêu đãi cả gia đình mình. Cùng vào bếp với Điện máy XANH để khám phá...",mứt cam | đường | mứt dâu | dầu ăn | bánh mì sandwich bỏ hết rìa | bột làm bánh cake flour có thể thay bằng bột mì đa dụng | dâu tây xay mịn | bột gạo tẻ | xoài xay mịn | bột gạo nếp
21,D022,22,10007,1,1 - partially related,"Rau câu trứng vân mây hoa đậu biếc đẹp mắt, vô cùng đơn giản",Món tráng miệng,Bạn đã nghe đến tên rau câu trứng vân mây bao giờ chưa ? Hãy cùng vào bếp với Điện máy XANH để tìm hiểu ngay món tráng miệng với cái tên vô cùng độc đáo nhưng lại cực kì dễ làm đễ cùng chiêu đãi cho gia đình bạn nhé!,đường | hoa nhài tươi hoặc tinh dầu hoa nhài | nước sôi | hoa đậu biếc | bột rau câu dẻo | nước lọc | nước cốt dừa | trứng gà | bột rau câu giòn
22,D023,23,3073,3,3 - highly relevant,Bánh sinh nhật rau câu đẹp mắt tặng người thân vào dịp đặc biệt,Món bánh,"Sắp đến ngày sinh nhật của một ai đó hay ngày lễ đặc biệt, nhưng bạn lại không quá khéo tay cũng như không có lò nướng để làm bánh? Không sao, vì bạn hoàn toàn có thể tham khảo cho mình món bánh sinh nhật rau câu đẹp...",đường | thanh long ruột đỏ | bột rau câu dẻo | màu hồng/ màu xanh thực phẩm | chanh dây | quả dưa lưới | nước cốt dừa | xoài chín | sữa tươi có đường | nhãn | bó lá dứa | nước | bột rau câu giòn
23,D024,24,8754,0,0 - not relevant,"Trứng vịt, trứng gà luộc chay thơm béo siêu đơn giản",Món chay,"Trứng luộc chay thơm béo, bùi bùi lại vô cùng đẹp mắt. Hãy cùng vào bếp và chế biến món chay ngon này cho gia đình mình ngay hôm nay nhé!",muỗng canh bột rau câu giòn agar | sữa tươi không đường | đậu xanh bỏ vỏ
24,D025,25,9161,1,1 - partially related,"Rau câu sữa bắp thơm ngon, dinh dưỡng cực đơn giản tại nhà",Ăn vặt,"Rau câu sữa bắp là món tráng miệng thơm ngon, dinh dưỡng, chỉ với các bước thực hiện đơn giản, đảm bảo sẽ thành công luôn đó. Hôm nay cùng vào bếp với chị Ngọc Hiền và Điện máy XANH để làm ngay món ăn hấp dẫn này nha...",đường | bột rau câu dẻo | nước lọc | bắp mỹ ngô ngọt | sữa tươi có đường
25,D026,26,2580,1,1 - partially related,"Bánh đậu xanh trái cây đẹp, độc lạ, thơm ngon đơn giản",Món bánh,Bánh đậu xanh trái cây là món ăn vặt rất quen thuộc với tuổi thơ của nhiều người. Món bánh có ngoại hình đẹp mắt và ngộ nghĩnh này hoàn toàn có thể thực hiện tại nhà. Cùng bài viết vào bếp dưới đây tham khảo cách thự...,muỗng cà phê muối | đậu xanh không vỏ | màu thực phẩm | đường thốt nốt | bột rau câu | nước cốt dừa
26,D027,27,10003,1,1 - partially related,Thạch rau câu Sting đẹp mắt ăn mát lạnh siêu thích,Món tráng miệng,"Thay vì uống nước Sting như thông thường, bạn có thể biến tấu nguyên liệu này thành một món tráng miệng thơm ngon cho cả nhà đổi vị. Với công thức đơn giản, đảm bảo sẽ thực hiện thành công, cùng Điện máy XANH vào bếp...",đường phèn | ói bột rau câu dẻo | sting dâu chai
27,D028,28,9959,1,1 - partially related,"Rau câu viên bi dừa hoa đậu biếc và hạt é đẹp mắt, ăn là ghiền",Món tráng miệng,"Rau câu là món ăn vặt vô cùng quen thuộc với mọi nhà, nhưng không phải ai cũng biết cách làm rau câu sao cho mới lạ và đặc biệt. Hôm nay hãy cùng với Điện máy XANH vào bếp , xem ngay cách làm rau câu viên bi dừa hoa ...",á lá dứa | muối | hạt é | sữa tươi không đường | nước lọc | sữa đặc | bột rau câu dẻo | bột rau câu agar | đường trắng | nước cốt dừa | hoa đậu biếc khoảng hoa khô | nước dừa tươi
28,D029,29,9976,1,1 - partially related,Rau câu sữa đặc giòn thơm béo bùi cực đơn giản tại nhà,Món tráng miệng,"Nếu bạn là một người yêu thích các món tráng miệng vừa mát lạnh, vừa thơm béo thì có thể học ngay cách làm rau câu sữa đặc cùng Điện máy XANH nhé! Hãy cùng vào bếp thực hiện món ăn hấp dẫn nhưng cách chế biến vô cùng...",đường | sữa đặc lon | nước lọc | bột rau câu giòn
29,D030,30,2738,1,1 - partially related,Bánh bông lan lá dứa nhiều lớp không cần lò nướng hấp dẫn dễ làm,Món bánh,"Bánh bông lan lá dứa có màu xanh mát mắt, hương thơm nức mũi cùng cốt bánh nhiều lớp bùi ngọt, béo ngậy. Món bánh này không cần dùng đến lò nướng nhưng vẫn có thể thực hiện thành công! Hãy cùng Điện máy XANH vào bếp ...",đường | á lá dứa | tinh bột đậu xanh | muối | bột sữa | bột bắp | bột rau câu dẻo | bột mì đa dụng bột mì số | nước cốt dừa | trứng gà
30,D031,31,2309,1,1 - partially related,Bánh flan gato sinh nhật tại nhà có thể không dùng lò nướng,Món bánh,"Bánh flan gato sinh nhật là sự kết hợp độc đáo giữa lớp flan mềm mịn, béo ngậy và cốt bánh bông lan nhẹ nhàng, tạo nên món tráng miệng vừa lạ miệng vừa hấp dẫn. Chỉ với một vài nguyên liệu cơ bản và cách hấp đơn giản...",dầu ăn | trứng | bột mì đa dụng | bột bắp | baking power bột nổi | sữa tươi không đường | tinh chất vani | đồ trang trí bánh dâu tây/ cam/ việt quất/ bánh quế/ kem tươi dạng xịt/ hạt hạnh nhân/ nước đường/ siro | muố...
31,D032,32,2482,1,1 - partially related,Bánh trung thu rau câu sầu riêng lạ miệng dễ làm tại nhà,Món bánh,"Mùa trung thu tới rồi, ngoài những hương vị bánh trung thu truyền thống, bánh trung thu rau câu cũng đang được quan tâm. Cùng Điện máy XANH vào bếp thực hiện cách làm bánh trung thu rau câu nhân sâu riêng, thêm một h...",đường | bột agar bột rau câu giòn | thịt sầu riêng | bột rau câu | cà phê | bột gấc
32,D033,33,10010,1,1 - partially related,"Rau câu trà sữa giòn ngon hấp dẫn, ăn là mê",Món tráng miệng,"Bạn đã từng nếm thử trà sữa phiên bản rau câu giòn sần sật chưa? Nếu chưa, hãy cùng tham khảo ngay món rau câu trà sữa mà Điện máy XANH giới thiệu sau đây nhé. Từng lớp rau câu ngọt thơm, béo ngậy chắc chắn sẽ khiến ...",đường phèn | trà thái đỏ hoặc hồng trà | sữa tươi không đường | nước cốt dừa | bột rau câu giòn
33,D034,34,9039,1,1 - partially related,Rau câu nhãn đậu biếc đẹp lung linh dễ làm,Ăn vặt,Rau câu là một món tráng miệng được rất nhiều người ưa chuộng. Nằm bên trong lớp rau câu xanh mát là từng quả nhãn trắng tròn xinh xinh trông thật đẹp mắt phải không nào? Hôm nay mời bạn vào bếp để cùng làm món tráng...,đường | hoa đậu biếc khô | muối | lá dứa | bột rau câu agar | nước cốt dừa | nhãn tách hạt
34,D035,35,2261,1,1 - partially related,"Bánh trung thu rau câu nhân trà xanh ngọt mát, ngon thơm, lạ miệng",Món bánh,"Bánh trung thu rau câu nhân trà xanh ngọt thơm quyện cùng vị đắng nhẹ đặc trưng của trà xanh. Tất cả tạo nên một món bánh hấp dẫn, ăn không có cảm giác ngán. Cùng Điện máy XANH vào bếp thực hiện nhé!",dừa nạo | đường phèn | sữa tươi không đường | sữa đặc | bột trà xanh | bột rau câu giòn
35,D036,36,3222,1,1 - partially related,"Bánh trung thu rau câu nhân đậu xanh thơm ngon, đẹp mắt",Món bánh,"Bánh trung thu rau câu nhân đậu xanh là sự kết hợp mới lạ giữa lớp vỏ ngoài giòn sần sật cùng phần nhân đậu ngọt thơm, lôi cuốn. Nếu bạn muốn chiêu đãi gia đình món bánh hấp dẫn này thì hãy vào bếp cùng Điện máy XANH...",muỗng cà phê muối | bột rau câu jelly ói | nước cốt thanh long | dầu ăn | rượu trắng | nước hoa đậu biếc | bột bánh dẻo | bột rau câu agar ói | đậu xanh | dầu mè | nước cốt cacao | trứng muối | đường cát cho vỏ bánh...
36,D037,37,9998,1,1 - partially related,Thạch rau câu sữa chua đơn giản chỉ mất 10 phút ngay tại nhà,Món tráng miệng,"Rau câu sữa chua là món tráng miệng độc đáo, lạ miệng. Có thể bạn chưa biết, nhưng món ăn này thật sự thơm ngon, kích thích vị giác và cũng thích hợp làm món ăn vặt đó nha. Hôm nay, cùng Điện máy XANH bắt tay vào bếp...",hộp sữa chua có đường | bột rau câu dẻo | milo hoặc bột cacao | sữa đặc
37,D038,38,9915,1,1 - partially related,Rau câu bơ độc lạ thơm ngon giải nhiệt mùa hè cực đơn giản,Món tráng miệng,"Rau câu là món tráng miệng hấp dẫn, rất phù hợp với những ngày thời tiết nóng bức mùa hè. Ngày nay, rau câu được các chị em biến tấu rất độc đáo. Nhân đây, hãy cùng vào bếp với Điện máy XANH khám phá ngay cách làm ra...",bơ | đường | ói bột rau câu dừa
38,D039,39,3765,1,1 - partially related,"Thạch rau câu trứng gà luộc đẹp mắt, đơn giản dễ làm",Món bánh,"Thạch rau câu luôn là món ăn vặt rất dễ làm và thưởng thức, vừa giúp giải khát vào những ngày thời tiết nóng, vừa chứa nhiều dưỡng chất. Hôm nay, cùng theo chân vào bếp thử làm ngay món bánh thạch rau câu trứng gà lu...",đậu xanh đã bóc vỏ | đường | bột rau câu | sữa đặc | vỏ trứng gà
39,D040,40,9231,1,1 - partially related,Rau câu sữa tươi giòn ngon chỉ với các nguyên liệu cực đơn giản,Ăn vặt,"Rau câu sữa tươi với vị ngọt thơm tươi mát, là món tráng miệng rất đáng để bạn chiêu đãi cho cả nhà sau mỗi bữa ăn vào các ngày nắng nóng. Đặc biệt, món ăn vô cùng hấp dẫn này lại có cách thực hiện rất đơn giản, theo...",đường | sữa tươi có đường bịch | nước | bột rau câu giòn
40,D041,41,9973,1,1 - partially related,Rau câu flan cà phê siêu ngon ai cũng có thể làm,Món tráng miệng,Đã bao giờ bạn nghĩ khi kết hợp 2 món tráng miệng cực hot là bánh flan và rau câu cà phê lại với nhau thì hương vị sẽ như thế nào? Cùng vào bếp với Điện máy XANH làm ngay món tráng miệng cực hấp dẫn này nhé!,lòng đỏ trứng gà | sữa đặc có đường | kem tươi whipping cream không bắt buộc | sữa tươi không đường hoặc nước cốt dừa tuỳ theo sở thích | nước nếu muốn ăn rau câu cứng hơn thì có thể làm ít nước lại | vani nước | ói ...
41,D042,42,3421,1,1 - partially related,Đổi gió với bánh trung thu rau câu vị dâu nhân trứng muối,Món bánh,Nếu như bạn đã quá ngán với những chiếc bánh trung thu truyền thốnghì hãy đổi vị với chiếc bánh trung thu rau câu có vỏ ngoài mát lạnh kèm theo hương vị đặc trưng thơm ngon. Không cần lò nướng mà vẫn có chiếc bánh Tr...,muỗng cà phê muối | đường | mứt dâu | lá dứa | bột rau câu | nước cốt dừa | cà rốt nhỏ | nước
42,D043,43,9942,1,1 - partially related,"Thạch rau câu sâm bổ lượng thanh mát, bổ dưỡng giải nhiệt cơ thể",Món tráng miệng,Nhắc đến sâm bổ lượng chắc chắn bạn sẽ thoáng nghĩ ngay đến món chè . Nhưng hôm nay hãy để Điện máy XANH đem đến cho mọi người một món tráng miệng đầy mới lạ nhưng không kém phần hấp dẫn đó là thạch rau câu sâm bổ lư...,muỗng cà phê muối | đường phèn | whipping cream | táo tàu | sữa đặc có đường | sữa tươi không đường | kỷ tử | phổ tai | bột rau câu dẻo ói | nhãn nhục | bột rau câu giòn
43,D044,44,664,1,1 - partially related,Rau câu chanh dây,"Món tráng miệng, giải khát","Từ quả chanh dây với mùi thơm quyến rũ và vị chua thanh, chúng ta có thể chế biến được nhiều món ngon, trong đó, rau câu chanh dây rất lý tưởng trong dịp hè này.",chanh dây | đường | bột rau câu
44,D045,45,10018,1,1 - partially related,Honey Jelly hot trend tiktok siêu dễ làm tại nhà,Món tráng miệng,"Mật ong được biết đến như một thực phẩm có giá trị dinh dưỡng cao và mang lại nhiều lợi ích cho sức khỏe. Vậy nên hôm nay, Điện máy xanh giới thiệu đến bạn món honey jelly (thạch mật ong) thanh mát - một món tráng mi...",mật ong | nước | bột rau câu
45,D046,46,9958,1,1 - partially related,"Rau câu xoài 3 tầng đẹp mắt, món tráng miệng cực ngon",Món tráng miệng,"Những ngày nắng nóng, món rau câu là món tráng miệng rất được yêu thích bởi hương vị giòn giòn, ngọt béo, mà lại còn dễ thực hiện ngay tại căn bếp nhà mình. Hôm nay hãy để Điện máy XANH đem đến cho các bạn cách làm r...",đường | bột rau câu rau câu giòn | sữa đặc lon | ống tinh chất vani | xoài | bông hoa đậu biếc khô | trái chanh

## 5. Targeted Spot Checks by Relevance Level

Random query inspection is useful, but it can miss edge cases. This section samples individual `(query, document)` pairs from each relevance level so we can quickly inspect whether labels `0`, `1`, `2`, and `3` feel calibrated.

In [5]:
TARGETED_SAMPLES_PER_RELEVANCE_LEVEL = 8

targeted_rows = []
for relevance_level in [3, 2, 1, 0]:
    level_rows = inspection_dataframe[inspection_dataframe["relevance"] == relevance_level]
    sample_size = min(TARGETED_SAMPLES_PER_RELEVANCE_LEVEL, len(level_rows))
    if sample_size == 0:
        continue
    targeted_rows.append(
        level_rows.sample(
            n=sample_size,
            random_state=RANDOM_SEED + relevance_level,
        )
    )

targeted_inspection_dataframe = (
    pd.concat(targeted_rows, ignore_index=True)
    .sort_values(["relevance", "query_id", "blinded_position"], ascending=[False, True, True])
    .reset_index(drop=True)
)

targeted_columns = [
    "query_id",
    "query_text",
    "candidate_id",
    "blinded_position",
    "doc_id",
    "relevance",
    "relevance_name",
    "recipe_title",
    "recipe_type",
    "recipe_description",
]

display(targeted_inspection_dataframe[targeted_columns])

,query_id,query_text,candidate_id,blinded_position,doc_id,relevance,relevance_name,recipe_title,recipe_type,recipe_description
0,128,"Chim cút xào lăn biến tấu lạ miệng, thơm ngon, ăn là ghiền",D017,17,5331,3,3 - highly relevant,"Chim cút xào lăn biến tấu lạ miệng, thơm ngon, ăn là ghiền",Món xào,Nếu thực đơn món xào của bạn đã nhàm chán với các món quá quen thuộc thì hôm nay hãy vào bếp ngay cùng Điện máy XANH để thực hiện món chim cút xào lăn lạ miệng thơm ngon với cách làm đơn giản vô cùng này nhé!
1,138,Món vả kho thịt cực đậm đà thơm ngon cho bữa ăn đưa cơm,D024,24,6423,3,3 - highly relevant,Thịt kho sung thơm ngon lạ miệng đậm đà cho bữa cơm,Món kho,"Những món kho luôn đem đến một hương vị đậm đà, vị mằn mặn ăn kèm chén cơm nóng mà nghĩ thôi cũng khiến bạn cồn cào cái bụng rồi. Cùng vào bếp ngay hôm nay thực hiện món thịt kho sung lạ miệng cho gia đình nhé!"
2,166,Bánh milo tan chảy không cần lò nướng hấp dẫn đơn giản tại nhà,D009,9,1976,3,3 - highly relevant,Bánh bông lan milo socola tan chảy mềm mịn không cần lò nướng,Món bánh,"Bánh bông lan milo được hòa quyện giữa lớp kem tươi béo ngậy cùng cốt bánh ngọt đắng, cực kỳ thơm ngon và ăn không có cảm giác ngán. Bạn cũng có thể thực hiện thành công món bánh này chỉ với một chiếc xửng hấp. Vào b..."
3,331,Công thức chi tiết cách tự làm dầu hào cực ngon đơn giản tại nhà,D026,26,10063,3,3 - highly relevant,Công thức chi tiết cách tự làm dầu hào cực ngon đơn giản tại nhà,Món khô - mắm,"Là một trong những gia vị cực kì phổ biến và được yêu thích trong ẩm thực, dầu hào hay còn gọi là dầu hàu đã và đang khiến nhiều người yêu thích vì hương vị của mình. Cùng Điện máy XANH vào bếp tìm hiểu công thức tự ..."
4,341,Nước chấm gỏi cuốn chay từ đậu phộng thơm ngon khó cưỡng tại nhà,D046,46,837,3,3 - highly relevant,Tương chấm gỏi cuốn chay,Món chay,"Tương chấm gỏi cuốn chay với vị béo ngậy của bơ đậu phộng, vị cay cay của ớt trái, đem đến cho bạn món nước chấm gỏi cuốn rất ngon và hấp dẫn đấy nhé!"
5,450,Bò bía mặn chấm tương đen đậu phộng béo ngậy ngon mê ly,D032,32,10242,3,3 - highly relevant,Bò bía mặn chấm tương đen đậu phộng béo ngậy ngon mê ly,Món cuốn - trộn,"Bò bía mặn là một món cuốn vô cùng ngon miệng với sự kết hợp độc đáo giữa các nguyên liệu như trứng chiên, lạp xưởng, tôm khô, rau quế,... Nếu bạn đã từng thưởng thức qua và cảm thấy nhung nhớ hương vị của cuốn bò bí..."
6,482,Bánh bò rễ tre bằng bột pha sẵn mềm dai chuẩn vị miền tây,D047,47,2385,3,3 - highly relevant,Bánh bò rễ tre bằng bột pha sẵn mềm dai chuẩn vị miền tây,Món bánh,"Bánh bò là món bánh được nhiều người yêu thích nhờ mùi vị thơm ngon, cốt bánh mềm mịn, dẻo thơm và màu sắc đẹp mắt. Hôm nay, cùng Điện máy XANH vào bếp học cách làm bánh bò rễ tre bằng bột pha sẵn mềm dai chuẩn vị mi..."
7,484,"Sườn xào chua ngọt mềm thơm ngon, đậm đà, cực hao cơm tại nhà",D008,8,953,3,3 - highly relevant,Sườn xào chua ngọt,Món chính,"Vị chua chua ngọt ngọt, miếng sườn mềm thơm hòa quyện cùng nước sốt sền sệt đậm đà, chỉ nhìn thôi đã thấy ngon miệng vô cùng."
8,39,Xôi lạc bằng nồi cơm điện cực nhanh gọn mà ngon,D040,40,338,2,2 - relevant,Xôi đậu đen cấp tốc bằng nồi cơm điện,Món ngon hàng ngày,"Hạt xôi dẻo mềm, đậu đen bên trong mềm bở mà vẫn giữ nguyên hạt, ăn kèm muối lạc làm nên bữa sáng vừa nhanh gọn lại thơm ngon."
9,93,"Bánh bao nhân custard xoài mềm mịn, thơm ngon",D036,36,3107,2,2 - relevant,Bánh bao nhân dừa ngọt căng mềm mịn thơm ngon,Món bánh,"Bánh bao nhân đậu đỏ chay thơm ngon, béo ngậy, là món ăn mà cả gia đình bạn có thể thưởng thức vào buổi sáng. Hãy cùng vào bếp thực hiện ngay món bánh ngon lành này nhé!"
10,254,"Khoai tây chiên bơ tỏi thơm lừng, nóng giòn ăn vặt ngày mưa gió",D037,37,7053,2,2 - relevant,Bánh hotdog khoai tây chiên giòn thơm ngon cực hấp dẫn,Món chiên,"Lớp vỏ khoai tây chiên mỏng giòn, phô mai béo ngậy chảy quyện với xúc xích dày thịt là sự kết hợp hoàn hảo để thay thế cho bánh hotdog bột mì truyền thống. Hôm nay hãy cùng vào bếp cùng làm món chiên siêu hấp dẫn này..."
11,320,"Sườn sụn heo nướng cay thơm ngon, giòn tan trong miệng",D022,22,4835,2,2 - relevant,"Sườn cốt lết nướng mật ong thơm lừng, thịt mềm, ngon khó cưỡng",Món nướng,"Mùa dịch này các quán xá đều phải đóng cửa, mà lại thèm món sườn nướng ngoài tiệm cơm quá thì phải làm sao đây? Bạn đừng lo, ngay bây giờ Điện máy XANH sẽ mách bạn công thức làm món sườn cốt lết mật ong siêu ngon tại..."
12,334,"Cá trê kho riềng ngon miệng đậm đà, bắt cơm",D012,12,6082,2,2 - relevant,Cá diếc kho riềng thơm lừng đậm đà ngon miệng,Món kho,"Món kho thường xuất hiện trong mâm cơm gia đình, hương vị đậm đà cùng chén cơm nóng mà nghĩ đến thôi bạn cũng đã phải thèm rồi. Hôm nay, cùng vào bếp thực hiện ngay cách làm cá diếc kho riềng đơn giản này nhé!"
13,434,Cơm trộn kim chi Hàn Quốc thơm ngon hấp dẫn chuẩn vị tại nhà,D041,41,7334,2,2 - relevant,Cơm chiên kim chi tôm rong biển cay ngon hết sẩy,Món chiên,"Hôm nay Điện máy XANH sẽ hướng dẫn các bạn cách thực hiện một món chiên siêu ngon với hương vị mới lạ, đổi vị cho cả gia đình với cách làm vô cùng đơn giản, dễ thực hiện. Cùng vào bếp và thực hiện ngay món cơm chiên ..."
14,437,Bánh muffin và kếp yến mạch nhanh chóng bổ dưỡng,D050,50,3789,2,2 - relevant,Bánh pancake bí đỏ yến mạch thơm ngon bổ dưỡng cho bé ăn dặm,Món bánh,"Tránh lặp đi lặp lại những món cháo nhàm chán, pancake bí đỏ yến mạch sẽ giúp bé thay đổi khẩu vị và ăn ngon hơn. Hãy cùng vào bếp thực hiện món bánh ngon này bạn nhé!"
15,447,"Nấm rơm kho sả ớt lạ miệng, thơm ngon đổi vị cho gia đình",D047,47,6311,2,2 - relevant,"Nấm rơm kho khổ qua chay thơm ngon, lạ miệng cho gia đình",Món kho,"Bạn đã bổ sung vào thực đơn món chay gia đình mình nhiều món ăn chưa? Hôm nay, Điện máy XANH sẽ mách bạn cách làm nấm rơm kho khổ qua chay thơm ngon đậm đà đổi vị cho ngày rằm. Cùng vào bếp để thực hiện ngay món ngon..."
16,76,Bánh Trung thu thập cẩm bằng nồi cơm điện đơn giản tại nhà,D011,11,3212,1,1 - partially related,"Bánh trung thu trà xanh phô mai bằng sandwich siêu ngon, dễ làm",Món bánh,"Dịp Trung Thu sắp đến rồi, bạn đã có kế hoạch gì cho ngày sum vầy cùng gia đình chưa? Nếu chưa thì hãy cùng vào bếp với Điện máy XANH khám phá ngay công thức của món bánh trung thu trà xanh nhân phô mai bằng sandwich..."
17,133,"Chả cá basa dai ngon, hấp dẫn đơn giản tại nhà",D010,10,1033,1,1 - partially related,Cá Basa kho tộ,Món chính,"- Món cá basa kho là món ăn được người dân miền Tây ưa chuộng, loại cá này có quanh năm nên rất được yêu thích"
18,214,"Bánh sinh nhật rau câu trái cây dễ làm, không cần máy đánh trứng",D025,25,9161,1,1 - partially related,"Rau câu sữa bắp thơm ngon, dinh dưỡng cực đơn giản tại nhà",Ăn vặt,"Rau câu sữa bắp là món tráng miệng thơm ngon, dinh dưỡng, chỉ với các bước thực hiện đơn giản, đảm bảo sẽ thành công luôn đó. Hôm nay cùng vào bếp với chị Ngọc Hiền và Điện máy XANH để làm ngay món ăn hấp dẫn này nha..."
19,242,Bánh đa cá rô ăn kèm với rau cải cực ngon đơn giản ngay tại nhà,D016,16,8352,1,1 - partially related,Gỏi cá rô phi sống ngon miệng dễ làm không bị tanh,Món gỏi - salad,"Nếu bạn đang tìm một món ăn thơm ngon, thanh mát để chóng ngấy sau những ngày ăn quá nhiều dầu mỡ thì món gỏi trộn chính là giải pháp ""cứu cánh"" tuyệt vời đấy! Cùng vào bếp với Điện máy XANH ngay hôm nay và học ngay ..."
20,268,Mắm ruốc ngon đậm đà món ăn dân dã lại dễ làm tại nhà,D022,22,8050,1,1 - partially related,"Lẩu mắm ruốc nóng hổi, thơm ngon khó cưỡng cho ngày lạnh",Món lẩu,"Lẩu mắm ruốc là món lẩu trứ danh của người dân miền Tây Nam Bộ với hương vị đậm đà, thơm ngon đặc trưng, ăn hoài không chán. Hãy cùng Điện máy XANH vào bếp thực hiện ngay món lẩu hấp dẫn này theo 2 công thức được chi..."
21,335,Súp bí đỏ thịt heo ngon miệng hấp dẫn dễ làm cho bữa ăn,D028,28,842,1,1 - partially related,Súp bí đỏ chay,Món chay,"Một món súp dễ làm, thơm ngon và beo béo mùi vị nước cốt dừa hòa lẫn bí đỏ, không những người ăn chay mà kể cả người ăn mặn, em bé, người già đều có thể dùng được. Bạn hãy nạp đầy năng lượng cho buổi sáng bằng một ch..."
22,353,"Hướng dẫn cách nấu xôi gấc ngon, dẻo, đẹp",D021,21,7636,1,1 - partially related,Cách đồ xôi ngô dừa bằng nồi cơm điện siêu đơn giản,Món hấp,"Chào bạn, hôm nay cùng mình vào bếp làm món xôi ngô dừa thơm lừng, dẻo béo nhé! Với cách đồ xôi bắp nước cốt dừa này, bạn sẽ có ngay món hấp ngon miệng, chuẩn vị mà lại cực kỳ đơn giản. Đây là món ăn sáng hoặc món ăn..."
23,481,Mực chiên giòn sốt me chua ngọt siêu ngon đậm đà hương vị,D030,30,4705,1,1 - partially related,Mực nướng muối ớt bằng nồi chiên không dầu ngon đậm đà,Món nướng,"Các món nướng hấp dẫn từ mực luôn luôn được đánh giá cao nhờ hương vị tươi ngon đậm đà khó cưỡng. Hôm nay, vào bếp cùng Điện máy XANH học ngay công thức làm món mực nướng muối ớt bằng nồi chiên không dầu với cách làm..."
24,31,"Thịt kho mắm nêm thơm ngon đậm đà hương vị, dễ làm tại nhà",D049,49,8383,0,0 - not relevant,"Mắm dưa cà pháo chuẩn vị miền Trung giòn ngon, đậm đà",Món gỏi - salad,"Mắm dưa cà có thể xem là một món gỏi trộn vô cùng nổi tiếng của miền Trung với hương vị hấp dẫn và được rất nhiều người yêu thích. Hôm nay, hãy cùng vào bếp và thử thực hiện món mắm dưa cà này nhé!"
25,37,"Chà bông gà thơm ngon, đơn giản, tơi mịn ngay tại nhà",D032,32,4689,0,0 - not relevant,Gà nướng mật ong nồi chiên không dầu tiện lợi nhanh chóng,Món nướng,"Bạn đang tìm kiếm công thức gà nướng mật ong nồi chiên không dầu đơn giản mà ngon bá cháy? Món gà nướng này sẽ biến bữa ăn gia đình bạn thành bữa tiệc nhỏ, với lớp da giòn rụm, thịt mềm mọng và hương vị đậm đà. Cùng ..."
26,251,Bóng cá chay sốt chua ngọt thơm ngon nức mũi cho bữa cơm Rằm,D025,25,10102,0,0 - not relevant,"Nước mắm cá cơm tại nhà thơm ngon, vàng ươm, chuẩn vị",Món khô - mắm,"Bạn muốn ăn một loại nước mắm vừa vệ sinh an toàn lại vừa thơm ngon, vậy hãy cùng Điện máy XANH vào bếp tự làm ngay nước mắm cá cơm thơm ngon cho cả gia đình mình với những bước làm vô cùng đơn giản dưới đây!"
27,252,Sò huyết nấu canh thơm ngon mới lạ đơn giản cho bữa cơm,D032,32,1203,0,0 - not relevant,Sò lông nước mỡ hành đậu phộng,Món chính,Tại hưởng món sò lông nướng mỡ hành thơm tại nhà vào buổi tối đẹp trời có gì sai?\r\nMón này là tuyệt nhất trong món hải sản nướng rồi.\r\nHôm nay nấu nhé!
28,266,Súp tôm nha đam mới lạ thơm ngon thanh mát cả ngày hè,D049,49,4346,0,0 - not relevant,Súp thanh cua dễ làm tại nhà với nồi inox cho bữa sáng ấm bụng,Món nước,"Bạn muốn nấu súp thanh cua ngon chuẩn vị, nhanh gọn? Cùng vào bếp với công thức súp thanh cua hạt chia thanh đạm, ấm bụng. Món nước này sẽ giúp bạn chế biến một món khai vị dinh dưỡng chỉ trong tích tắc, đảm bảo cả n..."
29,268,Mắm ruốc ngon đậm đà món ăn dân dã lại dễ làm tại nhà,D026,26,10084,0,0 - not relevant,"Mắm cá lóc thơm ngon, đậm vị đơn giản tại nhà",Món khô - mắm,"Mắm cá lóc là một trong những đặc sản của miền Tây sông nước với hương đậm đà vô cùng bắt cơm. Hôm nay, chuyên mục Mẹo vào bếp của Điện máy XANH sẽ mách bạn cách tự tay làm món mắm cá này tại nhà nhé!"
30,371,"Gà rán bằng nồi chiên không dầu giòn tan, đơn giản chuẩn vị KFC",D033,33,7424,0,0 - not relevant,Cách chiên chả giò bằng nồi chiên không dầu giòn rụm cực nhanh đơn giản,Món chiên,Bạn là một tín đồ của món chả giò chiên nhưng lại ngại việc sử dụng quá nhiều dầu mỡ sẽ gây hại cho sức khỏe. Thế nên hôm nay Điện máy XANH sẽ mách ngay với bạn cách chiên chả giò bằng nồi chiên không dầu giòn ngon s...
31,389,Ếch xào sả nghệ thơm ngon đậm đà hấp dẫn cho bữa cơm,D014,14,5800,0,0 - not relevant,"Gà xào sả ớt miền Bắc ngon, cay nồng, hấp dẫn và cực đưa cơm",Món xào,"Nếu bạn đang tìm một món xào nhanh gọn nhưng vẫn đậm đà hương vị thì hãy cùng vào bếp thử ngay công thức gà xào sả ớt miền Bắc. Với sự kết hợp cay nồng, hấp dẫn, món xào này chắc chắn sẽ khiến bữa cơm gia đình thêm p..."

## 6. Inspect a Specific Query

Use this cell when a query looks suspicious in the evaluation report or when you want to manually audit one known `query_id`. Set `MANUAL_QUERY_ID` to an integer from `0` to `499`.

In [ ]:
MANUAL_QUERY_ID = None
MANUAL_SORT_WITHIN_QUERY = "relevance_desc"

if MANUAL_QUERY_ID is None:
    print("Set MANUAL_QUERY_ID to an integer query_id when you want to inspect a specific query.")
else:
    display_query_inspection(int(MANUAL_QUERY_ID), sort_within_query=MANUAL_SORT_WITHIN_QUERY)

## 7. Optional Export of the Current Random Sample

This cell is disabled by default. Turn on `EXPORT_RANDOM_SAMPLE` if you want a CSV snapshot of the currently sampled query inspections for sharing or offline review.

In [ ]:
EXPORT_RANDOM_SAMPLE = False
RANDOM_SAMPLE_EXPORT_PATH = NOTEBOOK_OUTPUT_DIR / "manual_inspection" / "sampled_llm_relevance_inspection.csv"

if EXPORT_RANDOM_SAMPLE:
    RANDOM_SAMPLE_EXPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    sampled_export_dataframe = inspection_dataframe[inspection_dataframe["query_id"].isin(sampled_query_ids)].copy()
    sampled_export_dataframe = sampled_export_dataframe.sort_values(["query_id", "blinded_position"])
    sampled_export_dataframe.to_csv(RANDOM_SAMPLE_EXPORT_PATH, index=False, encoding="utf-8-sig")
    print("Saved random sample inspection file to:", RANDOM_SAMPLE_EXPORT_PATH)
else:
    print("Export disabled. Set EXPORT_RANDOM_SAMPLE = True to write a CSV snapshot.")