In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import time
import random
import re
from tqdm import tqdm
import os

In [2]:
# Config
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7',
}

BASE_URL = 'https://www.dienmayxanh.com'
MIN_DELAY = 0.5
MAX_DELAY = 1.5

## 1. Lấy danh sách Categories

In [8]:
def get_dmx_categories():
    categories = [
        {'name': "Món canh", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-canh'},
        {'name': "Món bánh", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-banh'},
        {'name': "Món chè", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-che'},
        {'name': "Món nước", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-nuoc'},
        {'name': "Món kem", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-kem'},
        {'name': "Món nướng", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-nuong'},
        {'name': "Món cháo", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-chao'},
        {'name': "Món xào", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-xao'},

        {'name': "Món kho", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-kho'},
        {'name': "Món chiên", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-chien'},        
        {'name': "Món hấp", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-hap'},
        {'name': "Món lẩu", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-lau'},
        {'name': "Món gỏi - salad", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-goi-tron'},
        {'name': "Món từ gà", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-tu-ga'},
        {'name': "Món từ bò", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-tu-bo'},
        {'name': "Món chay", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-chay'},
        {'name': "Ăn vặt", 'url': 'https://www.dienmayxanh.com/vao-bep/an-vat'},

        {'name': "Ngày lễ Tết", 'url': 'https://www.dienmayxanh.com/vao-bep/ngay-le-tet'},
        {'name': "Thức uống", 'url': 'https://www.dienmayxanh.com/vao-bep/thuc-uong'},
        {'name': "Sinh tố", 'url': 'https://www.dienmayxanh.com/vao-bep/sinh-to'},
        {'name': "Trà sữa", 'url': 'https://www.dienmayxanh.com/vao-bep/tra-sua'},
        {'name': "Nước ép", 'url': 'https://www.dienmayxanh.com/vao-bep/nuoc-ep'},
        {'name': "Món tráng miệng", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-trang-mieng'},
        {'name': "Món khô - mắm", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-kho-mam'},
        {'name': "Món cuốn - trộn", 'url': 'https://www.dienmayxanh.com/vao-bep/mon-cuon-tron'}
    ]
    return categories

categories = get_dmx_categories()
print(f"Tổng số category: {len(categories)}")

Tổng số category: 25

In [15]:
categories

[{'name': 'Món canh', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-canh'},
 {'name': 'Món bánh', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-banh'},
 {'name': 'Món chè', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-che'},
 {'name': 'Món nước', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-nuoc'},
 {'name': 'Món kem', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-kem'},
 {'name': 'Món nướng', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-nuong'},
 {'name': 'Món cháo', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-chao'},
 {'name': 'Món xào', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-xao'},
 {'name': 'Món kho', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-kho'},
 {'name': 'Món chiên', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-chien'},
 {'name': 'Món hấp', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-hap'},
 {'name': 'Món lẩu', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-lau'},
 {'name': 'Món gỏi - salad',
  'url': 'https://www.dienmayxanh.com/vao-bep/mon-goi-tron'},
 {'name': 'Món từ gà', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-tu-ga'},
 {'name': 'Món từ bò', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-tu-bo'},
 {'name': 'Món chay', 'url': 'https://www.dienmayxanh.com/vao-bep/mon-chay'},
 {'name': 'Ăn vặt', 'url': 'https://www.dienmayxanh.com/vao-bep/an-vat'},
 {'name': 'Ngày lễ Tết',
  'url': 'https://www.dienmayxanh.com/vao-bep/ngay-le-tet'},
 {'name': 'Thức uống', 'url': 'https://www.dienmayxanh.com/vao-bep/thuc-uong'},
 {'name': 'Sinh tố', 'url': 'https://www.dienmayxanh.com/vao-bep/sinh-to'},
 {'name': 'Trà sữa', 'url': 'https://www.dienmayxanh.com/vao-bep/tra-sua'},
 {'name': 'Nước ép', 'url': 'https://www.dienmayxanh.com/vao-bep/nuoc-ep'},
 {'name': 'Món tráng miệng',
  'url': 'https://www.dienmayxanh.com/vao-bep/mon-trang-mieng'},
 {'name': 'Món khô - mắm',
  'url': 'https://www.dienmayxanh.com/vao-bep/mon-kho-mam'},
 {'name': 'Món cuốn - trộn',
  'url': 'https://www.dienmayxanh.com/vao-bep/mon-cuon-tron'}]

## 2. Lấy danh sách URL công thức

Do trang điện máy xanh có định dạng cần bấm nút "Xem thêm" thay vì duyệt qua các page nên ta cần dùng selenium để giả lập click nút xem thêm này

In [14]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, ElementClickInterceptedException
import time

def get_food_urls_from_category_dmx(category_url):
    driver = webdriver.Chrome()
    driver.get(category_url)
    wait = WebDriverWait(driver, 10)

    food_urls = set()   # tránh trùng lặp

    prev_count = 0

    while True:
        # 1. Try to click "Xem thêm"
        try:
            see_more_btn = wait.until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, "a.seemore-cook"))
            )
            driver.execute_script("arguments[0].scrollIntoView(true);", see_more_btn)
            time.sleep(0.3)
            see_more_btn.click()
        except TimeoutException:
            # Không còn nút => load hết rồi
            break
        except ElementClickInterceptedException:
            # Thử lại nhẹ
            time.sleep(1)
            continue

        # 2. Wait until new li are loaded
        time.sleep(1)  # nhẹ để JS load
        all_items = driver.find_elements(By.CSS_SELECTOR, "ul li a")
        cur_count = len(all_items)

        if cur_count == prev_count:
            # Không tăng nữa => hết dữ liệu
            break

        prev_count = cur_count

    # 3. Extract URL từ tất cả li
    final_items = driver.find_elements(By.CSS_SELECTOR, "ul li a")
    for item in final_items:
        href = item.get_attribute("href")
        if href and "/vao-bep/" in href:   # filter chuẩn
            food_urls.add(href)

    driver.quit()
    return list(food_urls)

In [19]:
# Test trên 1 category
print(f"Testing: {categories[0]['name']}")

test_urls = get_food_urls_from_category_dmx(categories[0]['url'])
print(f"Found {len(test_urls)} recipes")

Testing: Món canh
Found 960 recipes

In [20]:
test_urls[:3]

['https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-ngot-chay-dau-hu-thom-ngon-thanh-mat-don-11520',
 'https://www.dienmayxanh.com/vao-bep/cach-nau-ga-ac-tan-ham-ngai-cuu-cuc-ngon-bo-mau-huyet-01384',
 'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-dua-leo-xuong-heo-nhoi-thit-va-tom-thanh-mat-05075']

In [21]:
# Cào tất cả categories
all_recipe_urls = []
seen_urls = set()

for category in tqdm(categories, desc="Crawling categories"):
    cat_name = category["name"]
    cat_url  = category["url"]

    print(f"Crawling category: {cat_name}")

    try:
        food_urls = get_food_urls_from_category_dmx(cat_url)
    except Exception as e:
        print(f"Lỗi khi crawl category {cat_name}: {e}")
        continue

    for url in food_urls:
        if url not in seen_urls:
            seen_urls.add(url)
            all_recipe_urls.append((cat_name, url))

    print(f"Total collected: {len(all_recipe_urls)}")
    time.sleep(random.uniform(1, 2))

print(f"Total unique recipes: {len(all_recipe_urls)}")

Crawling categories:   0%|          | 0/25 [00:00<?, ?it/s]

Crawling category: Món canh
Total collected: 960

Crawling categories:   4%|▍         | 1/25 [01:30<36:10, 90.45s/it]

Crawling category: Món bánh
Total collected: 3518

Crawling categories:   8%|▊         | 2/25 [08:08<1:44:07, 271.63s/it]

Crawling category: Món chè
Total collected: 3840

Crawling categories:  12%|█▏        | 3/25 [08:49<1:00:51, 165.96s/it]

Crawling category: Món nước
Total collected: 4309

Crawling categories:  16%|█▌        | 4/25 [09:41<42:27, 121.29s/it]

Crawling category: Món kem
Total collected: 4497

Crawling categories:  20%|██        | 5/25 [10:13<29:39, 88.97s/it]

Crawling category: Món nướng
Total collected: 5073

Crawling categories:  24%|██▍       | 6/25 [11:04<24:04, 76.02s/it]

Crawling category: Món cháo
Total collected: 5448

Crawling categories:  28%|██▊       | 7/25 [11:49<19:44, 65.80s/it]

Crawling category: Món xào
Total collected: 6764

Crawling categories:  32%|███▏      | 8/25 [14:06<25:02, 88.40s/it]

Crawling category: Món kho
Total collected: 7678

Crawling categories:  36%|███▌      | 9/25 [15:35<23:40, 88.75s/it]

Crawling category: Món chiên
Total collected: 9000

Crawling categories:  40%|████      | 10/25 [18:08<27:07, 108.50s/it]

Crawling category: Món hấp
Total collected: 9692

Crawling categories:  44%|████▍     | 11/25 [19:26<23:07, 99.11s/it]

Crawling category: Món lẩu
Total collected: 9947

Crawling categories:  48%|████▊     | 12/25 [20:05<17:33, 81.06s/it]

Crawling category: Món gỏi - salad
Total collected: 10454

Crawling categories:  52%|█████▏    | 13/25 [20:59<14:32, 72.74s/it]

Crawling category: Món từ gà
Total collected: 10583

Crawling categories:  56%|█████▌    | 14/25 [22:07<13:04, 71.27s/it]

Crawling category: Món từ bò
Total collected: 10706

Crawling categories:  60%|██████    | 15/25 [23:07<11:19, 67.94s/it]

Crawling category: Món chay
Total collected: 10971

Crawling categories:  64%|██████▍   | 16/25 [24:22<10:30, 70.02s/it]

Crawling category: Ăn vặt
Total collected: 11700

Crawling categories:  68%|██████▊   | 17/25 [27:24<13:49, 103.75s/it]

Crawling category: Ngày lễ Tết
Total collected: 11993

Crawling categories:  72%|███████▏  | 18/25 [28:47<11:21, 97.42s/it]

Crawling category: Thức uống
Total collected: 12843

Crawling categories:  76%|███████▌  | 19/25 [30:15<09:27, 94.54s/it]

Crawling category: Sinh tố
Total collected: 12899

Crawling categories:  80%|████████  | 20/25 [30:45<06:15, 75.18s/it]

Crawling category: Trà sữa
Total collected: 12977

Crawling categories:  84%|████████▍ | 21/25 [31:14<04:05, 61.28s/it]

Crawling category: Nước ép
Total collected: 13024

Crawling categories:  88%|████████▊ | 22/25 [31:42<02:34, 51.56s/it]

Crawling category: Món tráng miệng
Total collected: 13203

Crawling categories:  92%|█████████▏| 23/25 [32:58<01:57, 58.67s/it]

Crawling category: Món khô - mắm
Total collected: 13394

Crawling categories:  96%|█████████▌| 24/25 [33:46<00:55, 55.51s/it]

Crawling category: Món cuốn - trộn
Total collected: 13515

Crawling categories: 100%|██████████| 25/25 [34:34<00:00, 82.99s/it]

Total unique recipes: 13515

In [23]:
all_food_urls = [(cat, url) for cat, url in all_recipe_urls]

In [24]:
all_food_urls

[('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-ngot-chay-dau-hu-thom-ngon-thanh-mat-don-11520'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-ga-ac-tan-ham-ngai-cuu-cuc-ngon-bo-mau-huyet-01384'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-dua-leo-xuong-heo-nhoi-thit-va-tom-thanh-mat-05075'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-nam-can-tay-de-lam-de-an-thom-nuc-mui-07891'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-cua-chay-thom-ngon-don-gian-02693'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cac-mon-canh-mua-dong-mien-bac-de-nau-giu-am-co-the-23616'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-gio-heo-ham-cu-cai-muoi-thom-ngon-bo-duong-ca-nha-07674'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-minh-thai-han-quoc-bo-duong-la-mieng-cuc-09540'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ca-me-nau-me-dau-thom-ngon-bang-noi-lau-da-nang-tien-22348'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-ke-ga-ngoc-ke-ngon-thom-beo-voi-noi-lau-hap-da-22987'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-bi-do-mem-ngon-bo-duong-cho-bua-com-gia-06076'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-can-tay-ca-vien-thom-ngon-thanh-dam-cho-bua-com-05910'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-bo-vien-nau-nam-va-nau-rau-cu-thanh-mat-cho-05008'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-ma-de-tom-kho-ngon-mieng-bo-duong-de-lam-11759'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-dau-ca-hoi-voi-tom-va-mang-chua-thom-05830'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-bap-cai-giam-can-thom-ngon-nhanh-chong-cho-nang-07272'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-sup-bong-cai-xanh-voi-rau-cu-va-kem-sua-thom-ngon-04904'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chuoi-dau-thom-ngon-dam-da-cho-bua-com-gia-dinh-14886'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-ngheu-nau-khe-va-nau-rong-bien-thom-ngon-04918'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-ca-chua-trung-dam-da-don-gian-de-lam-thom-05752'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-dau-xanh-bi-do-thit-bam-bo-duong-bang-noi-inox-23234'),
 ('Món canh', 'https://www.dienmayxanh.com/vao-bep/ngay-le-tet'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-ca-nau-hoa-chuoi-me-thanh-mat-cho-bua-com-nha-23605'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-cua-bi-do-thom-ngon-bat-mat-khong-thua-ngoai-03210'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-sup-ca-chua-nuong-cuc-ngon-bo-duong-de-lam-05043'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-hen-nau-chua-bau-va-rau-muong-thom-ngon-thanh-05409'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-he-dau-hu-thit-bam-thom-ngon-la-mieng-17871'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-gio-heo-bac-thao-thom-ngon-moi-la-dam-vi-don-gian-08591'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bau-nhoi-thit-thom-ngon-thanh-dam-cho-ngay-nang-17218'),
 ('Món canh', 'https://www.dienmayxanh.com/vao-bep/nuoc-ep'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-rau-ram-thom-ngon-don-gian-cho-bua-com-06092'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-kho-qua-ca-ot-thom-ngon-thanh-mat-dam-d-02481'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-hen-nau-muop-thom-ngon-hap-dan-don-gian-vo-cung-16178'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-muop-nau-tom-kho-va-tom-tuoi-thom-ngon-don-05919'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-ga-ham-hat-sen-tao-do-ky-tu-cuc-tot-cho-suc-23112'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/thuc-don-com-toi-du-chat-cho-nguoi-ban-ron-00734'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-tom-moc-hat-sen-thanh-mat-cho-ngay-tet-04826'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-bong-he-dau-hu-non-va-thit-bam-thom-ngon-hap-05480'),
 ('Món canh', 'https://www.dienmayxanh.com/vao-bep/mon-xao'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-day-nau-tom-hap-thanh-mat-giai-nhiet-ngay-08668'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ga-nau-toi-la-mieng-thom-ngon-bo-duong-cho-ca-nha-07845'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-luon-la-giang-va-bap-chuoi-dam-chat-nam-04851'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rong-bien-ca-chua-thom-ngon-thanh-mat-co-the-13843'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-ngot-muop-va-nam-thom-ngon-thanh-nhiet-10248'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-khoai-tay-don-gian-thom-ngon-ai-an-cung-thich-07903'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/mach-ban-cach-luoc-tiet-lon-min-toi-khong-bot-khi-cuc-de-voi-23363'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-bo-cau-ham-dau-xanh-dac-biet-hap-dan-cho-ca-nha-cung-13163'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-hat-mit-chay-moi-la-thom-ngon-don-gian-tai-09174'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-thit-trau-ham-sa-va-ham-khoai-tay-thom-ngon-don-09686'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-thit-bam-sau-va-doc-mung-thanh-nhiet-05978'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-khoai-mon-ham-xuong-va-tom-kho-ngot-bui-deo-03867'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-duoi-heo-ham-khoai-mon-ngon-mieng-bui-beo-bo-10781'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-bong-bi-ca-thac-lac-va-tom-thom-ngon-ngot-nhe-05031'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-sup-khoai-tay-don-gian-thom-ngon-hap-dan-00072'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-den-thit-bam-va-tom-kho-ngot-mat-thom-04846'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-trai-dieu-ngot-bui-giai-nang-ngay-he-cuc-16947'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mong-toi-nau-tom-tuoi-thanh-mat-sieu-don-gian-09728'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-ga-ham-tao-do-nam-dong-co-bo-duong-ngot-lanh-22458'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-trung-cut-lon-um-bau-thom-ngon-thanh-dam-cho-bua-com-11055'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cua-dong-ca-chua-thanh-mat-nuoc-dung-dam-da-de-23305'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-thit-bo-ca-chua-dam-da-thom-ngon-cho-be-08184'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-thit-ga-ca-rot-don-gian-thom-ngon-cuc-dam-da-03927'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bau-chay-thom-ngon-thanh-dam-cho-ngay-chay-14764'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-tep-thom-ngon-thanh-mat-don-gian-de-lam-08675'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bau-thit-bo-ngon-ngot-thanh-mat-don-gian-tai-11276'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-ma-thit-bam-thom-ngon-ngot-nuoc-thanh-mat-11490'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-sup-gumbo-hai-san-va-thit-ga-dac-trung-cua-am-thuc-06653'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-cu-sen-ham-xuong-dam-da-hap-dan-cho-bua-com-nha-14925'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-xa-lach-xoong-tom-tuoi-ngon-ngot-hap-dan-don-11567'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/tong-hop-7-cach-nau-canh-trai-thanh-mat-hap-dan-de-lam-cho-13067'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-ca-chua-thom-thanh-mat-thom-ngon-an-la-12749'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/ngheu-nau-canh-gi-ngon-tong-hop-12-cach-nau-canh-ngheu-hap-09689'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ca-cam-nau-canh-chua-la-giang-chua-ngot-thanh-mat-11859'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ga-la-giang-ngon-nhat-vi-chua-diu-thit-ga-00187'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-thit-vien-rau-cu-dinh-duong-thanh-mat-cho-bua-11025'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-lang-nau-thit-bam-thom-ngon-giai-nhiet-co-12373'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-tom-cu-hu-dua-thanh-mat-chua-ngot-cuc-bat-06554'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-trung-ca-nau-canh-chua-thanh-mat-giai-nhiet-ngay-he-22571'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-cu-lao-chay-thom-ngon-hap-dan-cho-ngay-chay-them-14178'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-song-nau-ngot-chua-ngot-bat-vi-cuc-bat-com-13297'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bap-ham-gio-heo-dam-vi-thanh-mat-cho-mam-com-12727'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-sau-thit-bam-va-suon-thanh-mat-thom-ngon-don-05479'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-bi-dao-nau-xuong-va-nau-tom-thanh-mat-cho-bua-04674'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-duoi-bo-ham-bia-mon-ngon-kho-cuong-dip-cuoi-tuan-09479'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chuoi-xanh-la-lot-thom-ngon-beo-bui-de-lam-07855'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/tong-hop-9-cach-nau-canh-he-thanh-nhiet-don-gian-cho-ngay-12227'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-muc-nau-dua-ngot-thom-thanh-mat-bo-duong-cho-13842'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/tong-hop-cac-loai-rau-nem-canh-chua-thong-dung-de-di-cho-23506'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-duoi-heo-ham-dau-phong-ngot-thom-beo-bui-hap-dan-08975'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mang-tiet-nung-ninh-nuoc-canh-trong-veo-voi-noi-22773'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-luon-nghe-an-thom-ngon-chuan-vi-don-gian-04252'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ga-nau-cay-han-quoc-thom-nong-hap-dan-ngon-kho-cuong-08016'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-hau-ngon-ngot-mem-beo-bo-duong-de-lam-tai-nha-06757'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-bau-nau-hen-thanh-mat-don-gian-cho-ca-gia-dinh-09374'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-du-du-ham-xuong-ngon-mieng-bo-duong-tot-cho-suc-08844'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-bop-nau-ngot-thom-ngon-don-gian-hap-dan-ai-11121'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-ngot-khong-rau-ngot-chay-thanh-dam-ma-dua-13650'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-den-tom-tuoi-ngon-ngot-thanh-mat-cho-gia-09553'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-chua-cha-ca-thac-lac-thom-ngon-don-gian-tai-nha-08497'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-miso-rong-bien-chuan-bi-nhat-tai-gia-bang-noi-23086'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-la-vong-vang-nau-canh-chua-thanh-mat-cho-bua-com-nha-23220'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-be-xanh-long-ga-thanh-mat-ngon-ngot-cho-bua-10614'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mong-toi-muop-ngon-ngot-don-gian-tai-nha-14538'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-trai-nau-bau-ngon-mieng-don-gian-cho-bua-com-11964'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-dau-ca-thu-nau-canh-chua-cuc-ngon-an-la-ghien-15315'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-chan-gio-ham-mang-kho-chan-gio-ham-mang-kho-09312'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-ca-mu-nau-canh-chua-thom-ngon-dam-da-cho-bua-com-05666'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-ngot-tom-tuoi-thanh-mat-giup-bua-com-gia-10473'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-su-hao-xuong-va-canh-su-hao-ca-chep-thom-ngon-15391'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-mon-sup-ga-kieu-y-ngon-het-y-de-khong-tuong-ai-00302'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-lam-rau-cang-cua-nau-canh-ngon-va-thanh-mat-bang-noi-22781'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ga-ham-sam-han-quoc-chuan-vi-han-de-tam-bo-ca-nha-23191'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-bap-chay-don-gian-thom-ngon-cho-ngay-chay-02677'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-ca-chach-nau-canh-chua-ngon-mieng-thanh-nhiet-don-08159'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ga-quay-sieu-don-gian-nhanh-chong-moi-la-07287'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-xanh-thit-bam-thanh-mat-cho-ngay-nong-buc-13338'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-gan-bo-ham-hat-sen-va-dau-do-thom-ngon--02618'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-tiet-canh-tho-thom-ngon-de-lam-don-gian-ngay-tai-14557'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-chay-nam-thanh-dam-bat-vi-cho-bua-com-chay-12274'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ngheu-nau-ngot-ngot-mat-giai-nhiet-co-the-cuc-11864'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-bun-bo-gan-thom-ngon-don-gian-de-lam-an-la-ghien-09328'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ca-chep-nau-me-chua-thanh-chuan-vi-bang-bo-noi-green-23340'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ngao-he-thom-ngon-giau-chat-dinh-duong-cho-bua-17875'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-muong-nau-tom-thom-ngon-thanh-mat-tai-nha-05126'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-doc-mung-nau-canh-chua-ca-me-thom-ngon-dam-da-cay-23584'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-chan-gio-ham-ngai-cuu-thom-ngon-bo-duong-07517'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-don-quang-ngai-dac-san-tru-danh-bang-noi-va-22669'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-ngong-tom-kho-don-gian-ngot-nuoc-thanh-mat-08873'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cua-rau-ngot-khong-tanh-thanh-mat-cho-mam-com-08998'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-gio-heo-rau-ngot-ngon-ngot-doi-mon-cho-bua-com-11862'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-tom-rau-muong-thanh-mat-giai-nhiet-cuc-12690'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-kim-chi-ca-hoi-va-ca-ngu-thom-ngon-moi-la-don-08496'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-cuc-tan-o-nau-xuong-ngon-ngot-thanh-mat-cho-11344'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/tong-hop-21-cach-nau-canh-thit-bam-don-gian-thanh-ngot-tai-11597'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bap-cai-thit-bo-ngon-ngot-doi-vi-cho-bua-com-11701'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cu-cai-muoi-xa-bau-thom-ngon-bo-duong-hap-dan-13915'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cua-rau-mong-toi-muop-thanh-mat-sieu-hap-dan-13902'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-sup-ga-khoai-tay-hap-dan-thom-beo-cho-be-08170'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ca-ngat-nau-canh-chua-thom-ngon-giai-nhiet-cuc-hap-07564'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-vit-tiem-vua-ngon-vua-bo-ai-an-cung-khen--01464'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-sup-bao-ngu-hai-sam-vi-ca-map-thom-ngon-sang-chanh-09227'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-kim-chi-thit-heo-cap-toc-don-gian-thom-ngon-08484'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-dua-chua-tom-va-ca-thom-ngon-de-lam-tai-nha-04591'),
 ('Món canh', 'https://www.dienmayxanh.com/vao-bep/mon-tu-bo'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-ca-lang-sieu-bat-vi-dam-da-hap-dan-cho-bua-15259'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-khoai-mo-tom-tuoi-ngot-mat-hap-dan-cho-bua-com-11670'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bap-cai-thit-bam-don-gian-thom-ngon-ngot-thanh-09186'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/tong-hop-15-cach-nau-canh-ga-bo-duong-thom-ngon-don-gian-cho-07583'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ky-tu-bo-duong-sang-mat-dep-da-don-gian-05196'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-cu-chuoi-nau-oc-buou-ngon-la-vi-tuyet-chieu-dai-08378'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-chua-muc-dam-da-don-gian-thom-ngon-cho-bua-05710'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-tim-nau-xuong-heo-ngon-ngot-la-mieng-doi-mon-12804'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-ca-basa-tuyet-ngon-tai-nha-00575'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-sup-lo-dam-da-thom-ngon-cho-ca-gia-dinh-cung-14242'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mong-toi-thit-bam-don-gian-tai-nha-cho-bua-com-11904'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-ca-bong-lau-nau-mang-chua-thanh-nhiet-ngon-hap-dan-07632'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-moc-nam-huong-ngot-thanh-chuan-vi-cho-mam-co-23415'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-ca-thac-lac-ca-chua-thom-ngon-don-gian-doi-vi-08551'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-duoi-heo-ham-dau-den-ngot-thom-cuc-bo-duong-cho-09025'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-khoai-mo-nau-tom-va-nau-thit-bam-thom-ngon-04686'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-cai-cuc-tan-o-voi-tom-su-thit-bam-cha-ca-thac-04735'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-canh-cua-nau-rau-muong-ngon-ngot-dam-da-cho-bua-com-13640'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-nau-nam-kim-cham-don-gian-thom-ngon-de-06091'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-gio-heo-ham-va-don-gian-nhung-thom-ngon-bo-duong-cho-16451'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-nau-canh-khoai-tay-chay-thom-ngon-thanh-dam-cai-thien-13793'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-hoa-atiso-cuc-ngon-mat-ruot-dep-da-01647'),
 ('Món canh',
  'https://www.dienmayxanh.com/vao-bep/cach-lam-chim-cut-ham-bi-do-bo-duong-thom-ngon-cuc-don-gian-06162'),
 ('Món canh',

In [25]:
all_foods_df = pd.DataFrame(all_food_urls, columns=['category', 'url'])
all_foods_df

              category                                                url
0             Món canh  https://www.dienmayxanh.com/vao-bep/2-cach-nau...
1             Món canh  https://www.dienmayxanh.com/vao-bep/cach-nau-g...
2             Món canh  https://www.dienmayxanh.com/vao-bep/3-cach-nau...
3             Món canh  https://www.dienmayxanh.com/vao-bep/cach-nau-s...
4             Món canh  https://www.dienmayxanh.com/vao-bep/cach-nau-s...
...                ...                                                ...
13510  Món cuốn - trộn  https://www.dienmayxanh.com/vao-bep/2-cach-lam...
13511  Món cuốn - trộn  https://www.dienmayxanh.com/vao-bep/cach-lam-c...
13512  Món cuốn - trộn  https://www.dienmayxanh.com/vao-bep/cach-lam-m...
13513  Món cuốn - trộn  https://www.dienmayxanh.com/vao-bep/cach-lam-c...
13514  Món cuốn - trộn  https://www.dienmayxanh.com/vao-bep/cach-lam-c...

[13515 rows x 2 columns]

In [26]:
all_foods_df.to_csv('dienmayxanh_foods_urls.csv', index=False)
print("DataFrame successfully saved to output.csv")

DataFrame successfully saved to output.csv

## 3. Hàm crawl chi tiết công thức

In [16]:
#Load data từ csv
all_foods_df = pd.read_csv('dienmayxanh_foods_urls.csv')
all_foods_df.head()

   category                                                url
0  Món canh  https://www.dienmayxanh.com/vao-bep/2-cach-nau...
1  Món canh  https://www.dienmayxanh.com/vao-bep/cach-nau-g...
2  Món canh  https://www.dienmayxanh.com/vao-bep/3-cach-nau...
3  Món canh  https://www.dienmayxanh.com/vao-bep/cach-nau-s...
4  Món canh  https://www.dienmayxanh.com/vao-bep/cach-nau-s...

In [17]:
## Hàm để chỉ lấy text trong những đoạn có vừa text vừa link
def safe_text(node):
    if not node:
        return None

    p = node.find("p")
    if p:
        return p.get_text(" ", strip=True)

    return node.get_text(" ", strip=True)

In [18]:
import re

def normalize_time(text):
    """
    Chuẩn hoá thời gian tiếng Việt sang phút.
    """
    if not text:
        return None
    
    text = text.lower().strip()

    hours = 0
    minutes = 0

    # Bắt "x giờ" hoặc "xh"
    h1 = re.search(r'(\d+)\s*giờ', text)
    h2 = re.search(r'(\d+)\s*h(?!\w)', text)  # '1h', '2h'
    if h1:
        hours = int(h1.group(1))
    elif h2:
        hours = int(h2.group(1))

    # Bắt "y phút" hoặc "yph"
    m1 = re.search(r'(\d+)\s*phút', text)
    m2 = re.search(r'(\d+)\s*ph', text)
    if m1:
        minutes = int(m1.group(1))
    elif m2:
        minutes = int(m2.group(1))

    total = hours * 60 + minutes
    return str(total) + " phút" if total > 0 else None

In [19]:
def get_food_detail_dmx(url, category):
    result = {
        "link": url,
        "type_of_food": category,
        "title": None,
        "description": None,
        "author_name": None,
        "cook_time": None,
        "num_of_people": None,
        "calories": None,
        "num_of_ingredients": None,
        "ingredients": [],
        "step": [],
        "note": [],
        "post_date": None,
    }

    try:
        response = requests.get(url, headers=HEADERS, timeout=15)
        response.encoding = 'utf-8'
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Tìm vùng nội dung chính
        detail_content = soup.find('div', class_='detail-content')
        if not detail_content:
            detail_content = soup  # Fallback to toàn bộ page
        
        # Title - h1 đầu tiên trong detail-content
        try:
            title_tag = detail_content.find('h1')
            if title_tag:
                result['title'] = safe_text(title_tag)
        except:
            pass
        
        # Description - div.leadpost p
        try:
            leadpost = detail_content.find('div', class_='leadpost')
            if leadpost:
                result['description'] = safe_text(leadpost)
            else:
                # Fallback to meta description
                meta_desc = soup.find('meta', attrs={'name': 'description'})
                if meta_desc:
                    result['description'] = meta_desc.get('content', '')
        except:
            pass
        
        # Author - thử tìm nhiều vị trí
        try:
            # Từ script JSON-LD
            script_tag = soup.find('script', type='application/ld+json')
            if script_tag:
                import json
                try:
                    data = json.loads(script_tag.string)
                    if isinstance(data, dict) and 'author' in data:
                        author_data = data.get('author', {})
                        if isinstance(author_data, dict):
                            result['author_name'] = author_data.get('name')
                        elif isinstance(author_data, str):
                            result['author_name'] = author_data
                except:
                    pass
            
            if not result['author_name']:
                author_tag = soup.find('span', class_='author') or soup.find('a', class_='author')
                result['author_name'] = safe_text(author_tag)
        except:
            pass
        
        # Thông tin thời gian chế biến
        try:
            ready_items = soup.select('ul.ready li')
            for item in ready_items:
                h2_tag = item.find('h2')
                span_tag = item.find('span')
                if h2_tag and span_tag:
                    label = safe_text(h2_tag).lower()
                    value = safe_text(span_tag)

                    # Chỉ lấy "chế biến"
                    if 'chế biến' in label:
                        result['cook_time'] = normalize_time(value)
        except:
            pass

        # Số người - từ div.staple h2 small
        try:
            staple_div = soup.find('div', class_='staple')
            if staple_div:
                h2_tag = staple_div.find('h2')
                if h2_tag:
                    small_tag = h2_tag.find('small')
                    if small_tag:
                        raw_people = safe_text(small_tag).strip()

                        # Bỏ chữ "Cho"
                        raw_people = raw_people.lower()
                        if raw_people.startswith("cho"):
                            raw_people = raw_people[3:].strip()

                        result['num_of_people'] = raw_people
        except:
            pass
        
        # Ingredients - div.staple span
        try:
            ingredients = []
            staple_div = soup.find('div', class_='staple')
            if staple_div:
                ing_spans = staple_div.find_all('span', recursive=False)
                for span in ing_spans:
                    # Lấy tên nguyên liệu
                    name_parts = []
                    for content in span.contents:
                        if isinstance(content, str):
                            text = content.strip()
                            if text:
                                name_parts.append(text)
                    
                    name = ' '.join(name_parts).strip()
                    
                    # Lấy số lượng từ small
                    small_tag = span.find('small')
                    quantity = safe_text(small_tag) if small_tag else ''
                    
                    # Lấy ghi chú từ em
                    em_tag = span.find('em')
                    note = safe_text(em_tag) if em_tag else ''
                    
                    # Ghép lại
                    if name:
                        ingredient_text = name
                        if quantity:
                            ingredient_text = f"{quantity}" + f" {ingredient_text}"
                        if note:
                             ingredient_text += f" {note}"
                        ingredients.append(ingredient_text.strip())
            
            result['ingredients'] = ingredients
            result['num_of_ingredients'] = len(ingredients)
        except:
            pass
        
        # Steps - div.method ul li
        try:
            steps = []
            method_div = soup.find('div', class_='method')
            if method_div:
                step_items = method_div.find_all('li')
                for item in step_items:
                    # Lấy số bước từ label
                    label_tag = item.find('label')
                    step_num = safe_text(label_tag) if label_tag else ''
                    
                    # Lấy tiêu đề bước từ h3
                    h3_tag = item.find('h3')
                    step_title = safe_text(h3_tag) if h3_tag else ''
                    
                    # Lấy nội dung từ div.text-method
                    text_div = item.find('div', class_='text-method')
                    if text_div:
                        # Lấy tất cả p tags
                        p_tags = text_div.find_all('p')
                        contents = []
                        for p in p_tags:
                            text = safe_text(p)
                            if text:
                                contents.append(text)
                        step_content = ' '.join(contents)
                    else:
                        step_content = safe_text(item)
                    
                    # Ghép thành 1 bước
                    if step_content:
                        if step_num and step_title:
                            step_text = f"Bước {step_num}: {step_title}: {step_content}"
                        elif step_num:
                            step_text = f"Bước {step_num}: {step_content}"
                        else:
                            step_text = step_content
                        steps.append(step_text)
            
            result['step'] = steps
        except:
            pass
        
        # Notes - div.tipsrecipe
        try:
            notes = []
            tips_divs = soup.select('div.tipsrecipe, div.infobox, div.tips')
            for tips in tips_divs:
                text = safe_text(tips)
                if text:
                    # Loại bỏ "Mách nhỏ:" prefix
                    text = re.sub(r'^Mách nhỏ:\s*', '', text)
                    notes.append(text)
            result['note'] = notes
        except:
            pass
        
        # Post date - thử tìm từ nhiều nguồn
        try:
            # Từ meta hoặc span.date
            date_tag = soup.find('span', class_='date') or soup.find('time')
            if date_tag:
                result['post_date'] = safe_text(date_tag)
        except:
            pass
        
        return result
        
    except Exception as e:
        print(f"  [ERROR] {url}: {e}")
        return result

In [20]:
## Test trên 1 URL
test_url = all_foods_df.iloc[1]['url']
test_category = all_foods_df.iloc[1]['category']
test_food = get_food_detail_dmx(test_url, test_category)
test_food

{'link': 'https://www.dienmayxanh.com/vao-bep/cach-nau-ga-ac-tan-ham-ngai-cuu-cuc-ngon-bo-mau-huyet-01384',
 'type_of_food': 'Món canh',
 'title': 'Cách hầm gà lá ngải bằng nồi cơm điện đậm đà bổ dưỡng cho sức khỏe cả nhà',
 'description': 'Nếu bạn cần một gợi ý cho một món từ gà thơm ngon bổ dưỡng thì món gà hầm lá ngải sẽ là một món tuyệt vời không thể bỏ qua. Cùng Điện máy XANH vào bếp và thực hiện món canh này và mời người cùng thưởng thức ngay nào.',
 'author_name': None,
 'cook_time': '90 phút',
 'num_of_people': '3 người',
 'calories': None,
 'num_of_ingredients': 7,
 'ingredients': ['1 con Gà (khoảng 1.3 kg)',
  '1 củ Gừng',
  '50 gr Táo đỏ',
  '20 gr Kỷ tử',
  '1 ít Ngải cứu khô',
  '100 gr Ngải cứu tươi',
  '1 ít Gia vị thông dụng (Muối/ đường)'],
 'step': ['Bước 1: Sơ chế nguyên liệu: Gà bạn làm sạch rồi chà xát gà với 1 muỗng canh muối để khử bớt mùi hôi, sau đó bạn rửa sạch một lần nữa. Tiếp theo bạn chặt gà thành những miếng vừa ăn. Gừng bạn gọt vỏ, rửa sạch và cắt lát. Táo đỏ, kỷ tử mua về bạn đem đi ngâm với nước khoảng 15 phút. Sau đó, rửa lại với nước rồi để ráo. Lá ngải cứu nhặt lấy phần ngọn và lá non, sau đó bạn ngâm trong nước muối loãng trong vòng 15 phút, lấy ra để ráo.',
  'Bước 2: Luộc sơ gà: Bạn cho gà vào nồi , thêm vào 1 lít nước lọc sao cho nước vừa ngập hết phần thịt. Khi nước sôi khoảng 3 phút thì bạn vớt thịt ra tô .',
  'Bước 3: Hầm gà với lá ngải: Bạn cho gà đã luộc, táo đỏ, hạt kỷ tử, ngải cứu khô, gừng cắt lát, lá ngải cứu tươi và 1 lít nước vào nồi cơm điện . Sau đó bạn bật chế độ nấu, canh thời gian 1 tiếng.',
  'Bước 4: Hoàn thành: Sau 1 tiếng thì bạn nêm 1 muỗng cà phê muối, 1 muỗng cà phê đường. Sau đó nêm nếm lại sao cho vừa ăn.',
  'Bước 5: Thành phẩm: Vậy là bạn đã có được món gà hầm lá ngải cực thơm ngon hấp dẫn rồi. Khi ăn bạn sẽ cảm nhận được thịt gà mềm ngon, thấm vị cùng với nước hầm ngọt thanh bổ dưỡng sẽ làm cho món ăn thêm phần hấp dẫn hơn.'],
 'note': ['Xem chi tiết: Cách chọn mua thịt gà tươi ngon',
  'Xem thêm: Ngải cứu có tác dụng gì? Tác dụng của ngải cứu và lưu ý khi dùng',
  'Xem thêm:'],
 'post_date': None}

# 4. Áp dụng hàm crawl trên toàn bộ urls

In [21]:
import re

# Hàm lọc URL món ăn hợp lệ (tránh url của trang nhiều món)
def check_valid_format(url):
    slug = url.rstrip('/').split('/')[-1].lower()

    # Trang tổng hợp nhiều món – bắt đầu bằng số lượng món
    if re.match(r'^\d+-cach', slug):
        return False

    # Tong hop
    if slug.startswith("tong-hop-"):
        return False

    # Các dạng tổng hợp khác
    if "cac-mon" in slug or "nhung-mon" in slug or "mon-ngon" in slug:
        return False

    # Mặc định: hợp lệ
    return True

In [22]:
test_df = all_foods_df.tail(100)

for idx, row in test_df.iterrows():
    url = row['url']
    if not(check_valid_format(url)):
        print(f"{url} => Invalid")

https://www.dienmayxanh.com/vao-bep/3-cach-lam-sushi-cuon-bo-la-mieng-hap-dan-cuc-don-gian-10915 => Invalid
https://www.dienmayxanh.com/vao-bep/tong-hop-cac-nguyen-lieu-lam-pho-cuon-day-du-chuan-vi-ha-noi-23528 => Invalid
https://www.dienmayxanh.com/vao-bep/3-cach-lam-banh-da-tron-thom-ngon-la-mieng-doi-vi-cho-bua-an-09662 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-vo-banh-trang-cuon-cha-gio-don-gian-an-toan-04602 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-pha-nuoc-cham-pho-cuon-dam-da-ngon-de-lam-chuan-vi-14117 => Invalid
https://www.dienmayxanh.com/vao-bep/3-cach-lam-mit-tron-da-nang-sieu-ngon-chuan-vi-de-lam-tai-nha-14511 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-goi-cuon-ca-ngu-kieu-thai-va-hat-quinoa-moi-la-don-05165 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-goi-cuon-thit-ga-thanh-mat-thom-ngon-don-gian-cho-05208 => Invalid
https://www.dienmayxanh.com/vao-bep/tong-hop-8-cach-lam-goi-cuon-thom-ngon-dinh-duong-cho-ca-nha-13019 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-pho-cuon-thit-bam-sieu-ngon-hap-dan-de-lam-ngay-14646 => Invalid
https://www.dienmayxanh.com/vao-bep/tong-hop-11-cach-lam-cac-mon-trung-cuon-ngon-don-gian-bo-13202 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-bo-cuon-cai-xanh-hap-dan-de-lam-tai-nha-cho-bua-an-07269 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-xa-lach-xoong-nhat-tron-thit-bo-va-tai-heo-ngon-de-10211 => Invalid
https://www.dienmayxanh.com/vao-bep/3-cach-lam-mi-tron-muoi-ot-trung-muoi-va-kim-chi-ngon-tuyet-01781 => Invalid
https://www.dienmayxanh.com/vao-bep/tong-hop-13-cach-lam-bun-tron-ngon-don-gian-de-lam-cho-bua-14552 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-mi-soba-vit-va-nam-dui-ga-dam-da-mem-ngon-cuc-hap-04164 => Invalid
https://www.dienmayxanh.com/vao-bep/3-cach-lam-sushi-thanh-cua-ngon-mieng-de-lam-chuan-vi-nha-13143 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-goi-cuon-ca-hoi-don-gian-thanh-mat-va-dinh-duong-05262 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-mi-tron-chua-cay-thai-lan-thom-ngon-bung-vi-don-09772 => Invalid
https://www.dienmayxanh.com/vao-bep/2-cach-lam-trung-cuon-ngu-sac-ngon-mieng-dep-mat-de-lam-cho-11404 => Invalid

In [ ]:
total = len(all_foods_df)
all_foods = []
failed_urls = []
CHECKPOINT = 100

for i, row in all_foods_df.iterrows():
    category = row['category']
    url = row['url']

    # Print header line
    print(f"[{i+1}/{total}] {url}")

    # 1) Skip sớm – không tốn request
    if not check_valid_format(url):
        print("   → INVALID SLUG → SKIPPED")
        failed_urls.append((category, url, "Invalid slug"))
        continue

    try:
        # 2) Crawl detail
        detail = get_food_detail_dmx(url, category)

        # 3) Validate kết quả
        if detail['step'] and len(detail['ingredients']) > 0:
            print("   → OK")
            all_foods.append(detail)
        else:
            print("   → MISSING DATA")
            failed_urls.append((category, url, "Missing data"))

        # 4) Checkpoint
        if (i + 1) % CHECKPOINT == 0:
            pd.DataFrame(all_foods).to_csv('dienmayxanh_foods_checkpoint.csv', index=False)
            print(f"[CHECKPOINT] Checkpoint saved ({len(all_foods)} foods)")

        # 5) Delay
        time.sleep(random.uniform(MIN_DELAY, MAX_DELAY))

    except Exception as e:
        print(f"   → ERROR: {e}")
        failed_urls.append((category, url, str(e)))

print(f"\nSuccess: {len(all_foods)}")
print(f"Failed: {len(failed_urls)}")

[1/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-ngot-chay-dau-hu-thom-ngon-thanh-mat-don-11520
   → INVALID SLUG → SKIPPED
[2/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-ga-ac-tan-ham-ngai-cuu-cuc-ngon-bo-mau-huyet-01384
   → OK
[3/13515] https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-dua-leo-xuong-heo-nhoi-thit-va-tom-thanh-mat-05075
   → INVALID SLUG → SKIPPED
[4/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-nam-can-tay-de-lam-de-an-thom-nuc-mui-07891
   → OK
[5/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-cua-chay-thom-ngon-don-gian-02693
   → OK
[6/13515] https://www.dienmayxanh.com/vao-bep/cac-mon-canh-mua-dong-mien-bac-de-nau-giu-am-co-the-23616
   → INVALID SLUG → SKIPPED
[7/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-gio-heo-ham-cu-cai-muoi-thom-ngon-bo-duong-ca-nha-07674
   → OK
[8/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-minh-thai-han-quoc-bo-duong-la-mieng-cuc-09540
   → OK
[9/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ca-me-nau-me-dau-thom-ngon-bang-noi-lau-da-nang-tien-22348
   → OK
[10/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-ke-ga-ngoc-ke-ngon-thom-beo-voi-noi-lau-hap-da-22987
   → INVALID SLUG → SKIPPED
[11/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-bi-do-mem-ngon-bo-duong-cho-bua-com-gia-06076
   → OK
[12/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-can-tay-ca-vien-thom-ngon-thanh-dam-cho-bua-com-05910
   → OK
[13/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-bo-vien-nau-nam-va-nau-rau-cu-thanh-mat-cho-05008
   → INVALID SLUG → SKIPPED
[14/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-ma-de-tom-kho-ngon-mieng-bo-duong-de-lam-11759
   → OK
[15/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-dau-ca-hoi-voi-tom-va-mang-chua-thom-05830
   → INVALID SLUG → SKIPPED
[16/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-bap-cai-giam-can-thom-ngon-nhanh-chong-cho-nang-07272
   → OK
[17/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-sup-bong-cai-xanh-voi-rau-cu-va-kem-sua-thom-ngon-04904
   → INVALID SLUG → SKIPPED
[18/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chuoi-dau-thom-ngon-dam-da-cho-bua-com-gia-dinh-14886
   → OK
[19/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-ngheu-nau-khe-va-nau-rong-bien-thom-ngon-04918
   → INVALID SLUG → SKIPPED
[20/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-ca-chua-trung-dam-da-don-gian-de-lam-thom-05752
   → INVALID SLUG → SKIPPED
[21/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-dau-xanh-bi-do-thit-bam-bo-duong-bang-noi-inox-23234
   → OK
[22/13515] https://www.dienmayxanh.com/vao-bep/ngay-le-tet
   → MISSING DATA
[23/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-ca-nau-hoa-chuoi-me-thanh-mat-cho-bua-com-nha-23605
   → OK
[24/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-cua-bi-do-thom-ngon-bat-mat-khong-thua-ngoai-03210
   → OK
[25/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-sup-ca-chua-nuong-cuc-ngon-bo-duong-de-lam-05043
   → INVALID SLUG → SKIPPED
[26/13515] https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-hen-nau-chua-bau-va-rau-muong-thom-ngon-thanh-05409
   → INVALID SLUG → SKIPPED
[27/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-he-dau-hu-thit-bam-thom-ngon-la-mieng-17871
   → OK
[28/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-gio-heo-bac-thao-thom-ngon-moi-la-dam-vi-don-gian-08591
   → OK
[29/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bau-nhoi-thit-thom-ngon-thanh-dam-cho-ngay-nang-17218
   → OK
[30/13515] https://www.dienmayxanh.com/vao-bep/nuoc-ep
   → MISSING DATA
[31/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-rau-ram-thom-ngon-don-gian-cho-bua-com-06092
   → OK
[32/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-kho-qua-ca-ot-thom-ngon-thanh-mat-dam-d-02481
   → OK
[33/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-hen-nau-muop-thom-ngon-hap-dan-don-gian-vo-cung-16178
   → OK
[34/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-muop-nau-tom-kho-va-tom-tuoi-thom-ngon-don-05919
   → INVALID SLUG → SKIPPED
[35/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-ga-ham-hat-sen-tao-do-ky-tu-cuc-tot-cho-suc-23112
   → OK
[36/13515] https://www.dienmayxanh.com/vao-bep/thuc-don-com-toi-du-chat-cho-nguoi-ban-ron-00734
   → OK
[37/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-tom-moc-hat-sen-thanh-mat-cho-ngay-tet-04826
   → OK
[38/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-bong-he-dau-hu-non-va-thit-bam-thom-ngon-hap-05480
   → INVALID SLUG → SKIPPED
[39/13515] https://www.dienmayxanh.com/vao-bep/mon-xao
   → MISSING DATA
[40/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-day-nau-tom-hap-thanh-mat-giai-nhiet-ngay-08668
   → OK
[41/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ga-nau-toi-la-mieng-thom-ngon-bo-duong-cho-ca-nha-07845
   → OK
[42/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-luon-la-giang-va-bap-chuoi-dam-chat-nam-04851
   → INVALID SLUG → SKIPPED
[43/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rong-bien-ca-chua-thom-ngon-thanh-mat-co-the-13843
   → OK
[44/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-ngot-muop-va-nam-thom-ngon-thanh-nhiet-10248
   → INVALID SLUG → SKIPPED
[45/13515] https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-khoai-tay-don-gian-thom-ngon-ai-an-cung-thich-07903
   → INVALID SLUG → SKIPPED
[46/13515] https://www.dienmayxanh.com/vao-bep/mach-ban-cach-luoc-tiet-lon-min-toi-khong-bot-khi-cuc-de-voi-23363
   → OK
[47/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-bo-cau-ham-dau-xanh-dac-biet-hap-dan-cho-ca-nha-cung-13163
   → OK
[48/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-hat-mit-chay-moi-la-thom-ngon-don-gian-tai-09174
   → OK
[49/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-thit-trau-ham-sa-va-ham-khoai-tay-thom-ngon-don-09686
   → INVALID SLUG → SKIPPED
[50/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-thit-bam-sau-va-doc-mung-thanh-nhiet-05978
   → INVALID SLUG → SKIPPED
[51/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-khoai-mon-ham-xuong-va-tom-kho-ngot-bui-deo-03867
   → INVALID SLUG → SKIPPED
[52/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-duoi-heo-ham-khoai-mon-ngon-mieng-bui-beo-bo-10781
   → INVALID SLUG → SKIPPED
[53/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-bong-bi-ca-thac-lac-va-tom-thom-ngon-ngot-nhe-05031
   → INVALID SLUG → SKIPPED
[54/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-sup-khoai-tay-don-gian-thom-ngon-hap-dan-00072
   → OK
[55/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-den-thit-bam-va-tom-kho-ngot-mat-thom-04846
   → INVALID SLUG → SKIPPED
[56/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-trai-dieu-ngot-bui-giai-nang-ngay-he-cuc-16947
   → OK
[57/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mong-toi-nau-tom-tuoi-thanh-mat-sieu-don-gian-09728
   → OK
[58/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-ga-ham-tao-do-nam-dong-co-bo-duong-ngot-lanh-22458
   → OK
[59/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-trung-cut-lon-um-bau-thom-ngon-thanh-dam-cho-bua-com-11055
   → OK
[60/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cua-dong-ca-chua-thanh-mat-nuoc-dung-dam-da-de-23305
   → OK
[61/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-thit-bo-ca-chua-dam-da-thom-ngon-cho-be-08184
   → OK
[62/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-thit-ga-ca-rot-don-gian-thom-ngon-cuc-dam-da-03927
   → OK
[63/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bau-chay-thom-ngon-thanh-dam-cho-ngay-chay-14764
   → OK
[64/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chua-tep-thom-ngon-thanh-mat-don-gian-de-lam-08675
   → INVALID SLUG → SKIPPED
[65/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bau-thit-bo-ngon-ngot-thanh-mat-don-gian-tai-11276
   → OK
[66/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-ma-thit-bam-thom-ngon-ngot-nuoc-thanh-mat-11490
   → OK
[67/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-sup-gumbo-hai-san-va-thit-ga-dac-trung-cua-am-thuc-06653
   → INVALID SLUG → SKIPPED
[68/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-cu-sen-ham-xuong-dam-da-hap-dan-cho-bua-com-nha-14925
   → OK
[69/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-xa-lach-xoong-tom-tuoi-ngon-ngot-hap-dan-don-11567
   → OK
[70/13515] https://www.dienmayxanh.com/vao-bep/tong-hop-7-cach-nau-canh-trai-thanh-mat-hap-dan-de-lam-cho-13067
   → INVALID SLUG → SKIPPED
[71/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-thit-bo-ca-chua-thom-thanh-mat-thom-ngon-an-la-12749
   → OK
[72/13515] https://www.dienmayxanh.com/vao-bep/ngheu-nau-canh-gi-ngon-tong-hop-12-cach-nau-canh-ngheu-hap-09689
   → MISSING DATA
[73/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ca-cam-nau-canh-chua-la-giang-chua-ngot-thanh-mat-11859
   → OK
[74/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ga-la-giang-ngon-nhat-vi-chua-diu-thit-ga-00187
   → OK
[75/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-thit-vien-rau-cu-dinh-duong-thanh-mat-cho-bua-11025
   → OK
[76/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-lang-nau-thit-bam-thom-ngon-giai-nhiet-co-12373
   → OK
[77/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-tom-cu-hu-dua-thanh-mat-chua-ngot-cuc-bat-06554
   → OK
[78/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-trung-ca-nau-canh-chua-thanh-mat-giai-nhiet-ngay-he-22571
   → OK
[79/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-cu-lao-chay-thom-ngon-hap-dan-cho-ngay-chay-them-14178
   → OK
[80/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-song-nau-ngot-chua-ngot-bat-vi-cuc-bat-com-13297
   → OK
[81/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bap-ham-gio-heo-dam-vi-thanh-mat-cho-mam-com-12727
   → OK
[82/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-sau-thit-bam-va-suon-thanh-mat-thom-ngon-don-05479
   → INVALID SLUG → SKIPPED
[83/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-bi-dao-nau-xuong-va-nau-tom-thanh-mat-cho-bua-04674
   → INVALID SLUG → SKIPPED
[84/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-duoi-bo-ham-bia-mon-ngon-kho-cuong-dip-cuoi-tuan-09479
   → INVALID SLUG → SKIPPED
[85/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-chuoi-xanh-la-lot-thom-ngon-beo-bui-de-lam-07855
   → INVALID SLUG → SKIPPED
[86/13515] https://www.dienmayxanh.com/vao-bep/tong-hop-9-cach-nau-canh-he-thanh-nhiet-don-gian-cho-ngay-12227
   → INVALID SLUG → SKIPPED
[87/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-muc-nau-dua-ngot-thom-thanh-mat-bo-duong-cho-13842
   → OK
[88/13515] https://www.dienmayxanh.com/vao-bep/tong-hop-cac-loai-rau-nem-canh-chua-thong-dung-de-di-cho-23506
   → INVALID SLUG → SKIPPED
[89/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-duoi-heo-ham-dau-phong-ngot-thom-beo-bui-hap-dan-08975
   → OK
[90/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mang-tiet-nung-ninh-nuoc-canh-trong-veo-voi-noi-22773
   → OK
[91/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-luon-nghe-an-thom-ngon-chuan-vi-don-gian-04252
   → OK
[92/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ga-nau-cay-han-quoc-thom-nong-hap-dan-ngon-kho-cuong-08016
   → OK
[93/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-hau-ngon-ngot-mem-beo-bo-duong-de-lam-tai-nha-06757
   → OK
[94/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-bau-nau-hen-thanh-mat-don-gian-cho-ca-gia-dinh-09374
   → OK
[95/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-du-du-ham-xuong-ngon-mieng-bo-duong-tot-cho-suc-08844
   → OK
[96/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-bop-nau-ngot-thom-ngon-don-gian-hap-dan-ai-11121
   → OK
[97/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-ngot-khong-rau-ngot-chay-thanh-dam-ma-dua-13650
   → OK
[98/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-rau-den-tom-tuoi-ngon-ngot-thanh-mat-cho-gia-09553
   → OK
[99/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-canh-chua-cha-ca-thac-lac-thom-ngon-don-gian-tai-nha-08497
   → OK
[100/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-miso-rong-bien-chuan-bi-nhat-tai-gia-bang-noi-23086
   → OK
[CHECKPOINT] Checkpoint saved (65 foods)
[101/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-la-vong-vang-nau-canh-chua-thanh-mat-cho-bua-com-nha-23220
   → OK
[102/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-be-xanh-long-ga-thanh-mat-ngon-ngot-cho-bua-10614
   → OK
[103/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mong-toi-muop-ngon-ngot-don-gian-tai-nha-14538
   → OK
[104/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-trai-nau-bau-ngon-mieng-don-gian-cho-bua-com-11964
   → INVALID SLUG → SKIPPED
[105/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-dau-ca-thu-nau-canh-chua-cuc-ngon-an-la-ghien-15315
   → OK
[106/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-chan-gio-ham-mang-kho-chan-gio-ham-mang-kho-09312
   → OK
[107/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-ca-mu-nau-canh-chua-thom-ngon-dam-da-cho-bua-com-05666
   → INVALID SLUG → SKIPPED
[108/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-ngot-tom-tuoi-thanh-mat-giup-bua-com-gia-10473
   → OK
[109/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-su-hao-xuong-va-canh-su-hao-ca-chep-thom-ngon-15391
   → INVALID SLUG → SKIPPED
[110/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-mon-sup-ga-kieu-y-ngon-het-y-de-khong-tuong-ai-00302
   → OK
[111/13515] https://www.dienmayxanh.com/vao-bep/3-cach-lam-rau-cang-cua-nau-canh-ngon-va-thanh-mat-bang-noi-22781
   → INVALID SLUG → SKIPPED
[112/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ga-ham-sam-han-quoc-chuan-vi-han-de-tam-bo-ca-nha-23191
   → OK
[113/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-bap-chay-don-gian-thom-ngon-cho-ngay-chay-02677
   → OK
[114/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-ca-chach-nau-canh-chua-ngon-mieng-thanh-nhiet-don-08159
   → INVALID SLUG → SKIPPED
[115/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ga-quay-sieu-don-gian-nhanh-chong-moi-la-07287
   → OK
[116/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-xanh-thit-bam-thanh-mat-cho-ngay-nong-buc-13338
   → OK
[117/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-gan-bo-ham-hat-sen-va-dau-do-thom-ngon--02618
   → INVALID SLUG → SKIPPED
[118/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-tiet-canh-tho-thom-ngon-de-lam-don-gian-ngay-tai-14557
   → OK
[119/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-chay-nam-thanh-dam-bat-vi-cho-bua-com-chay-12274
   → OK
[120/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ngheu-nau-ngot-ngot-mat-giai-nhiet-co-the-cuc-11864
   → OK
[121/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-bun-bo-gan-thom-ngon-don-gian-de-lam-an-la-ghien-09328
   → OK
[122/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ca-chep-nau-me-chua-thanh-chuan-vi-bang-bo-noi-green-23340
   → OK
[123/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ngao-he-thom-ngon-giau-chat-dinh-duong-cho-bua-17875
   → OK
[124/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-rau-muong-nau-tom-thom-ngon-thanh-mat-tai-nha-05126
   → INVALID SLUG → SKIPPED
[125/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-doc-mung-nau-canh-chua-ca-me-thom-ngon-dam-da-cay-23584
   → OK
[126/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-chan-gio-ham-ngai-cuu-thom-ngon-bo-duong-07517
   → OK
[127/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-don-quang-ngai-dac-san-tru-danh-bang-noi-va-22669
   → OK
[128/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-ngong-tom-kho-don-gian-ngot-nuoc-thanh-mat-08873
   → OK
[129/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cua-rau-ngot-khong-tanh-thanh-mat-cho-mam-com-08998
   → OK
[130/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-gio-heo-rau-ngot-ngon-ngot-doi-mon-cho-bua-com-11862
   → OK
[131/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-tom-rau-muong-thanh-mat-giai-nhiet-cuc-12690
   → OK
[132/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-kim-chi-ca-hoi-va-ca-ngu-thom-ngon-moi-la-don-08496
   → INVALID SLUG → SKIPPED
[133/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cai-cuc-tan-o-nau-xuong-ngon-ngot-thanh-mat-cho-11344
   → OK
[134/13515] https://www.dienmayxanh.com/vao-bep/tong-hop-21-cach-nau-canh-thit-bam-don-gian-thanh-ngot-tai-11597
   → INVALID SLUG → SKIPPED
[135/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bap-cai-thit-bo-ngon-ngot-doi-vi-cho-bua-com-11701
   → OK
[136/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cu-cai-muoi-xa-bau-thom-ngon-bo-duong-hap-dan-13915
   → OK
[137/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-cua-rau-mong-toi-muop-thanh-mat-sieu-hap-dan-13902
   → OK
[138/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-sup-ga-khoai-tay-hap-dan-thom-beo-cho-be-08170
   → OK
[139/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ca-ngat-nau-canh-chua-thom-ngon-giai-nhiet-cuc-hap-07564
   → OK
[140/13515] https://www.dienmayxanh.com/vao-bep/3-cach-nau-vit-tiem-vua-ngon-vua-bo-ai-an-cung-khen--01464
   → INVALID SLUG → SKIPPED
[141/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-sup-bao-ngu-hai-sam-vi-ca-map-thom-ngon-sang-chanh-09227
   → OK
[142/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-kim-chi-thit-heo-cap-toc-don-gian-thom-ngon-08484
   → OK
[143/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-dua-chua-tom-va-ca-thom-ngon-de-lam-tai-nha-04591
   → INVALID SLUG → SKIPPED
[144/13515] https://www.dienmayxanh.com/vao-bep/mon-tu-bo
   → MISSING DATA
[145/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-ca-lang-sieu-bat-vi-dam-da-hap-dan-cho-bua-15259
   → OK
[146/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-khoai-mo-tom-tuoi-ngot-mat-hap-dan-cho-bua-com-11670
   → OK
[147/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-bap-cai-thit-bam-don-gian-thom-ngon-ngot-thanh-09186
   → OK
[148/13515] https://www.dienmayxanh.com/vao-bep/tong-hop-15-cach-nau-canh-ga-bo-duong-thom-ngon-don-gian-cho-07583
   → INVALID SLUG → SKIPPED
[149/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ky-tu-bo-duong-sang-mat-dep-da-don-gian-05196
   → OK
[150/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-cu-chuoi-nau-oc-buou-ngon-la-vi-tuyet-chieu-dai-08378
   → OK
[151/13515] https://www.dienmayxanh.com/vao-bep/3-cach-nau-canh-chua-muc-dam-da-don-gian-thom-ngon-cho-bua-05710
   → INVALID SLUG → SKIPPED
[152/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-ca-tim-nau-xuong-heo-ngon-ngot-la-mieng-doi-mon-12804
   → OK
[153/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-chua-ca-basa-tuyet-ngon-tai-nha-00575
   → OK
[154/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-sup-lo-dam-da-thom-ngon-cho-ca-gia-dinh-cung-14242
   → OK
[155/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-mong-toi-thit-bam-don-gian-tai-nha-cho-bua-com-11904
   → OK
[156/13515] https://www.dienmayxanh.com/vao-bep/cach-lam-ca-bong-lau-nau-mang-chua-thanh-nhiet-ngon-hap-dan-07632
   → OK
[157/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-canh-moc-nam-huong-ngot-thanh-chuan-vi-cho-mam-co-23415
   → OK
[158/13515] https://www.dienmayxanh.com/vao-bep/2-cach-nau-canh-ca-thac-lac-ca-chua-thom-ngon-don-gian-doi-vi-08551
   → INVALID SLUG → SKIPPED
[159/13515] https://www.dienmayxanh.com/vao-bep/cach-nau-duoi-heo-ham-dau-den-ngot-thom-cuc-bo-duong-cho-09025
   → OK
[160/13515] https://www.dienmayxanh.com/vao-bep/2-cach-lam-canh-khoai-mo-nau-tom-va-nau-thit-bam-thom-ngon-04686
   → INVALID SLUG → SKIPPED

## Phần này đã được chạy ở trên KAGGLE. Link: https://www.kaggle.com/code/minhtien3103/crawl-dienmayxanh-food

# Chuyển thành dataframe và lưu xuống

In [1]:
dmx_df = pd.DataFrame(all_foods)

NameError: name 'pd' is not defined

In [ ]:
dmx_df.head()

In [ ]:
# Lưu kết quả
dmx_df.to_csv('dienmayxanh_foods_detail.csv', index=False)
print(f"Saved {len(dmx_df)} foods")

if failed_urls:
    pd.DataFrame(failed_urls, columns=['category', 'url', 'error']).to_csv('dienmayxanh_failed_urls.csv', index=False)

Saved 252 recipes